### ISSUE TITLE
NullPointerException: Display state is null during Survey Activity Destruction

### ISSUE THREAD

**Issue by juliocbcotta** [mixpanel/mixpanel-android#117]
Hi, I got it from crashlytics:

``` Java
java.lang.RuntimeException: Unable to destroy activity {MY_APP_PACKAGE/com.mixpanel.android.surveys.SurveyActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:2735)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:2753)
       at android.app.ActivityThread.access$2100(ActivityThread.java:118)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:981)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:130)
       at android.app.ActivityThread.main(ActivityThread.java:3747)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:507)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.NullPointerException
       at com.mixpanel.android.surveys.SurveyActivity.isShowingSurvey(SurveyActivity.java:398)
       at com.mixpanel.android.surveys.SurveyActivity.onDestroy(SurveyActivity.java:301)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:2722)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:2753)
       at android.app.ActivityThread.access$2100(ActivityThread.java:118)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:981)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:130)
       at android.app.ActivityThread.main(ActivityThread.java:3747)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:507)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

I am not quite sure of the version I was using, since my gradle file was like
compile "com.mixpanel.android:mixpanel-android:4.2.+@aar"

**Comment by Momepukku** [comment]
Hi, I am also getting the same error. I'm using v4.6.4.
I have attached the trace(From crashlytics)

```java
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {MY_APP_PACKAGE/com.mixpanel.android.surveys.SurveyActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3609)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3627)
       at android.app.ActivityThread.access$1400(ActivityThread.java:139)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5249)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at com.mixpanel.android.surveys.SurveyActivity.onDestroySurvey(SurveyActivity.java:321)
       at com.mixpanel.android.surveys.SurveyActivity.onDestroy(SurveyActivity.java:305)
       at android.app.Activity.performDestroy(Activity.java:5583)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1117)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3596)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3627)
       at android.app.ActivityThread.access$1400(ActivityThread.java:139)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5249)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by joeatwork** [comment]
@Momepukku you may want to open another issue (this one is quite old, and they may not share the same root cause) (cc @yinfeiru )
