### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by phil-brown** [mixpanel/mixpanel-android#138]
_NullPointerException in Mixpanel 4.3.1_

```
java.lang.RuntimeException: Unable to destroy activity {com.nclexpn.hlt/com.mixpanel.android.surveys.SurveyActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3813)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3831)
       at android.app.ActivityThread.access$1500(ActivityThread.java:175)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1361)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.NullPointerException
       at com.mixpanel.android.surveys.SurveyActivity.isShowingSurvey(SurveyActivity.java:398)
       at com.mixpanel.android.surveys.SurveyActivity.onDestroy(SurveyActivity.java:301)
       at android.app.Activity.performDestroy(Activity.java:5623)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1123)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3800)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3831)
       at android.app.ActivityThread.access$1500(ActivityThread.java:175)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1361)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by badeleux** [comment]
java.lang.RuntimeException: Unable to destroy activity {com.ultimatefanlive.ultimatefanandroid/com.mixpanel.android.surveys.SurveyActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.mixpanel.android.mpmetrics.MixpanelAPI$People.append(java.lang.String, java.lang.Object)' on a null object reference
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3706)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3724)
       at android.app.ActivityThread.access$1400(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.mixpanel.android.mpmetrics.MixpanelAPI$People.append(java.lang.String, java.lang.Object)' on a null object reference
       at com.mixpanel.android.surveys.SurveyActivity.onDestroySurvey(SurveyActivity.java:321)
       at com.mixpanel.android.surveys.SurveyActivity.onDestroy(SurveyActivity.java:305)
       at android.app.Activity.performDestroy(Activity.java:6169)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1141)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3693)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3724)
       at android.app.ActivityThread.access$1400(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

on 4.5.3. Any Idea? ;)

**Comment by phil-brown** [comment]
@badeleux this is a separate bug - the stack trace is different. I would recommend opening a new bug [here](https://github.com/mixpanel/mixpanel-android/issues/new).

**Comment by joeatwork** [comment]
Hi, @badeleux ! Thanks for the report! I've filed issue #211 to record the issue.

I do have a few questions (you can answer them either here or in the new issue if you have the time) Mostly, are you passing `null` to MixpanelAPI.getPeople().identify() anywhere in your code?

Thanks again for the report, and I'm sorry for the inconvenience!
