### ISSUE TITLE
Debug message causes crash when fallback is disabled

### ISSUE THREAD

**Issue by sciutand** [mixpanel/mixpanel-android#160]
using version 4.5.2
```
lAPI.AnalyticsMessages  E  Worker threw an unhandled exception
                        E  java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
                        E      at com.mixpanel.android.mpmetrics.DecideChecker.getDecideResponseFromServer(DecideChecker.java:203)
                        E      at com.mixpanel.android.mpmetrics.DecideChecker.runDecideCheck(DecideChecker.java:72)
                        E      at com.mixpanel.android.mpmetrics.DecideChecker.runDecideChecks(DecideChecker.java:54)
                        E      at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMes
                           sages.java:259)
                        E      at android.os.Handler.dispatchMessage(Handler.java:102)
                        E      at android.os.Looper.loop(Looper.java:135)
                        E      at android.os.HandlerThread.run(HandlerThread.java:61)
                        E  Mixpanel will not process any more analytics messages
                        E  java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
                        E      at com.mixpanel.android.mpmetrics.DecideChecker.getDecideResponseFromServer(DecideChecker.java:203)
                        E      at com.mixpanel.android.mpmetrics.DecideChecker.runDecideCheck(DecideChecker.java:72)
                        E      at com.mixpanel.android.mpmetrics.DecideChecker.runDecideChecks(DecideChecker.java:54)
                        E      at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMes
                           sages.java:259)
                        E      at android.os.Handler.dispatchMessage(Handler.java:102)
                        E      at android.os.Looper.loop(Looper.java:135)
                        E      at android.os.HandlerThread.run(HandlerThread.java:61)
                        V  Dead mixpanel worker dropping a message: 13 (Thread 1)
                        V  Dead mixpanel worker dropping a message: 2 (Thread 1)
```

After that worker stays dead and all messages are dropped.

**Comment by sciutand** [comment]
I just checked where the code fails 203. turning off debug will fix the issue. 

FYI upon app start up I do get the below so not sure why the fallback is not in the uri[]:

```
panelAPI.Configuration  V  Mixpanel configured with:
                        V      AutoShowMixpanelUpdates true
                        V      BulkUploadLimit 40
                        V      FlushInterval 60000
                        V      DataExpiration 432000000
                        V      DisableFallback true
                        V      DisableAppOpenEvent false
                        V      DisableDeviceUIBinding false
                        V      DisableEmulatorUIBinding false
                        V      EnableDebugLogging true
                        V      TestMode false
                        V      EventsEndpoint https://api.mixpanel.com/track?ip=1
                        V      PeopleEndpoint https://api.mixpanel.com/engage
                        V      DecideEndpoint https://decide.mixpanel.com/decide
                        V      EventsFallbackEndpoint http://api.mixpanel.com/track?ip=1
                        V      PeopleFallbackEndpoint http://api.mixpanel.com/engage
                        V      DecideFallbackEndpoint http://decide.mixpanel.com/decide
                        V      EditorUrl wss://switchboard.mixpanel.com/connect/
```

Shouldn't the sdk/worker be able to recover from such an error rather than just stay dead? Doesn't seem to be very resilient.

**Comment by arittr** [comment]
@sciutand turning off debug will absolutely solve the issue - this is a bug that will hopefully be patched in the next release. the reason for this crash is that we took the fallback decide URL out of the library - in the case that the device couldn't connect over SSL our library went into a loop that repeatedly checked both HTTP and HTTPS endpoints for results (creating a ton of request amplification on our end). this was  a temporary fix that will be resolved going forward. let me know if you have more questions here!

**Comment by joeatwork** [comment]
I've scheduled this for a fix in the next release.

**Comment by Quuxplusone** [comment]
Looks like Joe fixed this in https://github.com/mixpanel/mixpanel-android/commit/694efa3308ba9bc5b4c3be81b46a5db7814fb050.

**Comment by yinfeiru** [comment]
@Quuxplusone lol
Closing
