### ISSUE TITLE
Possible Resource Leak in ServerMessage.performRequest

### ISSUE THREAD

**Issue by phil-brown** [mixpanel/mixpanel-android#162]
With strict mode on, I get this error with Mixpanel 4.5.1:

````
01-20 17:32:29.757    2740-2749/info.hltcorp.ndbeII E/StrictMode﹕ A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'close' not called
            at dalvik.system.CloseGuard.open(CloseGuard.java:184)
            at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:300)
            at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:257)
            at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:210)
            at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:477)
            at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:432)
            at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:282)
            at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:232)
            at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:80)
            at libcore.net.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:188)
            at libcore.net.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:280)
            at com.mixpanel.android.mpmetrics.ServerMessage.performRequest(ServerMessage.java:96)
            at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.sendData(AnalyticsMessages.java:391)
            at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.sendAllData(AnalyticsMessages.java:362)
            at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:252)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.os.HandlerThread.run(HandlerThread.java:60)
````

**Comment by joeatwork** [comment]
That is a super weird error, so I've got a few follow-up questions.

Do you experience this error often (on every test run) or occasionally?
Have you experienced the issue in a more recent version? (The code in your stack trace hasn't changed much since 4.5.1, so even if you haven't I don't imagine the issue is fixed.)
Are there any stack traces near the error? In particular, anything with log tag "MixpanelAPI.ServerMessage"?

Finally, if you can reproduce this easily, would you consider running your failure case with the following meta-data tag in your AndroidManifest.xml

```xml
<meta-data android:name="com.mixpanel.android.MPConfig.EnableDebugLogging"
                   android:value="true" />
```

**Comment by phil-brown** [comment]
This is very difficult to reproduce. I have seen it more - but cannot reliably reproduce it.

**Comment by joeatwork** [comment]
No worries, I'm going to leave this issue open and keep an eye out for it here.

Thanks again for the report!

**Comment by phil-brown** [comment]
Sounds good! I have updated to the latest release (4.5.3), and I still see this output sometimes.

**Comment by yinfeiru** [comment]
@phil-brown Sorry for the late. Are you still seeing this issue with the latest lib? Please re-open if you see it.
