### ISSUE TITLE
PersistentIdentity : OutOfMemoryError

### ISSUE THREAD

**Issue by fred8** [mixpanel/mixpanel-android#180]
Hey!

I noticed recently a new crash in my crash report tool. I didn't had a chance to reproduce it out of the wild.

Here is the stack trace:

java.lang.OutOfMemoryError
       at java.lang.String.(String.java:422)
       at java.lang.AbstractStringBuilder.toString(AbstractStringBuilder.java:642)
       at java.lang.StringBuilder.toString(StringBuilder.java:663)
       at org.json.JSONStringer.toString(JSONStringer.java:430)
       at org.json.JSONArray.toString(JSONArray.java:575)
       at com.mixpanel.android.mpmetrics.PersistentIdentity.writeIdentities(PersistentIdentity.java:380)
       at com.mixpanel.android.mpmetrics.PersistentIdentity.storeWaitingPeopleRecord(PersistentIdentity.java:142)
       at com.mixpanel.android.mpmetrics.MixpanelAPI.recordPeopleMessage(MixpanelAPI.java:1718)
       at com.mixpanel.android.mpmetrics.MixpanelAPI.access$800(MixpanelAPI.java:112)
       at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl.set(MixpanelAPI.java:1130)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1030)

**Comment by joeatwork** [comment]
I suspect I know a possible cause!

When you make calls to Mixpanel.getPeople().set or other people analytics methods, but don't call Mixpanel.getPeople().identify(), the changes you make end up stored on the device in persistent memory. This is true even if you call Mixpanel.identify() - the people version is required to send set() and other updates to the server.  The changes get purged when you finally do call getPeople().identify. I suspect you're getting this error because the library is attempting to store a very large value from a single set, or append the value of a new set to a large array of other waiting values.

If I'm right, this is still a bug (The Mixpanel library should *never* crash you app under any circumstances) but you can work around the issue by being sure to call Mixpanel.getPeople().identify() before you call set() or any of the other people analytics methods.

On the other hand, if you're sure that you *do* call getPeople().identify() before you make any calls to set(), then I'm barking up the wrong tree- please let me know if that is the case!

Thank so much for this report!

**Comment by fred8** [comment]
@joeatwork Thank you for the quick feedback. We stopped to do set people properties while identify was not called yet.

**Comment by joeatwork** [comment]
Glad that helped! I'm going to leave this bug open (again, we don't want to throw runtime exceptions out of the library!) but I'm glad that the fix worked for you!

**Comment by fred8** [comment]
@joeatwork So we applied the change (stopped to do set people properties while identify was not called) and the same issue appear again on our crash report tool.

**Comment by joeatwork** [comment]
Thanks for keeping us up to date on this!

Note to maintainers: I suspect this has to do with giant queues in persistent people properties already written to the device. Fix should truncate the queue if an OOM occurs (which can be done directly in storage)

**Comment by fred8** [comment]
@joeatwork Thanks for your super reactive support!

**Comment by fred8** [comment]
Hey @joeatwork, 

We still have that issue with the version 4.6.1.
Is that possible to have a fix for it? It's crashing our app pretty often.

Thank you!

**Comment by joeatwork** [comment]
Thanks for the update! We'll need to address the crashes in the next release.

**Comment by fred8** [comment]
Hi @joeatwork ,

We are keep getting that crash and it's a very important one in our crash report tool. We have hundreds of users that are blocked with this issue -- they can't open the app. 
I would very appreciate to get a fix quickly now.

Again, here is the crashlog.

Thank you for your understanding.

Fred

java.lang.OutOfMemoryError
       at java.lang.String.(String.java:432)
       at java.lang.AbstractStringBuilder.toString(AbstractStringBuilder.java:642)
       at java.lang.StringBuilder.toString(StringBuilder.java:663)
       at org.json.JSONStringer.toString(JSONStringer.java:430)
       at org.json.JSONArray.toString(JSONArray.java:545)
       at com.mixpanel.android.mpmetrics.PersistentIdentity.writeIdentities(PersistentIdentity.java:421)
       at com.mixpanel.android.mpmetrics.PersistentIdentity.storeWaitingPeopleRecord(PersistentIdentity.java:175)
       at com.mixpanel.android.mpmetrics.MixpanelAPI.recordPeopleMessage(MixpanelAPI.java:2020)
       at com.mixpanel.android.mpmetrics.MixpanelAPI.access$800(MixpanelAPI.java:114)
       at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl.set(MixpanelAPI.java:1390)

**Comment by joeatwork** [comment]
Got it. Just to confirm, you're calling getPeople().identify() on application start up already? You're not calling set() before identify() in the latest version of your code? (Otherwise, the workaround is to only call set() after you identify the people record)

**Comment by joeatwork** [comment]
@fred8 would you consider reaching out to support@mixpanel.com? We might be able to dig deeper into your code person to person.

**Comment by fred8** [comment]
@joeatwork We just updated to the very last version, so I suppose that it hasn't been fixed in 4.6.2, correct?

**Comment by joeatwork** [comment]
It looks like the crash is during a write, which is a surprise if you're never writing before identify, so it might be good to get in touch with us and see what's going on.

**Comment by RomainPiel** [comment]
I just noticed this issue in our instrumentation tests. We're using version 4.7.0. Has this been fixed?
```
java.lang.OutOfMemoryError
    at java.lang.String.(String.java:432)
    at java.lang.AbstractStringBuilder.toString(AbstractStringBuilder.java:642)
    at java.lang.StringBuilder.toString(StringBuilder.java:663)
    at org.json.JSONStringer.toString(JSONStringer.java:430)
    at org.json.JSONArray.toString(JSONArray.java:545)
    at com.mixpanel.android.mpmetrics.PersistentIdentity.writeIdentities(PersistentIdentity.java:421)
    at com.mixpanel.android.mpmetrics.PersistentIdentity.setEventsDistinctId(PersistentIdentity.java:149)
    at com.mixpanel.android.mpmetrics.MixpanelAPI.identify(MixpanelAPI.java:390)
    at com.myapp.MixpanelClient.setDeviceIdentifier(MixpanelClient.java:48)
...
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
    at android.support.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:534)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
    at android.app.ActivityThread.access$600(ActivityThread.java:130)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4745)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by joeatwork** [comment]
This sort of issue often rises when you call set() & friends without identifying the user first - the library tries to fix things by storing up all of your changes. The best fix for this issue is to always call identify() before setting people properties.

**Comment by RomainPiel** [comment]
`identify()` is definitely happening before `getPeople().set()`, that's part of our initialisation:
```java
    public MixpanelClient(MixpanelAPI mixpanelAPI) {
        this.sharedMixpanelAPI = mixpanelAPI;

        // init core properties
        setDeviceIdentifier("");
        setUserId("0");
    }

    public void setDeviceIdentifier(String deviceIdentifier) {
        sharedMixpanelAPI.identify(deviceIdentifier);
    }

    public void setUserId(String userId) {
        sharedMixpanelAPI.getPeople().set("user_id", userId);
    }
```

**Comment by ryanseams** [comment]
thanks for jumping in here @joeatwork and shedding some light on this issue.

@RomainPiel one thing I noticed is that in your code you use ```sharedMixpanelAPI.identify()```, however, the identify which actually flushes these calls (and prevents against this crash) is ```sharedMixpanelAPI.getPeople().identify()```.

other reports of this crash are instances where ```getPeople().identify()``` is conditionally called and for guests/anonymous users who never get identified the queue of updates builds up so large it causes the crash.

**Comment by RomainPiel** [comment]
Thanks for the explanations @ryanseams I'm not sure to understand the fix, should I replace the `identify()` by `getpeople().identify()`? Does it do the same thing at the end?

**Comment by ryanseams** [comment]
hi @RomainPiel -- ```identify()``` is used to set the user's distinct id for their events, whereas ```getPeople().identify()``` is used to set the user's distinct id for their profile as well as send any queued waiting people updates on the device.

as the crash is occurring when you are trying to add another people update to the queue on the device, you would want to call ```getPeople().identify()``` in order to flush the queued updates from the device to Mixpanel and avoid future crashes when making additional people updates.

one thing to note: if the user does not have a profile, at the point of calling ```getPeople().identify()``` this will create a new profile for this user. if you do not want to create a profile for the user (because for example they are a guest) we would need to discuss some alternative solutions specific to your usage case.

**Comment by RomainPiel** [comment]
OK cool, I'll have a closer look at out requirements after my Christmas vacations. Thanks for your help!!

**Comment by RomainPiel** [comment]
Looks like calling `getPeople().identify()` before `getPeople().set()` fixes the issue, thanks! This sequence of instructions is not really obvious, maybe `getPeople().set()` should throw an exception if `getPeople().identify()` was not called before?

**Comment by ryanseams** [comment]
you do not have to call ```getPeople().identify()``` if you wish to only queue an update to Mixpanel. this is helpful when you wish to track data on a guest before they create a profile so that when you do call ```getPeople().identify()``` their profile has historical information included.

that being said, over time as you make more and more updates, the queue will fill up and this crash can occur. it would make sense to add some exception handling for this case to fix the size of the queue should there be a large number of people updates waiting.

**Comment by SwiftyWang** [comment]
have it fixed or not? if fixed in which version?
