### ISSUE TITLE
ConcurrentModificationException - com.mixpanel.android.mpmetrics.MixpanelAPI.track(MixpanelAPI.java:364)

### ISSUE THREAD

**Issue by arittr** [mixpanel/mixpanel-android#183]
Using 4.5.3

java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:278)
at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
at java.util.concurrent.FutureTask.run(FutureTask.java:137)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:856)
Caused by: java.util.ConcurrentModificationException
at java.util.HashMap$HashIterator.nextEntry(HashMap.java:792)
at java.util.HashMap$KeyIterator.next(HashMap.java:819)
at com.mixpanel.android.mpmetrics.MixpanelAPI.track(MixpanelAPI.java:364)
...
at android.os.AsyncTask$2.call(AsyncTask.java:264)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
at java.util.concurrent.FutureTask.run(FutureTask.java:137)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:856)

Line 364 ( final String key = (String) superIter.next(); ) is in the middle of the process that resolves Super Properties and injects them into the final properties dict to be dispatched to Mixpanel. The customer is using Mixpanel from multiple threads.

**Comment by joeatwork** [comment]
Right now, we expose a shared JSONObject to callers of getSuperProperties, this will be fixed in v4.5.4 with commit c7f035a11de47a1a79ef0d8ea2b43bfc6115efc1

**Comment by joeatwork** [comment]
This is fixed in 4.5.4
