### ISSUE TITLE
OutOfMemoryError: DecideChecker.getNotificationImage()

### ISSUE THREAD

**Issue by fred8** [mixpanel/mixpanel-android#189]
Hey,

MP SDK: 4.5.3
Just to let you know about a recent crash report I got. Not so much info to repro it.

DecideChecker.java line 231
com.mixpanel.android.mpmetrics.DecideChecker.getNotificationImage

java.lang.OutOfMemoryError
       at android.graphics.BitmapFactory.nativeDecodeByteArray(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:596)
       at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:619)
       at com.mixpanel.android.mpmetrics.DecideChecker.getNotificationImage(DecideChecker.java:231)
       at com.mixpanel.android.mpmetrics.DecideChecker.runDecideCheck(DecideChecker.java:85)
       at com.mixpanel.android.mpmetrics.DecideChecker.runDecideChecks(DecideChecker.java:54)
       at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:253)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by joeatwork** [comment]
Thanks for this report!

**Comment by fred8** [comment]
@joeatwork I'm still getting a bunch of error in production for that one. Any plans to get it fixed soon?
Thank you!

**Comment by joeatwork** [comment]
I'd like to get a fix for this in the next release

**Comment by yinfeiru** [comment]
@fred8 Are you still seeing this issue? Please re-open if you are.
