### ISSUE TITLE
IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by mwelham** [mixpanel/mixpanel-android#205]
Hey,

Repeatable crash (happens enough that I can grab it in a debugger and get any other info you need).

'com.mixpanel.android:mixpanel-android:4.5.3'

Seems to happen when we're changing activities, and have recently set/unset properties with MixpanelAPI.People.set(String propertyName, Object value)

Properties never seem to end up in our Mixpanel account.

Please let me know whatever I else I can provide to get this resolved.

Full stack traces are below (one exception causes another). The last non-Android line is:
com.mixpanel.android.mpmetrics.InAppFragment.cleanUp(InAppFragment.java:221)

Cheers
Mike

04-16 15:59:59.490 16632-16632/com.devicemagic.androidx.forms E/AndroidRuntime﹕ FATAL EXCEPTION: main
Process: com.devicemagic.androidx.forms, PID: 16632
java.lang.RuntimeException: Unable to pause activity {com.devicemagic.androidx.forms/com.devicemagic.androidx.forms.ui.BaseActivity}: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
 at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3271)
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3226)
at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3204)
at android.app.ActivityThread.access$1100(ActivityThread.java:169)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1288)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
 at android.app.ActivityThread.main(ActivityThread.java:5476)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
 at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1323)
at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1341)
at android.app.BackStackRecord.commitInternal(BackStackRecord.java:597)
at android.app.BackStackRecord.commit(BackStackRecord.java:575)
at com.mixpanel.android.mpmetrics.InAppFragment.cleanUp(InAppFragment.java:221)
at com.mixpanel.android.mpmetrics.InAppFragment.onPause(InAppFragment.java:210)
at android.app.Fragment.performPause(Fragment.java:1859)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:935)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1044)
at android.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:1873)
at android.app.Activity.performPause(Activity.java:5575)
at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1239)
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3257)
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3226)
at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3204)
at android.app.ActivityThread.access$1100(ActivityThread.java:169)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1288)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
 at android.app.ActivityThread.main(ActivityThread.java:5476)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
at dalvik.system.NativeStart.main(Native Method)

**Comment by joeatwork** [comment]
Yow! This is a problem! Have you sent an in-app notification (and in particular, is that notification showing during the crash?)

Thank you so much for reporting this!

**Comment by mwelham** [comment]
Hey Joe,

Thanks for the quick response.

It's a test Mixpanel project which we're using to play with Mixpanel integration (I can send you the details in private, if it helps), and we did experiment with notifications and surveys, but I don't believe to the specific device I was working with. In fact I don't see any trace of that device in the people event stream, It's not impossible that one of my colleagues did test a general notification though. Can I check that somehow?

I got the standard "App has stopped working/responding" Android response from the device, pretty much as I was transitioning activities. From the logcat trail I grabbed the stack trace. I didn't see anything else unusual/suspicious in the log. I didn't see any notification UI, but the screen had greyed with the "stopped" message.

I overrode the onSaveInstanceState for the activity where we do the Mixpanel start/flush calls (our base activity), and hit a breakpoint in a catch for the exception, but couldn't glean any extra info.

What else can I send you to help?

Cheers
Mike

**Comment by joeatwork** [comment]
This is a big help! Whether or not you're sending inApps, the library should *absolutely* not crash your app! From the stack trace you sent, it does look like you're sending a notification, but if you never see it, well, that's a problem, too!

I'm interested in the work you're doing in onSaveInstanceState - that might give me a hint for where to check. You're also welcome to send any details you don't feel comfortable posting here to joe@mixpanel.com (that's me, I'm a maintainer of the lib) and/or support@mixpanel.com (who will be sure I see it in any case) - would you consider emailing me the code of your original onSaveInstanceState? (the one that is running during the crash?)

**Comment by mwelham** [comment]
Hey Joe,

This activity doesn't actually override onSaveInstanceState. (I did it when testing after the crash to see what I could see.)

Here's the sequence of events that causes the crash:

This activity (BaseActivity) is up and running (onCreate, onResume).
It pushes another activity in front of it.
An intent comes through, the topmost activity completes.
onResume in this activity runs again, and it then tries to push another new activity.
Kaboom! (Before the new pushed activity becomes visible)

This activity (BaseActivity) is where we call MixpanelTracker.start(this) in onCreate and MixpanelTracker.flush() in onDestroy

It may be a timing thing - I was on a breakpoint in the debugger, and after looking around, resumed execution, and it ran through fine. I grey bar at the bottom of the screen appeared very briefly with what looked like a notification, but disappeared very quickly and I didn't get a good look.

Cheers
Mike

**Comment by joeatwork** [comment]
Gotcha- it makes sense that this is a race with a fragment (and that may be why we're having a hard time reproducing it here)

**Comment by yinfeiru** [comment]
#300 will fix this issue. This patch will be available in the next release.

**Comment by OleksandrKucherenko** [comment]
v5.2.1 - crash is still there

```
java.lang.IllegalStateException: 
  at android.app.FragmentManagerImpl.checkStateLoss (FragmentManager.java:1438)
  at android.app.FragmentManagerImpl.enqueueAction (FragmentManager.java:1456)
  at android.app.BackStackRecord.commitInternal (BackStackRecord.java:707)
  at android.app.BackStackRecord.commit (BackStackRecord.java:671)
  at aue.a (InAppFragment.java:258)
  at aue.onSaveInstanceState (InAppFragment.java:240)
  at android.app.Fragment.performSaveInstanceState (Fragment.java:2514)
  at android.app.FragmentManagerImpl.saveFragmentBasicState (FragmentManager.java:1767)
  at android.app.FragmentManagerImpl.saveAllState (FragmentManager.java:1824)
  at android.app.FragmentController.saveAllState (FragmentController.java:113)
  at android.app.Activity.onSaveInstanceState (Activity.java:1574)
  at gb.onSaveInstanceState (SupportActivity.java:74)
  at fd.onSaveInstanceState (FragmentActivity.java:538)
  at kk.onSaveInstanceState (AppCompatActivity.java:509)
  at bjr.onSaveInstanceState (BaseActivity.java:227)
  at net.easypark.android.mvp.home.MainActivity.onSaveInstanceState (MainActivity.java:229)
  at android.app.Activity.performSaveInstanceState (Activity.java:1503)
  at android.app.Instrumentation.callActivityOnSaveInstanceState (Instrumentation.java:1308)
  at android.app.ActivityThread.callCallActivityOnSaveInstanceState (ActivityThread.java:4943)
  at android.app.ActivityThread.performStopActivityInner (ActivityThread.java:4231)
  at android.app.ActivityThread.handleStopActivity (ActivityThread.java:4290)
  at android.app.ActivityThread.-wrap28 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1665)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6682)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)
```

Problematic code:
```java
    private void cleanUp() {
        if (!mCleanedUp) {
            mHandler.removeCallbacks(mRemover);
            mHandler.removeCallbacks(mDisplayMini);
            UpdateDisplayState.releaseDisplayState(mDisplayStateId);

            final FragmentManager fragmentManager = mParent.getFragmentManager();
            FragmentTransaction transaction = fragmentManager.beginTransaction();
            transaction.remove(this).commit();
        }

        mCleanedUp = true;
    }
```

Cause of the problem: 
- after call of onSaveInstanceState fragment manager cannot apply any transactions

Possible solution:
- call `cleanUp` method from onPause, but do not call from `onSaveInstanceState`

Take a look into Lifecycle in Depth https://imgur.com/lUtGxVO

**Comment by OleksandrKucherenko** [comment]
and make mCleanedUp AtomicBoolean or transient
