### ISSUE TITLE
Apparent race condition in surveys - NPE when dismissing a survey after calling reset on MixpanelAPI

### ISSUE THREAD

**Issue by joeatwork** [mixpanel/mixpanel-android#211]
From a report by @badeleux

```
java.lang.RuntimeException: Unable to destroy activity {com.ultimatefanlive.ultimatefanandroid/com.mixpanel.android.surveys.SurveyActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.mixpanel.android.mpmetrics.MixpanelAPI$People.append(java.lang.String, java.lang.Object)' on a null object reference
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3706)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3724)
       at android.app.ActivityThread.access$1400(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.mixpanel.android.mpmetrics.MixpanelAPI$People.append(java.lang.String, java.lang.Object)' on a null object reference
       at com.mixpanel.android.surveys.SurveyActivity.onDestroySurvey(SurveyActivity.java:321)
       at com.mixpanel.android.surveys.SurveyActivity.onDestroy(SurveyActivity.java:305)
       at android.app.Activity.performDestroy(Activity.java:6169)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1141)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3693)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3724)
       at android.app.ActivityThread.access$1400(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by badeleux** [comment]
Not explicitly I am able to replicate the issue when I login to my app and then quickly before any survey will show up sign out., which also invokes `reset` on `MixpanelAPI`.

**Comment by joeatwork** [comment]
This is a great help, and a good clue for us! I suspect that the survey display is racing with your reset, and by the time we configure the survey there is no user to apply it to.

**Comment by kraizman** [comment]
Hello, any chance for fix? I just release new version of app with mixpanel 4.6.4 and start getting this issue. Mixpanel is now in top 10 crashes.I didn't find scenario when this crash happens but people in production fall in this issue. Between someone mention that this happen on reset of MixpanelAPI. I do not explicitly call any reset.

**Comment by mochawich** [comment]
any update on this issue?

**Comment by joeatwork** [comment]
Ping @patedit

**Comment by mochawich** [comment]
here are our Crashlytics logs

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.shoutit.app.android.local/com.shoutit.app.android.view.main.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.mixpanel.android.mpmetrics.MixpanelAPI$People.append(java.lang.String, java.lang.Object)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2464)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524)
       at android.app.ActivityThread.access$900(ActivityThread.java:154)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:5526)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void com.mixpanel.android.mpmetrics.MixpanelAPI$People.append(java.lang.String, java.lang.Object)' on a null object reference
       at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl.trackNotificationSeen(MixpanelAPI.java:1544)
       at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl$4.run(MixpanelAPI.java:1929)
       at android.app.Activity.runOnUiThread(Activity.java:5558)
       at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl.showGivenOrAvailableNotification(MixpanelAPI.java:1835)
       at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl.showNotificationIfAvailable(MixpanelAPI.java:1582)
       at com.mixpanel.android.mpmetrics.MixpanelActivityLifecycleCallbacks.onActivityStarted(MixpanelActivityLifecycleCallbacks.java:32)
       at android.app.Application.dispatchActivityStarted(Application.java:205)
       at android.app.Activity.onStart(Activity.java:1155)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:535)
       at com.trello.rxlifecycle.components.support.RxAppCompatActivity.onStart(RxAppCompatActivity.java:38)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
       at android.app.Activity.performStart(Activity.java:6302)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2427)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524)
       at android.app.ActivityThread.access$900(ActivityThread.java:154)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:5526)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by patedit** [comment]
Thanks @joeatwork @mochawich - I'm looking into it 👍

**Comment by patedit** [comment]
https://github.com/mixpanel/mixpanel-android/pull/361 will solve this issue. Thanks a lot to @ryanseams for the fix :)

**Comment by DuM4ll3** [comment]
Hi @patedit  I'm having similar error as @mochawich but in another mixpanel method
`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sample.app/com.sample.app.activities.SampleActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mixpanel.android.mpmetrics.w.a(java.lang.String, org.json.JSONObject)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2394)
       at android.app.ActivityThread.access$800(ActivityThread.java:154)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5276)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mixpanel.android.mpmetrics.w.a(java.lang.String, org.json.JSONObject)' on a null object reference
       at com.sample.app.activities.SampleActivity.**com.mixpanel.android.mpmetrics.MixpanelAPI.track**(SampleActivity.java:1541)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1239)
       at android.app.Activity.performStart(Activity.java:6057)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2394)
       at android.app.ActivityThread.access$800(ActivityThread.java:154)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5276)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)`

**Comment by alexustinovsm** [comment]
Me too

**Comment by alexustinovsm** [comment]
I got crash at onActivityResume
