### ISSUE TITLE
OutOfMemory after ~20 mins of flooding with event

### ISSUE THREAD

**Issue by ryazmin** [mixpanel/mixpanel-android#215]
Getting OutOfMemory if the app starts flooding the mix panel api with event.
Total size of event properties is ~600bytes,  track event called every 10ms.

java.lang.OutOfMemoryError
       at java.lang.String.<init>(String.java:422)
       at java.lang.String.<init>(String.java:404)
       at com.mixpanel.android.util.Base64Coder.encodeString(Base64Coder.java:44)
       at com.mixpanel.android.mpmetrics.HttpPoster.postData(HttpPoster.java:43)
       at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.sendData(AnalyticsMessages.java:310)
       at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.sendAllData(AnalyticsMessages.java:299)
       at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:269)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$1.run(AnalyticsMessages.java:187)

**Comment by joeatwork** [comment]
Wow, that is a lot of events! Thanks for reporting this!

**Comment by ryazmin** [comment]
I'm sorry, but it was a false alarm.
I double checked everything a few times and found a real root cause.

**Comment by joeatwork** [comment]
Glad to hear it! Do be aware, 600 events per second, per user of your app might end up with quite a lot of data points in the long run! You might wa
