### ISSUE TITLE
GCM InstanceID NPE in MixpanelAPI.setPushRegistrationId

### ISSUE THREAD

**Issue by eygraber** [mixpanel/mixpanel-android#227]
After [migrating to using InstanceID for GCM](https://developers.google.com/cloud-messaging/android/client) I am seeing this stacktrace in my logs:

```
06-04 21:43:21.884  18359-18359/com.isapp.dev E/MixpanelAPI.MixpanelAPI﹕ set push registration id error
    org.json.JSONException: Unterminated array at character 13 of [***********:...]
            at org.json.JSONTokener.syntaxError(JSONTokener.java:450)
            at org.json.JSONTokener.readArray(JSONTokener.java:440)
            at org.json.JSONTokener.nextValue(JSONTokener.java:103)
            at org.json.JSONArray.<init>(JSONArray.java:92)
            at org.json.JSONArray.<init>(JSONArray.java:108)
            at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl.setPushRegistrationId(MixpanelAPI.java:1368)
```

I believe this is because the InstanceID token has an unescaped colon (':').

**Comment by eygraber** [comment]
I see that there is a fix for this https://github.com/mixpanel/mixpanel-android/commit/e851e0077cd1b87a795fad5f8c7fd621985dc6e5
