### ISSUE TITLE
android.content.res.Resources$NotFoundException: File res/drawable-xxhdpi-v4/com_mixpanel_android_ic_bell.png

### ISSUE THREAD

**Issue by dbachelder** [mixpanel/mixpanel-android#243]
Frequent exception in production

So far it is 100% Samsung devices running android 4.4.4

```
android.content.res.Resources$NotFoundException: File res/drawable-xxhdpi-v4/com_mixpanel_android_ic_bell.png from drawable resource ID #0x7f02006b
       at android.content.res.Resources$CRunnable_openmp.doOpenMP(Resources.java:1097)
       at android.content.res.Resources$__ompClass0.__doWork(Resources.java:1029)
       at com.samsung.javaomp.runtime.__OMPThread.run()
Caused by: java.io.FileNotFoundException: res/drawable-xxhdpi-v4/com_mixpanel_android_ic_bell.png
       at android.content.res.AssetManager.openNonAssetNative(AssetManager.java)
       at android.content.res.AssetManager.openNonAsset(AssetManager.java:408)
       at android.content.res.Resources$CRunnable_openmp.doOpenMP(Resources.java:1092)
       at android.content.res.Resources$__ompClass0.__doWork(Resources.java:1029)
       at com.samsung.javaomp.runtime.__OMPThread.run()
```

**Comment by dbachelder** [comment]
this is on version 4.6.2 of the library.

on version 4.5.3 a very similar exception was occuring frequently on samsung 4.4.4 devices:

```
android.content.res.Resources$NotFoundException: File res/drawable-xxhdpi-v4/com_mixpanel_android_ic_coin.png from drawable resource ID #0x7f020070
       at android.content.res.Resources$CRunnable_openmp.doOpenMP(Resources.java:1097)
       at android.content.res.Resources$__ompClass0.__doWork(Resources.java:1029)
       at com.samsung.javaomp.runtime.__OMPThread.run()
Caused by: java.io.FileNotFoundException: res/drawable-xxhdpi-v4/com_mixpanel_android_ic_coin.png
       at android.content.res.AssetManager.openNonAssetNative(AssetManager.java)
       at android.content.res.AssetManager.openNonAsset(AssetManager.java:408)
       at android.content.res.Resources$CRunnable_openmp.doOpenMP(Resources.java:1092)
       at android.content.res.Resources$__ompClass0.__doWork(Resources.java:1029)
       at com.samsung.javaomp.runtime.__OMPThread.run()
```

**Comment by dbachelder** [comment]
The only threads with MP code in them at crash time are these:

```
com.mixpanel.android.AnalyticsWorker thread
       at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:972)
       at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
       at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
       at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1593)
       at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1463)
       at com.mixpanel.android.mpmetrics.MPDbAdapter.addJSON(MPDbAdapter.java:155)
       at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:242)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

and:

```
om.mixpanel.android.viewcrawler.ViewCrawler thread
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:138)
       at android.os.Looper.loop(Looper.java:131)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

Why is there a "viewcrawler" thread? We are not using the codeless event tracking stuff...

**Comment by dbachelder** [comment]
Additional info..

proguard rules: 
```
-keep class     com.mixpanel.** { *; }
-keep interface com.mixpanel.** { *; }
```

and we are including the `aar` as our dependency.

The first occurrence of this crash was on 7/18 but it started getting prevalent on 7/22 / 7/23 with the 4.5.3 version of the library even though we had been using it since 4/3

**Comment by justincpollard** [comment]
A little update here: we updated some of your dependencies (encapsulated in pull request #247) and removed all unused drawable resources in our fork of this repo (https://github.com/mixpanel/mixpanel-android), then released a version of our app pointed to that fork. So far, with pretty significant usage, we haven't seen any of these crashes on that version of our app.

**Comment by dbachelder** [comment]
Looks like this is related to this: https://code.google.com/p/android/issues/detail?id=79325

**Comment by yinfeiru** [comment]
Thanks for the info guys! I'll look into this in the next few days!

**Comment by yinfeiru** [comment]
@dbachelder Thanks for the link! It's extremely helpful!

@justincpollard Thanks for the PR. I'll take a look and talk to you there!
