### ISSUE TITLE
NPE when trying to display take-over in-app message

### ISSUE THREAD

**Issue by carlospaulino** [mixpanel/mixpanel-android#257]
When trying to manually display a take-over in-app notification, I get a NPE.

    mixpanelAPI.getPeople().showNotificationIfAvailable(theActivity);

The problem is in the following line

    getPeople().withIdentity(getDistinctId())

in com.mixpanel.android.mpmetrics.MixpanelApi.PeopleImpl#trackNotificationSeen(InAppNotification)

See stack trace:

    java.lang.RuntimeException: Unable to start activity ComponentInfo{**REDACTED**}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.mixpanel.android.mpmetrics.MixpanelAPI$People.append(java.lang.String, java.lang.Object)' on a null object reference
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.mixpanel.android.mpmetrics.MixpanelAPI$People.append(java.lang.String, java.lang.Object)' on a null object reference
            at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl.trackNotificationSeen(MixpanelAPI.java:1536)
            at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl$4.run(MixpanelAPI.java:1913)
            at android.app.Activity.runOnUiThread(Activity.java:5293)
            at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl.showGivenOrAvailableNotification(MixpanelAPI.java:1829)
            at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl.showNotificationIfAvailable(MixpanelAPI.java:1574)
            at **redacted**

FYI:
*AutoShowMixpanelUpdates is false in the manifest
*SurveyActivity is declared in the manifest

**Comment by bsmith42** [comment]
This was closed but no comment on how it was addressed.  I have auto set to true and this started happening after upgrading to 4.6.4.  Seems like some additional checks need to be made to avoid this.
```
Caused by: java.lang.NullPointerException
	at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl.trackNotificationSeen(MixpanelAPI.java:1536)
	at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl$4.run(MixpanelAPI.java:1913)
	at android.app.Activity.runOnUiThread(Activity.java:4843)
	at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl.showGivenOrAvailableNotification(MixpanelAPI.java:1829)
	at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl.showNotificationIfAvailable(MixpanelAPI.java:1574)
	at com.mixpanel.android.mpmetrics.MixpanelActivityLifecycleCallbacks.onActivityStarted(MixpanelActivityLifecycleCallbacks.java:21)
	at android.app.Application.dispatchActivityStarted(Application.java:186)
	at android.app.Activity.onStart(Activity.java:1080)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:499)
```

**Comment by HozakaN** [comment]
Any news on that one? I'm getting this :s

**Comment by ryanseams** [comment]
Looks like this issue was closed by the user, but there is an equivalent open issue in https://github.com/mixpanel/mixpanel-android/issues/211. This problem will be resolved by https://github.com/mixpanel/mixpanel-android/pull/361 in the next version of the SDK.
