### ISSUE TITLE
Unable to start receiver com.mixpanel.android.mpmetrics.InstallReferrerReceiver

### ISSUE THREAD

**Issue by sudam-chavan** [mixpanel/mixpanel-android#262]
Stacktrace:

java.lang.RuntimeException: Unable to start receiver com.mixpanel.android.mpmetrics.InstallReferrerReceiver: java.lang.IllegalArgumentException: Invalid % sequence %+o at 28
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2258)
       at android.app.ActivityThread.access$1500(ActivityThread.java:134)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1297)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:4624)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:809)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.IllegalArgumentException: Invalid % sequence %+o at 28
       at libcore.net.UriCodec.decode(UriCodec.java:165)
       at java.net.URLDecoder.decode(URLDecoder.java:67)
       at com.mixpanel.android.mpmetrics.InstallReferrerReceiver.find(InstallReferrerReceiver.java:106)
       at com.mixpanel.android.mpmetrics.InstallReferrerReceiver.onReceive(InstallReferrerReceiver.java:93)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2251)
       at android.app.ActivityThread.access$1500(ActivityThread.java:134)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1297)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:4624)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:809)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by yinfeiru** [comment]
@sudam-chavan Sorry for the late. Are you still seeing this issue? Have you tried the latest lib we have? Please re-open if you still have this problem! 

Again, sorry for the late response!
