### ISSUE TITLE
Android Mixpanel exception in application opening

### ISSUE THREAD

**Issue by epool** [mixpanel/mixpanel-android#263]
I am getting the following exception in some cases, not always. This happen when my application is opened, this is very rarely and my application crashes, I need help to know why this could be happening. In advance thanks!

    09-14 08:27:26.466  12986-13051/com.app.kuona E/CursorWindow﹕ Failed to read row 0, column 0 from a CursorWindow which has 0 rows, 3 columns.
    09-14 08:27:26.499  12986-13051/com.app.kuona E/MixpanelAPI.Messages﹕ Worker threw an unhandled exception
    java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
            at android.database.CursorWindow.nativeGetLong(Native Method)
            at android.database.CursorWindow.getLong(CursorWindow.java:511)
            at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
            at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
            at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
            at com.mixpanel.android.mpmetrics.MPDbAdapter.generateDataString(MPDbAdapter.java:254)
            at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.sendData(AnalyticsMessages.java:405)
            at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.sendAllData(AnalyticsMessages.java:393)
            at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:268)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
    09-14 08:27:26.500  12986-13051/com.app.kuona E/MixpanelAPI.Messages﹕ Mixpanel will not process any more analytics messages
    java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
            at android.database.CursorWindow.nativeGetLong(Native Method)
            at android.database.CursorWindow.getLong(CursorWindow.java:511)
            at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
            at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
            at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
            at com.mixpanel.android.mpmetrics.MPDbAdapter.generateDataString(MPDbAdapter.java:254)
            at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.sendData(AnalyticsMessages.java:405)
            at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.sendAllData(AnalyticsMessages.java:393)
            at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:268)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
    09-14 08:27:26.577  12986-12998/com.app.kuona A/libc﹕ Fatal signal 11 (SIGSEGV), code 2, fault addr 0xa2a90a20 in tid 12998 (FinalizerDaemon)

**Comment by yinfeiru** [comment]
Thanks for writing in!!

What I'm really curious about is `CursorWindow`. I don't think it's part of our library and looks like it's related to your database.
From the log `Failed to read row 0, column 0 from a CursorWindow which has 0 rows, 3 columns.`, I guess the problem is that you are accessing a row which doesn't exist. And then Mixpanel gets mad as it can't access it.

Please let me know your thoughts and how it goes!!

**Comment by epool** [comment]
The `android.database.CursorWindow` class appears to be from Android. The log from mixpanel did not crash my application. Finally I fond the reason of my `Fatal signal 11 (SIGSEGV)`, this was caused by serialize `android.location.Location` with [Gson](https://github.com/google/gson) and on deserialize this was causing the error in some cases.
