### ISSUE TITLE
Issue when running on local machine

### ISSUE THREAD

**Issue by chandrasc** [mixpanel/mixpanel-android#265]
In the development environment, running the app in emulator crashes due to the below error:

6303-6320/com.areuin.uin E/MixpanelAPI.ViewCrawler﹕ Error parsing URI wss://switchboard.mixpanel.com/connect/XXX for editor websocket
    java.net.URISyntaxException: Illegal character in path at index 39: wss://switchboard.mixpanel.com/connect/"123"
            at libcore.net.UriCodec.validate(UriCodec.java:63)
            at java.net.URI.parseURI(URI.java:402)
            at java.net.URI.<init>(URI.java:204)
            at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.connectToEditor(ViewCrawler.java:452)
            at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleMessage(ViewCrawler.java:296)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by yinfeiru** [comment]
Thanks for writing in!

Can you please provide me more details? Is it crushing in the same way on a real device? Are you sure your emulator has internet connection? What was the device you were emulating? What's the lib version?

**Comment by yinfeiru** [comment]
Closing. Please re-open if you still have this issue.
