### ISSUE TITLE
Unable to get Acceptance tests to pass

### ISSUE THREAD

**Issue by yogurtearl** [mixpanel/mixpanel-android#274]
I am not able to get the selendroid tests to pass. I am getting this error:

( On Genymotion API 23 )

```======================================================================
FAIL: test_layout_absent_views (__main__.AndroidTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_layout.py", line 63, in test_layout_absent_views
    self.assertEquals(self.driver.find_element_by_id('edit_email_address').location['y'], self.driver.find_element_by_id('edit_first_name').location['y'])
AssertionError: 381 != 129

======================================================================
FAIL: test_layout_change_basic (__main__.AndroidTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_layout.py", line 28, in test_layout_change_basic
    self.assertTrue(send_to_mixpanel_location['y'] < edit_email_address_location['y'])
AssertionError: False is not true

======================================================================
FAIL: test_layout_massive_changes (__main__.AndroidTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_layout.py", line 51, in test_layout_massive_changes
    self.assertEquals(send_to_mixpanel_location['y'], edit_first_name_location['y'])
AssertionError: 507 != 129

----------------------------------------------------------------------
Ran 4 tests in 10.131s

FAILED (failures=3)

```

**Comment by yinfeiru** [comment]
It's you again and, as always, thanks for writing in.
This acceptance test, as you can tell, is just a prototype I wrote long long time ago and hasn't been updated since then. The tests above are for layout A/B, which is not officially supported as yet. I'll definitely re-visit this test once I get a chance. You can simply ignore them for now.

**Comment by yinfeiru** [comment]
I've updated the acceptance test. Thanks again for pointing this out!
#306
