### ISSUE TITLE
FadingImageView - ClassCastException

### ISSUE THREAD

**Issue by jiri-hlt** [mixpanel/mixpanel-android#286]
Fatal Exception: java.lang.ClassCastException: android.widget.RelativeLayout cannot be cast to android.widget.LinearLayout
       at com.mixpanel.android.surveys.FadingImageView.onMeasure(FadingImageView.java:46)
       at android.view.View.measure(View.java:17624)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
       at android.view.View.measure(View.java:17624)

**Comment by jiri-hlt** [comment]
com.mixpanel.android.surveys.FadingImageView.onMeasure(FadingImageView.java:46)
should just be casted to ViewGroup:
```
ViewGroup container = (ViewGroup) getParent();
```

**Comment by pavel-kurnosov** [comment]
When this will be released? I got a lot of issues on Crashlytics with same issue...

**Comment by yinfeiru** [comment]
Closing this as it's been fixed in #288

**Comment by yinfeiru** [comment]
@pavel-kurnosov a new release will probably be available in a week.
