### ISSUE TITLE
Handle SSL Timeout Exceptions

### ISSUE THREAD

**Issue by martyglaubitz** [mixpanel/mixpanel-android#297]
We're getting a lot of weird Exceptions in our live app

    Fatal Exception: java.util.concurrent.TimeoutException: com.android.org.conscrypt.OpenSSLDigestContext.finalize() timed out after 10 seconds
       at com.android.org.conscrypt.NativeCrypto.EVP_MD_CTX_destroy(NativeCrypto.java)
       at com.android.org.conscrypt.OpenSSLDigestContext.finalize(OpenSSLDigestContext.java:27)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:190)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:173)
       at java.lang.Thread.run(Thread.java:818)

And we only see one reasonable source of the Exception:

    com.mixpanel.android.viewcrawler.ViewCrawler
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:143)
       at android.os.Looper.loop(Looper.java:130)
       at android.os.HandlerThread.run(HandlerThread.java:61)

Unfortunatly fabric doesn't show us any linenumbers :/
I hope you can work with that

**Comment by martyglaubitz** [comment]
turns out the problem seems to originate from somewhere else...
