### ISSUE TITLE
Crash in ViewCrawler with Mixpanel 4.7.0 and StrictMode

### ISSUE THREAD

**Issue by jdauphant** [mixpanel/mixpanel-android#320]
Hello,

I have crash on the class com.mixpanel.android.viewcrawler.ViewCrawler .

It look's like have different behavior with different device : 
- Sony Xperia Z3 with android 5.1 don't crash 
- it crash on a yotaphone with Android 5.0
- it didn't crash on a Samsung S2 on Android 4.2

The stack : 
```
E/StrictMode: null
          android.app.IntentReceiverLeaked: Activity my.package.ui.LocationActivity has leaked IntentReceiver android.hardware.SystemSensorManager$1@3e827e66 that was originally registered here. Are you missing a call to unregisterReceiver()?
          at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:898)
          at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:699)
          at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1638)
          at android.app.ContextImpl.registerReceiver(ContextImpl.java:1618)
          at android.app.ContextImpl.registerReceiver(ContextImpl.java:1612)
          at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:488)
          at android.hardware.SystemSensorManager.<init>(SystemSensorManager.java:81)
          at android.app.ContextImpl$31.createService(ContextImpl.java:539)
          at android.app.ContextImpl$ServiceFetcher.getService(ContextImpl.java:297)
          at android.app.ContextImpl.getSystemService(ContextImpl.java:1833)
          at android.view.ContextThemeWrapper.getSystemService(ContextThemeWrapper.java:113)
          at android.app.Activity.getSystemService(Activity.java:5067)
          at com.mixpanel.android.viewcrawler.ViewCrawler$LifecycleCallbacks.installConnectionSensor(ViewCrawler.java:208)
          at com.mixpanel.android.viewcrawler.ViewCrawler$LifecycleCallbacks.onActivityResumed(ViewCrawler.java:180)
          at android.app.Application.dispatchActivityResumed(Application.java:208)
          at android.app.Activity.onResume(Activity.java:1259)
          at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:438)
          at my.package.BuildTypeActivity.onResume(BuildTypeActivity.kt:36)
          at my.package.BaseActivity.onResume(BaseActivity.kt:31)
          at my.package.ui.LocationActivity.onResume(DetailActivity.kt:641)
          at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1241)
          at android.app.Activity.performResume(Activity.java:6087)
          at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2965)
          at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3007)
          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2363)
          at android.app.ActivityThread.access$800(ActivityThread.java:144)
          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
          at android.os.Handler.dispatchMessage(Handler.java:102)
          at android.os.Looper.loop(Looper.java:135)
          at android.app.ActivityThread.main(ActivityThread.java:5246)
          at java.lang.reflect.Method.invoke(Native Method)
          at java.lang.reflect.Method.invoke(Method.java:372)
          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```
Mixpanel version: 4.7.0.

FYI: We don't use sensors in our app.

Best regards,
Julien

**Comment by patedit** [comment]
@jdauphant Thanks a lot for pointing this out! We are using the `Activity` context and it seems that Android keeps an strong reference in this case. I believe this issue was solved on Android 5.1 and they do not retain the object anymore - that is why it's working fine on your Sony.

I'm going to create a PR now fixing this issue :) Thanks again @jdauphant

**Comment by yinfeiru** [comment]
@jdauphant this fix will be available in the next release which is coming soon

**Comment by jdauphant** [comment]
Thanks

**Comment by jdauphant** [comment]
@yinfeiru 
Do you have a beta version with the fix we can use ?

**Comment by patedit** [comment]
@jdauphant You could pull from master if you want. Otherwise, we are making a new release today/tomorrow.

**Comment by patedit** [comment]
@jdauphant We released a new version yesterday with this fix!

**Comment by jdauphant** [comment]
@patedit Thanks but I have the same issue in 4.8.0.
I have solved the problem by setting "com.mixpanel.android.MPConfig.DisableGestureBindingUI" to true
