### ISSUE TITLE
FatalException

### ISSUE THREAD

**Issue by iauglov** [mixpanel/mixpanel-android#327]
We have some problems with notification.
Fatal Exception: java.lang.ClassCastException: android.widget.RelativeLayout cannot be cast to android.widget.LinearLayout
       at com.mixpanel.android.surveys.FadingImageView.onMeasure(FadingImageView.java:46)
       at android.view.View.measure(View.java:17496)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
       at android.view.View.measure(View.java:17496)
       at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1265)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:617)
       at android.view.View.measure(View.java:17496)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
       at android.view.View.measure(View.java:17496)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5464)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
       at android.view.View.measure(View.java:17496)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5464)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1438)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:724)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:615)
       at android.view.View.measure(View.java:17496)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5464)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2636)
       at android.view.View.measure(View.java:17496)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2031)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1193)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1400)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1078)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5875)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
       at android.view.Choreographer.doFrame(Choreographer.java:550)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5297)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by ryanseams** [comment]
Hi @iauglov ! It sounds like you are seeing the same crash as https://github.com/mixpanel/mixpanel-android/issues/286, which should be resolved in the newest release of the library. 

Can you try updating to version 4.8.0 and letting us know if this crash persists?

**Comment by iauglov** [comment]
Thanks, we try update if problem continue we reopen this issue
