### ISSUE TITLE
Leak on ImageStore on Android 5.0 (version 4.8.0)

### ISSUE THREAD

**Issue by jdauphant** [mixpanel/mixpanel-android#329]
I have bug with StrictMode on Android 5.0 (Yotaphone), I have this leak : 
```
/StrictMode: StrictMode policy violation; ~duration=36 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=95 violation=2
                                                                at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1137)
                                                                at libcore.io.BlockGuardOs.access(BlockGuardOs.java:67)
                                                                at java.io.File.doAccess(File.java:283)
                                                                at java.io.File.exists(File.java:363)
                                                                at android.app.ContextImpl.getDir(ContextImpl.java:2189)
                                                                at android.content.ContextWrapper.getDir(ContextWrapper.java:256)
                                                                at com.mixpanel.android.util.ImageStore.<init>(ImageStore.java:41)
                                                                at com.mixpanel.android.util.ImageStore.<init>(ImageStore.java:37)
                                                                at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.<init>(ViewCrawler.java:268)
                                                                at com.mixpanel.android.viewcrawler.ViewCrawler.<init>(ViewCrawler.java:76)
                                                                at com.mixpanel.android.mpmetrics.MixpanelAPI.constructUpdatesFromMixpanel(MixpanelAPI.java:1341)
                                                                at com.mixpanel.android.mpmetrics.MixpanelAPI.<init>(MixpanelAPI.java:227)
                                                                at com.mixpanel.android.mpmetrics.MixpanelAPI.<init>(MixpanelAPI.java:196)
                                                                at com.mixpanel.android.mpmetrics.MixpanelAPI.getInstance(MixpanelAPI.java:300)
                                                                at myApp.Analytics.init(Analytics.kt:14)
                                                                at myApp.onCreate(MyApplication.kt:37)
                                                                at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
                                                                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4543)
                                                                at android.app.ActivityThread.access$1500(ActivityThread.java:144)
                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                at android.os.Looper.loop(Looper.java:135)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5246)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

If I add the setting "com.mixpanel.android.MPConfig.DisableViewCrawler"="true"
```
StrictMode: StrictMode policy violation; ~duration=39 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=95 violation=2
                                                                at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1137)
                                                                at libcore.io.BlockGuardOs.access(BlockGuardOs.java:67)
                                                                at java.io.File.doAccess(File.java:283)
                                                                at java.io.File.exists(File.java:363)
                                                                at android.app.ContextImpl.getDir(ContextImpl.java:2189)
                                                                at android.content.ContextWrapper.getDir(ContextWrapper.java:256)
                                                                at com.mixpanel.android.util.ImageStore.<init>(ImageStore.java:41)
                                                                at com.mixpanel.android.util.ImageStore.<init>(ImageStore.java:37)
                                                                at com.mixpanel.android.mpmetrics.DecideChecker.createImageStore(DecideChecker.java:57)
                                                                at com.mixpanel.android.mpmetrics.DecideChecker.<init>(DecideChecker.java:53)
                                                                at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.createDecideChecker(AnalyticsMessages.java:227)
                                                                at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.<init>(AnalyticsMessages.java:220)
                                                                at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker.restartWorkerThread(AnalyticsMessages.java:212)
                                                                at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker.<init>(AnalyticsMessages.java:187)
                                                                at com.mixpanel.android.mpmetrics.AnalyticsMessages.createWorker(AnalyticsMessages.java:52)
                                                                at com.mixpanel.android.mpmetrics.AnalyticsMessages.<init>(AnalyticsMessages.java:47)
                                                                at com.mixpanel.android.mpmetrics.AnalyticsMessages.getInstance(AnalyticsMessages.java:67)
                                                                at com.mixpanel.android.mpmetrics.MixpanelAPI.getAnalyticsMessages(MixpanelAPI.java:1301)
                                                                at com.mixpanel.android.mpmetrics.MixpanelAPI.<init>(MixpanelAPI.java:240)
                                                                at com.mixpanel.android.mpmetrics.MixpanelAPI.<init>(MixpanelAPI.java:196)
                                                                at com.mixpanel.android.mpmetrics.MixpanelAPI.getInstance(MixpanelAPI.java:300)
                                                                at myApp.Analytics.init(Analytics.kt:14)
                                                                at myApp.MyApplication.onCreate(MyApplication.kt:37)
                                                                at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
                                                                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4543)
                                                                at android.app.ActivityThread.access$1500(ActivityThread.java:144)
                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                at android.os.Looper.loop(Looper.java:135)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5246)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

I have create a separate issue as #320 , made it could be qualified at same bug.

Thanks for your answer

**Comment by yinfeiru** [comment]
@jdauphant Thanks for reporting this!!
I found this post on stackoverflow http://stackoverflow.com/questions/13323431/strictmodediskreadviolation-when

I've tried to do `context.getDir` in a runnable and it does eliminate this warning. However, I don't think it's necessary do this in a separate thread as I don't think `getDir` will ever take that much time to finish.

Please let me know your thoughts as you might have a better understanding.

**Comment by jdauphant** [comment]
Thanks, apparently it's working !
