### ISSUE TITLE
NPE in MixpanelActivityLifecycleCallbacks when activity is started

### ISSUE THREAD

**Issue by martyglaubitz** [mixpanel/mixpanel-android#352]
Mixpanel SDK used: 4.8.5

```
Android: 5.1.1
Manufacturer: samsung
Model: SM-J110M
Thread: main-1
Date: Sun Apr 24 00:31:24 BRT 2016

java.lang.RuntimeException: Unable to start activity ComponentInfo{our.app/our.app.HomeActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.mixpanel.android.mpmetrics.ao.a(java.lang.String, java.lang.Object)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2697)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2771)
	at android.app.ActivityThread.access$900(ActivityThread.java:177)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1432)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5912)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.mixpanel.android.mpmetrics.ao.a(java.lang.String, java.lang.Object)' on a null object reference
	at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl$4.com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl.trackNotificationSeen(MixpanelAPI.java:5546)
                                                            run
	at android.app.Activity.runOnUiThread(Activity.java:5481)
	at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl.showGivenOrAvailableNotification(MixpanelAPI.java:4839)
                                                          showNotificationIfAvailable
	at com.mixpanel.android.mpmetrics.MixpanelActivityLifecycleCallbacks.onActivityStarted(MixpanelActivityLifecycleCallbacks.java:21)
	at android.app.Application.dispatchActivityStarted(Application.java:223)
	at android.app.Activity.onStart(Activity.java:1241)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:590)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
	at android.app.Activity.performStart(Activity.java:6213)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2660)
	... 10 more
```

**Comment by patedit** [comment]
Seems is the same issue as https://github.com/mixpanel/mixpanel-android/issues/211 :)
