### ISSUE TITLE
android.content.res.Resources$NotFoundException: File res/drawable/title_bar.xml from drawable resource ID #0x1080095

### ISSUE THREAD

**Issue by luiges90** [mixpanel/mixpanel-android#382]
Our error reporting system recently spewing this crash. However our `LaunchActivity` has no layout at all.

So far all crashes exclusively come from Xiaomi phones (across all android versions)

We have looked into https://github.com/mixpanel/mixpanel-android/issues/243 this issue but that concerns about resource shrinking (which PNGs got thrown away) that happen on Samsung phones. Samsung phones do not have this issue.

Library version: 4.6.4

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.example/com.example.LaunchActivity}: android.view.InflateException: Binary XML file line #32: Binary XML file line #32: Error inflating class <unknown>
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3110)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3141)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2488)
       at android.app.ActivityThread.access$900(ActivityThread.java:153)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5442)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
Caused by android.view.InflateException: Binary XML file line #32: Binary XML file line #32: Error inflating class <unknown>
       at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:3909)
       at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:3981)
       at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:1969)
       at com.mixpanel.android.viewcrawler.EditState.applyIntendedEdits(EditState.java:98)
       at com.mixpanel.android.viewcrawler.EditState.applyEditsOnUiThread(EditState.java:83)
       at com.mixpanel.android.viewcrawler.EditState.add(EditState.java:37)
       at com.mixpanel.android.viewcrawler.ViewCrawler$LifecycleCallbacks.onActivityResumed(ViewCrawler.java:181)
       at android.app.Application.dispatchActivityResumed(Application.java:218)
       at android.app.Activity.onResume(Activity.java:1220)
       at com.example.LaunchActivity.onResume(LaunchActivity.java:277)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
       at android.app.Activity.performResume(Activity.java:6379)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3099)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3141)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2488)
       at android.app.ActivityThread.access$900(ActivityThread.java:153)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5442)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
Caused by android.view.InflateException: Binary XML file line #32: Error inflating class <unknown>
       at android.view.LayoutInflater.createView(LayoutInflater.java:649)
       at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:698)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:766)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:839)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:3909)
       at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:3981)
       at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:1969)
       at com.mixpanel.android.viewcrawler.EditState.applyIntendedEdits(EditState.java:98)
       at com.mixpanel.android.viewcrawler.EditState.applyEditsOnUiThread(EditState.java:83)
       at com.mixpanel.android.viewcrawler.EditState.add(EditState.java:37)
       at com.mixpanel.android.viewcrawler.ViewCrawler$LifecycleCallbacks.onActivityResumed(ViewCrawler.java:181)
       at android.app.Application.dispatchActivityResumed(Application.java:218)
       at android.app.Activity.onResume(Activity.java:1220)
       at com.example.LaunchActivity.onResume(LaunchActivity.java:277)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
       at android.app.Activity.performResume(Activity.java:6379)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3099)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3141)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2488)
       at android.app.ActivityThread.access$900(ActivityThread.java:153)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5442)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at android.view.LayoutInflater.createView(LayoutInflater.java:623)
       at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:698)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:766)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:839)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:3909)
       at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:3981)
       at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:1969)
       at com.mixpanel.android.viewcrawler.EditState.applyIntendedEdits(EditState.java:98)
       at com.mixpanel.android.viewcrawler.EditState.applyEditsOnUiThread(EditState.java:83)
       at com.mixpanel.android.viewcrawler.EditState.add(EditState.java:37)
       at com.mixpanel.android.viewcrawler.ViewCrawler$LifecycleCallbacks.onActivityResumed(ViewCrawler.java:181)
       at android.app.Application.dispatchActivityResumed(Application.java:218)
       at android.app.Activity.onResume(Activity.java:1220)
       at com.example.LaunchActivity.onResume(LaunchActivity.java:277)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
       at android.app.Activity.performResume(Activity.java:6379)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3099)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3141)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2488)
       at android.app.ActivityThread.access$900(ActivityThread.java:153)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5442)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
Caused by android.content.res.Resources$NotFoundException: File res/drawable/title_bar.xml from drawable resource ID #0x1080095
       at android.content.res.Resources.loadDrawableForCookie(Resources.java:2690)
       at android.content.res.Resources.loadDrawable(Resources.java:2580)
       at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:387)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:872)
       at android.view.View.(View.java)
       at android.view.ViewGroup.(ViewGroup.java)
       at android.widget.FrameLayout.(FrameLayout.java)
       at android.widget.FrameLayout.(FrameLayout.java)
       at android.widget.FrameLayout.(FrameLayout.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at android.view.LayoutInflater.createView(LayoutInflater.java:623)
       at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:698)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:766)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:839)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:3909)
       at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:3981)
       at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:1969)
       at com.mixpanel.android.viewcrawler.EditState.applyIntendedEdits(EditState.java:98)
       at com.mixpanel.android.viewcrawler.EditState.applyEditsOnUiThread(EditState.java:83)
       at com.mixpanel.android.viewcrawler.EditState.add(EditState.java:37)
       at com.mixpanel.android.viewcrawler.ViewCrawler$LifecycleCallbacks.onActivityResumed(ViewCrawler.java:181)
       at android.app.Application.dispatchActivityResumed(Application.java:218)
       at android.app.Activity.onResume(Activity.java:1220)
       at com.example.LaunchActivity.onResume(LaunchActivity.java:277)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
       at android.app.Activity.performResume(Activity.java:6379)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3099)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3141)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2488)
       at android.app.ActivityThread.access$900(ActivityThread.java:153)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5442)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
Caused by org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: <nine-patch> requires a valid 9-patch source image
       at android.graphics.drawable.NinePatchDrawable.updateStateFromTypedArray(NinePatchDrawable.java:459)
       at android.graphics.drawable.NinePatchDrawable.inflate(NinePatchDrawable.java:413)
       at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1217)
       at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1126)
       at android.content.res.Resources.createFromXml(Resources.java:2964)
       at android.content.res.Resources.loadDrawableForCookie(Resources.java:2676)
       at android.content.res.Resources.loadDrawable(Resources.java:2580)
       at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:387)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:872)
       at android.view.View.(View.java)
       at android.view.ViewGroup.(ViewGroup.java)
       at android.widget.FrameLayout.(FrameLayout.java)
       at android.widget.FrameLayout.(FrameLayout.java)
       at android.widget.FrameLayout.(FrameLayout.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at android.view.LayoutInflater.createView(LayoutInflater.java:623)
       at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:698)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:766)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:839)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:3909)
       at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:3981)
       at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:1969)
       at com.mixpanel.android.viewcrawler.EditState.applyIntendedEdits(EditState.java:98)
       at com.mixpanel.android.viewcrawler.EditState.applyEditsOnUiThread(EditState.java:83)
       at com.mixpanel.android.viewcrawler.EditState.add(EditState.java:37)
       at com.mixpanel.android.viewcrawler.ViewCrawler$LifecycleCallbacks.onActivityResumed(ViewCrawler.java:181)
       at android.app.Application.dispatchActivityResumed(Application.java:218)
       at android.app.Activity.onResume(Activity.java:1220)
       at com.example.LaunchActivity.onResume(LaunchActivity.java:277)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
       at android.app.Activity.performResume(Activity.java:6379)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3099)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3141)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2488)
       at android.app.ActivityThread.access$900(ActivityThread.java:153)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5442)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
```

**Comment by patedit** [comment]
@luiges90 Seems there are some people complaining about it on Xiaomi as well (http://bbs.xiaomi.cn/t-3080220). Do you use codeless events and/or AB test? If you don't, you could disable the `ViewCrawler` and that crash won't happen. To do that, you need to add this to your AndroidManifest.xml file:

```
<meta-data
            android:name="com.mixpanel.android.MPConfig.DisableViewCrawler"
            android:value="true"/>
```

Alternatively, if you don't have a layout on `LaunchActivity` you don't need to have that activity as part of the "possible activities that we could apply ab test on". Is `LaunchActivity` your launcher activity and is not part of the activity history? If that is the case, you'd need to make sure your Mixpanel instance is created after `LaunchActivity.onResume()`. How are you creating your Mixpanel instance? If you could walk me through a bit about what `LaunchActivity` does and how you are initializing Mixpanel i could help you avoiding that crash without having to disable the `ViewCrawler`. Thanks for reaching out!

**Comment by luiges90** [comment]
We are disabling `ViewCrawler` (we don't use AB test/codeless events) and the crash stopped at the moment.

**Comment by patedit** [comment]
Awesome, if you need to enable AB test or codeless events we can also work around that bug as I pointed out above. Thanks for using Mixpanel!
