### ISSUE TITLE
Crash when implementing notification

### ISSUE THREAD

**Issue by ywj7931** [mixpanel/mixpanel-android#396]
Platform:       Android 6.0.1
build setting: minSdkVersion 19
```
compile 'com.google.android.gms:play-services-base:8.3.0'
compile 'com.google.android.gms:play-services-gcm:8.3.0'
compile "com.mixpanel.android:mixpanel-android:4.+"
```
I used the following to initialize pushing notification:
 mMixpanel = MixpanelAPI.getInstance(this,MIXPANEL_TOKEN );
        mMixpanel.getPeople().identify(id);
        mMixpanel.getPeople().set("ID", id);
        mMixpanel.getPeople().initPushHandling("my google project id");

But I have error:
```
FATAL EXCEPTION: com.mixpanel.android.AnalyticsWorker
 Process: ueye.com.fragmenttest, PID: 31876
java.lang.IncompatibleClassChangeError: The method 'java.io.File android.support.v4.content.ContextCompat.getNoBackupFilesDir(android.content.Context)' was expected to be of type virtual but instead was found to be of type direct (declaration of 'com.google.android.gms.iid.zzd' appears in /data/data/ueye.com.fragmenttest/files/instant-run/dex/slice-com.google.android.gms-play-services-gcm-8.3.0_d397001c904b476dcb0f394a3cc5afb8c87c645f-classes.dex)
 at com.google.android.gms.iid.zzd.zzdL(Unknown Source)
 at com.google.android.gms.iid.zzd.<init>(Unknown Source)
 at com.google.android.gms.iid.zzd.<init>(Unknown Source)
 at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
 at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
 at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.runGCMRegistration(AnalyticsMessages.java:358)
 at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:282)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:148)
 at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by patedit** [comment]
Hello @ywj7931! Thanks for writing. 

Could you paste your entire dependencies? It seems that you may be using an incompatible appcompact version with Google Play Services. Also, I believe that issue was solved on the latest google play services (v9.0.1). Have you tried updating your google play services dependency?

**Comment by ywj7931** [comment]
@patedit Thanks for replying, Im still sticking on 8.3, because when I moved to higher version, it told me some are replying on 8.3,
```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.1.1'
    compile 'com.google.android.gms:play-services-base:8.3.0'
    compile 'com.google.android.gms:play-services-gcm:8.3.0'
    compile 'com.google.android.gms:play-services-maps:8.3.0'
    compile 'com.google.android.gms:play-services-location:8.3.0'
    compile 'com.facebook.android:facebook-android-sdk:[4,5)'
    compile 'com.github.florent37:materialtextfield:1.0.5'
    compile 'com.google.code.gson:gson:2.7'
    compile 'com.github.recruit-lifestyle:WaveSwipeRefreshLayout:1.6'
    compile 'com.google.maps.android:android-maps-utils:0.4'
    compile 'com.github.jd-alexander:LikeButton:0.2.0'
    compile 'com.android.support:recyclerview-v7:24.1.1'
    compile 'com.android.support:cardview-v7:24.1.1'
    compile 'com.mcxiaoke.volley:library-aar:1.0.0'
    compile 'com.android.support:design:24.1.1'
    compile 'com.aurelhubert:ahbottomnavigation:1.3.3'
    compile 'de.hdodenhof:circleimageview:2.1.0'
    compile 'info.hoang8f:android-segmented:1.0.6'
    compile 'com.kyleduo.switchbutton:library:1.4.4'
    compile 'com.longtailvideo.jwplayer:jwplayer-android-sdk:+'
    compile('com.twitter.sdk.android:twitter:2.0.0@aar') {
        transitive = true;
    }
    compile "com.mixpanel.android:mixpanel-android:4.+"

    compile 'org.apache.commons:commons-io:1.3.2'
    compile files('libs/ShareSDK-Twitter-2.7.7.jar')
    compile files('libs/ShareSDK-Core-2.7.7.jar')
    compile files('libs/MobTools-2016.0830.1940.jar')
    compile files('libs/MobCommons-2016.0830.1940.jar')
    compile files('libs/ShareSDK-FacebookMessenger-2.7.7.jar')
    compile files('libs/ShareSDK-Email-2.7.7.jar')
    compile files('libs/ShareSDK-Facebook-2.7.7.jar')
    compile files('libs/ShareSDK-ShortMessage-2.7.7.jar')
}

```

**Comment by ywj7931** [comment]
That 
` compile 'com.longtailvideo.jwplayer:jwplayer-android-sdk:+'`
is requiring me using google 8.3 service, is there other solution I can solve the crash without using other version's google service?

**Comment by patedit** [comment]
It seems that this dependency is not compatible with that version of google play services:
`compile 'com.android.support:appcompat-v7:24.1.1'`

Can you use a lower version? 
`compile 'com.android.support:appcompat-v7:23.4.0'`

Let me know if it worked!

**Comment by ywj7931** [comment]
Still the same error:
```
buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }
}


apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
//apply plugin: 'com.google.gms.google-services'

repositories {
    maven { url 'https://maven.fabric.io/public' }
    maven {
        url "https://jitpack.io"
    }
}
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "ueye.com.fragmenttest"
        minSdkVersion 19
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.google.android.gms:play-services-base:8.3.0'
    compile 'com.google.android.gms:play-services-gcm:8.3.0'
    compile 'com.google.android.gms:play-services-maps:8.3.0'
    compile 'com.google.android.gms:play-services-location:8.3.0'
    compile 'com.facebook.android:facebook-android-sdk:[4,5)'
    compile 'com.github.florent37:materialtextfield:1.0.5'
    compile 'com.google.code.gson:gson:2.7'
    compile 'com.github.recruit-lifestyle:WaveSwipeRefreshLayout:1.6'
    compile 'com.google.maps.android:android-maps-utils:0.4'
    compile 'com.github.jd-alexander:LikeButton:0.2.0'
    compile 'com.android.support:recyclerview-v7:23.4.0'
    compile 'com.android.support:cardview-v7:23.4.0'
    compile 'com.mcxiaoke.volley:library-aar:1.0.0'
    compile 'com.android.support:design:23.4.0'
    compile 'com.aurelhubert:ahbottomnavigation:1.3.3'
    compile 'de.hdodenhof:circleimageview:2.1.0'
    compile 'info.hoang8f:android-segmented:1.0.6'
    compile 'com.kyleduo.switchbutton:library:1.4.4'
    compile 'com.longtailvideo.jwplayer:jwplayer-android-sdk:+'
    compile('com.twitter.sdk.android:twitter:2.0.0@aar') {
        transitive = true;
    }
    compile "com.mixpanel.android:mixpanel-android:4.+"

    compile 'org.apache.commons:commons-io:1.3.2'
    compile files('libs/ShareSDK-Twitter-2.7.7.jar')
    compile files('libs/ShareSDK-Core-2.7.7.jar')
    compile files('libs/MobTools-2016.0830.1940.jar')
    compile files('libs/MobCommons-2016.0830.1940.jar')
    compile files('libs/ShareSDK-FacebookMessenger-2.7.7.jar')
    compile files('libs/ShareSDK-Email-2.7.7.jar')
    compile files('libs/ShareSDK-Facebook-2.7.7.jar')
    compile files('libs/ShareSDK-ShortMessage-2.7.7.jar')
}
```

**Comment by ywj7931** [comment]
I followed others' solution and fixed it:
```
configurations.all {
    resolutionStrategy {
        force 'com.android.support:design:23.4.0'
        force 'com.android.support:support-v4:23.4.0'
        force 'com.android.support:appcompat-v7:23.4.0'
    }
}
```

**Comment by ywj7931** [comment]
Thanks very much for your help! I am also wondering, if my app has a setting to disable notification. how do I prevent that user from receiving the notification?

**Comment by patedit** [comment]
Great it is solved. Seems that another library was using a newer version of `design` `support-v4` or `appcompat-v7`.

Regarding your question: You can target users when sending push notifications from mixpanel.com. I'd set a super property for that person with a boolean that specifies whether this person disabled or not notifications from your app settings. You can read more about super properties here: https://mixpanel.com/help/reference/android#superproperties
After that, you can only send push notifications to users that have that super property set to true :)

**Comment by ywj7931** [comment]
@patedit Thank you! Can I ask another question about the notification? When I push the notification, my phones didnt show any popup message or sound or show up in screen when screen is off, I have to slide to see the message, I have turned on the notification in my phones.

**Comment by patedit** [comment]
Our SDK does not turn the screen ON when a notification is received since it could be very annoying for the user. You could, however, implement this functionality on your by using `PowerManager`. Can you confirm that when you turn the screen on manually you can access your push notification? Thanks!

**Comment by ywj7931** [comment]
The notification shows only when I slide down the bar, but it just quietly appeared there.
