### ISSUE TITLE
OOM crash on com.mixpanel.android:mixpanel-android:4.6.4

### ISSUE THREAD

**Issue by akhgupta** [mixpanel/mixpanel-android#398]
Fatal Exception: java.lang.OutOfMemoryError
       at android.graphics.BitmapFactory.nativeDecodeStream(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:650)
       at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:389)
       at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:449)
       at com.newrelic.agent.android.instrumentation.BitmapFactoryInstrumentation.decodeFile(BitmapFactoryInstrumentation.java:36)
       at com.mixpanel.android.util.ImageStore.getImage(ImageStore.java:96)
       at com.mixpanel.android.mpmetrics.DecideChecker.getNotificationImage(DecideChecker.java:258)
       at com.mixpanel.android.mpmetrics.DecideChecker.runDecideCheck(DecideChecker.java:101)
       at com.mixpanel.android.mpmetrics.DecideChecker.runDecideChecks(DecideChecker.java:70)
       at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:269)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by patedit** [comment]
@akhgupta This issue was already fixed. Please, update your SDK library to the latest :)

Thanks!!
