### ISSUE TITLE
Unable to destroy activity SurveyActivity: NullPointerException

### ISSUE THREAD

**Issue by mtrakal** [mixpanel/mixpanel-android#399]
`compile "com.mixpanel.android:mixpanel-android:4.9.2"`

Stacktrace from Fabric. We can't reproduce it, it's user crash (have a lot of users with this crash)

```
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {com.myapp/com.mixpanel.android.surveys.SurveyActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.mixpanel.android.mpmetrics.i$c.b(java.lang.String, java.lang.Object)' on a null object reference
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3877)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3895)
       at android.app.ActivityThread.-wrap5(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5471)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void com.mixpanel.android.mpmetrics.i$c.b(java.lang.String, java.lang.Object)' on a null object reference
       at com.mixpanel.android.surveys.SurveyActivity.onDestroySurvey(SurveyActivity.java:4303)
       at android.app.Activity.performDestroy(Activity.java:7296)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1143)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3864)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3895)
       at android.app.ActivityThread.-wrap5(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5471)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by patedit** [comment]
Hi @mtrakal! Thanks for reporting this. Are you unidentifying the user at some point (i.e. log out will  reset data, etc)? It may be possible that the survey is shown after you unidentified the user. This will help us to implement a proper fix. Thanks!

**Comment by mtrakal** [comment]
Hi @patedit,

user can logout yourself or delete user data (same as logout). It's possible, that's after logout. I have no idea what user do, but hour later after crash we track that user sign in.
Sorry, that I have no more info, but it's just from Fabric...

**Comment by letronje** [comment]
Hi @patedit , i have the exact same issue with our android app . This happens while the user is logged in and other mixpanel API calls work fine.

**Comment by patedit** [comment]
@mtrakal I opened a PR that will fix your issue. Will be available soon. Thanks for your feedback!

**Comment by patedit** [comment]
Guys, this should be fixed now on the latest release. Thanks for your patience!
