### ISSUE TITLE
InAppFragment crash

### ISSUE THREAD

**Issue by klemzy** [mixpanel/mixpanel-android#400]
We have detected the following crash in one of our apps:

`Fatal Exception: java.lang.IllegalStateException: Activity has been destroyed
       at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1450)
       at android.app.BackStackRecord.commitInternal(BackStackRecord.java:687)
       at android.app.BackStackRecord.commit(BackStackRecord.java:663)
       at com.mixpanel.android.mpmetrics.InAppFragment.remove(InAppFragment.java:250)
       at com.mixpanel.android.mpmetrics.InAppFragment.access$000(InAppFragment.java:45)
       at com.mixpanel.android.mpmetrics.InAppFragment$1.run(InAppFragment.java:77)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7225)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by baboog** [comment]
same here ...  on v 4.9.0 ... any fix for this in any later build or any idea or update?

**Comment by kroussevrb** [comment]
@klemzy how's it going :D 

We also stumbled across this issue in a Segment-provided mixpanel bundled sdk (4.5.2)

Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1438)
       at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1456)
       at android.app.BackStackRecord.commitInternal(BackStackRecord.java:707)
       at android.app.BackStackRecord.commit(BackStackRecord.java:671)
       at com.mixpanel.android.mpmetrics.InAppFragment.cleanUp(InAppFragment.java:247)
       at com.mixpanel.android.mpmetrics.InAppFragment.onSaveInstanceState(InAppFragment.java:229)
       at android.app.Fragment.performSaveInstanceState(Fragment.java:2514)
       at android.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:1767)
       at android.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1824)
       at android.app.FragmentController.saveAllState(FragmentController.java:113)
       at android.app.Activity.onSaveInstanceState(Activity.java:1573)
       at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:570)
       at android.support.v7.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:509)
       at android.app.Activity.performSaveInstanceState(Activity.java:1502)
       at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1308)
       at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4964)
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4242)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4301)
       at android.app.ActivityThread.-wrap28(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1669)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by clownba0t** [comment]
This issue (OP's) still seems to occur with version 5.1.3 of the library - I've just received a crash report for a Nexus 7 running Android 6.0.1:

```
Fatal Exception: java.lang.IllegalStateException: Activity has been destroyed
       at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1433)
       at android.app.BackStackRecord.commitInternal(BackStackRecord.java:687)
       at android.app.BackStackRecord.commit(BackStackRecord.java:663)
       at com.mixpanel.android.mpmetrics.InAppFragment.remove(SourceFile:263)
       at com.mixpanel.android.mpmetrics.InAppFragment.access$000(SourceFile:45)
       at com.mixpanel.android.mpmetrics.InAppFragment$1.run(SourceFile:77)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Please do let me know if there's any further information I can provide that would be of use.

**Comment by patedit** [comment]
hopefully this fixes it https://github.com/mixpanel/mixpanel-android/commit/98bb530f9263f3bac0737971acc00dfef7ea4c35 :)
