### ISSUE TITLE
Null pointer exception in com.mixpanel.android.surveys.SurveyActivity

### ISSUE THREAD

**Issue by letronje** [mixpanel/mixpanel-android#404]
I pushed a survey to my android app and the app crashes on launch. the
crash stack trace tells me it has something to do with the Survey sent.
The same survey works on our iOS app without any issue.
We use version 4.9.2 of the mixpanel SDK for android

```
E/AndroidRuntime(13342): java.lang.RuntimeException: Unable to destroy
activity {in.flohapp.pstg/com.mixpanel.android.surveys.SurveyActivity}:
java.lang.NullPointerException: Attempt to invoke interface method 'void
com.mixpanel.android.mpmetrics.MixpanelAPI$People.append(java.lang.String,
java.lang.Object)' on a null object reference
E/AndroidRuntime(13342): at
android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3713)
E/AndroidRuntime(13342): at
android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3731)
E/AndroidRuntime(13342): at
android.app.ActivityThread.access$1400(ActivityThread.java:154)
E/AndroidRuntime(13342): at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
E/AndroidRuntime(13342): at
android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(13342): at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(13342): at
android.app.ActivityThread.main(ActivityThread.java:5276)
E/AndroidRuntime(13342): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13342): at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(13342): at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
E/AndroidRuntime(13342): at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
E/AndroidRuntime(13342): Caused by: java.lang.NullPointerException: Attempt
to invoke interface method 'void
com.mixpanel.android.mpmetrics.MixpanelAPI$People.append(java.lang.String,
java.lang.Object)' on a null object reference
E/AndroidRuntime(13342): at
com.mixpanel.android.surveys.SurveyActivity.onDestroySurvey(SurveyActivity.java:303)
E/AndroidRuntime(13342): at
com.mixpanel.android.surveys.SurveyActivity.onDestroy(SurveyActivity.java:286)
E/AndroidRuntime(13342): at
android.app.Activity.performDestroy(Activity.java:6220)
E/AndroidRuntime(13342): at
android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1144)
E/AndroidRuntime(13342): at
android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3700)
E/AndroidRuntime(13342): ... 10 more
```

**Comment by patedit** [comment]
Hey @letronje - I've created a PR that will fix your issue in the next release. Thanks for the report!
