### ISSUE TITLE
ConcurrentModificationException on Tweaks.getDefaultValues()

### ISSUE THREAD

**Issue by RomainPiel** [mixpanel/mixpanel-android#408]
We've had a few crashes with this stacktrace since we've updated Mixpanel to version 4.9.2. We have a few tweaks in place but non that should involve the view crawler.

```
java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:788)
       at java.util.HashMap$EntryIterator.next(HashMap.java:825)
       at java.util.HashMap$EntryIterator.next(HashMap.java:823)
       at java.util.HashMap.constructorPutAll(HashMap.java:208)
       at java.util.HashMap.<init>(HashMap.java:196)
       at com.mixpanel.android.mpmetrics.Tweaks.getDefaultValues(Tweaks.java:71)
       at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.applyVariantsAndEventBindings(ViewCrawler.java:903)
       at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.initializeChanges(ViewCrawler.java:447)
       at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleEventBindingsReceived(ViewCrawler.java:789)
       at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleMessage(ViewCrawler.java:333)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
```

**Comment by 1jpgodara** [comment]
Same here, After updating mix panel library to version 4.9.2 we are getting so many crashes with same stack trace.

**Comment by abhi-practo** [comment]
@patedit when can we expect this released?

**Comment by patedit** [comment]
@abhi-practo This fix was included in the latest release. Thanks!
