### ISSUE TITLE
ConcurrentModificationException in Tweaks

### ISSUE THREAD

**Issue by agrawalsuneet09** [mixpanel/mixpanel-android#414]
Hi team,

I am facing a crash randomly (logs below) even if we I am not trying to change any tweak value.
I tried to downgrade the mixpanel version number to 4.9.0 but it didn't help.
Please look into the matter as the number of crashes getting increase rapidly.

Thanks

Fatal Exception: java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
       at java.util.HashMap$EntryIterator.next(HashMap.java:891)
       at java.util.HashMap$EntryIterator.next(HashMap.java:890)
       at java.util.HashMap.putAllForCreate(HashMap.java:485)
       at java.util.HashMap.(HashMap.java)
       at com.mixpanel.android.mpmetrics.Tweaks.getDefaultValues(Tweaks.java:61)
       at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.applyVariantsAndEventBindings(ViewCrawler.java:874)
       at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.initializeChanges(ViewCrawler.java:431)
       at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleEventBindingsReceived(ViewCrawler.java:773)
       at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleMessage(ViewCrawler.java:317)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by oparinov** [comment]
Seems like we are having the same problem: http://crashes.to/s/136f52a20e9
Any news regarding this?
Thanks!

**Comment by patedit** [comment]
This will be fixed in the next release 5.0.1. Thanks for reporting it!
