### ISSUE TITLE
Crash from Mixpanel randomly at app startup

### ISSUE THREAD

**Issue by facos86** [mixpanel/mixpanel-android#417]
Hi,
My android app is randomly crashing at startup with the following stackstrace
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: XXX, PID: 24258
                  java.lang.RuntimeException: Unable to pause activity {XXX}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.removeCallbacks(java.lang.Runnable)' on a null object reference
                      at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3751)
                      at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3717)
                      at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3691)
                      at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3665)
                      at android.app.ActivityThread.-wrap16(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1489)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.removeCallbacks(java.lang.Runnable)' on a null object reference
                      at com.mixpanel.android.viewcrawler.ViewCrawler$EmulatorConnector.stop(ViewCrawler.java:169)
                      at com.mixpanel.android.viewcrawler.ViewCrawler$LifecycleCallbacks.uninstallConnectionSensor(ViewCrawler.java:233)
                      at com.mixpanel.android.viewcrawler.ViewCrawler$LifecycleCallbacks.onActivityPaused(ViewCrawler.java:206)
                      at android.app.Application.dispatchActivityPaused(Application.java:225)
                      at android.app.Activity.onPause(Activity.java:1587)
                      at android.support.v4.app.FragmentActivity.onPause(FragmentActivity.java:442)
                      at android.app.Activity.performPause(Activity.java:6819)
                      at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1322)
                      at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3740)
                      at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3717) 
                      at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3691) 
                      at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3665) 
                      at android.app.ActivityThread.-wrap16(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1489) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6119) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by chemickypes** [comment]
I get this error only when use AVD.

**Comment by patedit** [comment]
Fixed 👍
