### ISSUE TITLE
Excessive logging

### ISSUE THREAD

**Issue by dbarwacz** [mixpanel/mixpanel-android#419]
According to 4.9.3 release notes, excessive logging should be limited. Unfortunately I still see insane amount of loggs in debug console. 
```
W/MixpanelAPI.Tweaks: Attempt to reference a tweak "XXX" which has never been defined.
W/MixpanelAPI.Tweaks: Attempt to set a tweak "XXX" which has never been defined.
E/MixpanelAPI.ViewCrawler: Bad editor tweak cannot be applied.
com.mixpanel.android.viewcrawler.EditProtocol$BadInstructionsException: Can't read tweak update
at com.mixpanel.android.viewcrawler.EditProtocol.readTweak(EditProtocol.java:246)
at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.applyVariantsAndEventBindings(ViewCrawler.java:881)
at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleEditorClosed(ViewCrawler.java:835)
at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleMessage(ViewCrawler.java:345)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: org.json.JSONException: No value for value
at org.json.JSONObject.get(JSONObject.java:389)
at org.json.JSONObject.getString(JSONObject.java:550)
at com.mixpanel.android.viewcrawler.EditProtocol.readTweak(EditProtocol.java:239)
at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.applyVariantsAndEventBindings(ViewCrawler.java:881)
at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleEditorClosed(ViewCrawler.java:835)
at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleMessage(ViewCrawler.java:345)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.os.HandlerThread.run(HandlerThread.java:61)
```
I don't know if that is what has actually been fixed, because I have no idea what `No network attempts to visual editor` actually means in context of the lib, so would be great if you linked resolved issues next to release notes comments in the future.

**Comment by jt-gilkeson** [comment]
I'm seeing a ton of these too (can't read tweak update).  Our experiments seem to work fine, but for int/long values I see these read errors being logged quite often.  Seeing in 4.9.8

**Comment by dbarwacz** [comment]
I think https://github.com/mixpanel/mixpanel-android/issues/319 should resolve your problem.
