### ISSUE TITLE
BLUETOOTH permission is listed as optional in docs but seems to be required

### ISSUE THREAD

**Issue by agramian** [mixpanel/mixpanel-android#424]
The [Android setup docs](https://mixpanel.com/help/reference/android#installing-as) under *Step 2 - Add permissions to your AndroidManifest.xml:* list the BLUETOOTH permission as optional but I am seeing a consistent crash for at least a Samsung SM-925T.  I have not tested enough to determine if this is device specific but either way it should not happen.  It causes our app to go into a crash/restart cycle of sometimes more than 10 times.

```
02-02 10:09:11.688 13384-13405/? E/BluetoothAdapter: Application does not have bluetooth permission, registering is failed
02-02 10:09:11.688 13384-13405/? E/BluetoothAdapter: java.lang.SecurityException: Need BLUETOOTH permission: Neither user 10348 nor current process has android.permission.BLUETOOTH.
                                                         at android.os.Parcel.readException(Parcel.java:1620)
                                                         at android.os.Parcel.readException(Parcel.java:1573)
                                                         at android.bluetooth.IBluetoothManager$Stub$Proxy.registerStateChangeCallback(IBluetoothManager.java:350)
                                                         at android.bluetooth.BluetoothAdapter.<init>(BluetoothAdapter.java:594)
                                                         at android.bluetooth.BluetoothAdapter.getDefaultAdapter(BluetoothAdapter.java:576)
                                                         at com.mixpanel.android.mpmetrics.SystemInformation.isBluetoothEnabled(SystemInformation.java:141)
                                                         at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.getDefaultEventProperties(AnalyticsMessages.java:559)
                                                         at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.prepareEventObject(AnalyticsMessages.java:573)
                                                         at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:251)
                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                         at android.os.Looper.loop(Looper.java:158)
                                                         at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by patedit** [comment]
Hi @agramian ! Thanks for reporting this. What's the SDK Version that you are using? Also, have you modified the library somehow?

Thanks!

**Comment by agramian** [comment]
Hi @patedit no I have not modified the library at all.  I'm using it exactly as your docs instruct.  Here's the info from my gradle file.

```
    compileSdkVersion 25
    buildToolsVersion "25.0.2"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 25
...
    compile "com.mixpanel.android:mixpanel-android:4.9.3"
```

**Comment by RockyLin** [comment]
+ 1 same problem
![mixpanel](https://cloud.githubusercontent.com/assets/6820710/23100468/6beac804-f6bc-11e6-8ca5-47fe4e67eb8e.png)

**Comment by edenman** [comment]
What's slightly crazy about this is that there's already this in `SystemInformation.isBluetoothEnabled()`:
```
        } catch (SecurityException e) {
            // do nothing since we don't have permissions
        }
```
I can't figure out from the stacktrace how the app would be crashing on a `SecurityException` from the `getDefaultAdapter()` call

**Comment by patedit** [comment]
Hehe, I know. This crash is pretty crazy (hence my interest of including the permission in the AndroidManifest.xml). I suspect it's an OEM implementation that I'd need to dig into.

**Comment by tHollarek** [comment]
+1 similar issue:
I get the same error message every time i open the app. But it does not crash at least.

Still.. it looks wierd to see error output in my logcat every time I open the app..

**Comment by aliamohsin** [comment]
same here on android N samsung device s8

05-04 08:04:41.778 12607-12634/com.sample.airwatchsdk E/BluetoothAdapter: Application does not have bluetooth permission, registering is failed
05-04 08:04:41.781 12607-12634/com.sample.airwatchsdk E/BluetoothAdapter: java.lang.SecurityException: Need BLUETOOTH permission: Neither user 10201 nor current process has android.permission.BLUETOOTH.
                                                                              at android.os.Parcel.readException(Parcel.java:1693)
                                                                              at android.os.Parcel.readException(Parcel.java:1646)
                                                                              at android.bluetooth.IBluetoothManager$Stub$Proxy.registerStateChangeCallback(IBluetoothManager.java:375)
                                                                              at android.bluetooth.BluetoothAdapter.<init>(BluetoothAdapter.java:640)
                                                                              at android.bluetooth.BluetoothAdapter.getDefaultAdapter(BluetoothAdapter.java:621)
                                                                              at com.mixpanel.android.mpmetrics.SystemInformation.isBluetoothEnabled(SystemInformation.java:144)
                                                                              at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.getDefaultEventProperties(AnalyticsMessages.java:553)
                                                                              at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.prepareEventObject(AnalyticsMessages.java:567)
                                                                              at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:247)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by victor5171** [comment]
I'm having this error too:
07-28 09:24:52.657 12893-13502/br.com.sltalk E/BluetoothAdapter: Application does not have bluetooth permission, registering is failed
07-28 09:24:52.657 12893-13502/br.com.sltalk E/BluetoothAdapter: java.lang.SecurityException: Need BLUETOOTH permission: Neither user 10529 nor current process has android.permission.BLUETOOTH.
                                                                     at android.os.Parcel.readException(Parcel.java:1620)
                                                                     at android.os.Parcel.readException(Parcel.java:1573)
                                                                     at android.bluetooth.IBluetoothManager$Stub$Proxy.registerStateChangeCallback(IBluetoothManager.java:358)
                                                                     at android.bluetooth.BluetoothAdapter.<init>(BluetoothAdapter.java:598)
                                                                     at android.bluetooth.BluetoothAdapter.getDefaultAdapter(BluetoothAdapter.java:580)
                                                                     at com.mixpanel.android.mpmetrics.SystemInformation.isBluetoothEnabled(SystemInformation.java:144)
                                                                     at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.getDefaultEventProperties(AnalyticsMessages.java:620)
                                                                     at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.prepareEventObject(AnalyticsMessages.java:634)
                                                                     at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:294)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                 
                                                                 
                                                                 [ 07-28 09:24:52.667 12893:12893 W/         ]
                                                                 Unable to open '/system/framework/qcom.fmradio.jar': No such file or directory

Any updates on this issue?

**Comment by patedit** [comment]
guys, could you kindly tell me what are the devices you are seeing this issue on and their android version? thanks!

**Comment by RockyLin** [comment]
@patedit Samsung s7 Edge

**Comment by Aidin** [comment]
same issue on S6 EDGE and S7 EDGE

**Comment by patedit** [comment]
what about the android version? is it only happening on N? Do you guys see something in common with all the devices? thanks!

**Comment by Aidin** [comment]
Android API 7.0

**Comment by Aidin** [comment]
both devices

**Comment by eladkatz** [comment]
Same here, on galaxy s7 edge

**Comment by houssemzaier** [comment]
It seems like this bug is still not solved yet. 
 @patedit ,@Mixplanel  can you please resolve the problem ASAP...
We don't really want to have a BLUETOOTH permission in our manifest ..requesting this is really permission so bad for the UX..

**Comment by dementia2029** [comment]
I cant even download my app from play store from emulator because emulators does not have bluetooth!!! FIX IT

**Comment by patedit** [comment]
@dementia2029 Sorry, I am not sure I understand your problem. Whether you can or can't download your app from Google Play is unrelated to this issue.

Guys, hopefully this PR will solve your issue https://github.com/mixpanel/mixpanel-android/pull/499 I'll make a release today!

**Comment by adin234** [comment]
@patedit we can't download a released app (with mixpanel) from google play to our emulator because mixpanel requires bluetooth, if the device doesn't have bluetooth then the app wont show up in google play.

**Comment by levibostian** [comment]
@adin234 because of [this pull request](https://github.com/mixpanel/mixpanel-android/pull/499) Mixpanel no longer *requires* bluetooth. If you would like to remove the need from your manifest, make a release, and try installing on an emulator again, you may do so.

**Comment by adin234** [comment]
@levibostian i just explained to @patedit why this issue and the app not being downloadable from the store and an emulator are related

**Comment by patedit** [comment]
Thanks for the clarification @adin234 ! And nice profile pic 👨‍💻
