### ISSUE TITLE
No virtual method getContext()

### ISSUE THREAD

**Issue by biokys** [mixpanel/mixpanel-android#431]
After upgrade to the newest lib version 4.9.5 we are getting folowing exception:

`Fatal Exception: java.lang.NoSuchMethodError: No virtual method getContext()Landroid/content/Context; in class Lcom/mixpanel/android/mpmetrics/InAppFragment; or its super classes (declaration of 'com.mixpanel.android.mpmetrics.InAppFragment' appears in /data/app/com.droid4you.application.wallet-1/base.apk:classes2.dex)
       at com.mixpanel.android.mpmetrics.InAppFragment.onCreateView(InAppFragment.java:191)
       at android.app.Fragment.performCreateView(Fragment.java:2053)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
       at android.app.BackStackRecord.run(BackStackRecord.java:840)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1454)
       at android.app.Activity.performStart(Activity.java:6054)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2305)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404)
       at android.app.ActivityThread.access$800(ActivityThread.java:154)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5290)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)`

**Comment by patedit** [comment]
Hi @biokys! Thanks for reporting this. It seems that the build tools we are using did not complain about this (known bug: https://code.google.com/p/android/issues/detail?id=185848). @joeymalysz open PR https://github.com/mixpanel/mixpanel-android/pull/432 that has already been merged and I'll make a release asap. Thanks!

**Comment by biokys** [comment]
Cool, i am glad to see such a fast reaction!
