### ISSUE TITLE
Crash in trackNotificationSeen in PeopleImpl

### ISSUE THREAD

**Issue by bjaekel** [mixpanel/mixpanel-android#449]
Hi, we are using mixpanel in our project. We get a random crash in our app in PeopleImpl. Actually I don't see what we could have done wrong. Can you help us with this?

java.lang.RuntimeException: Unable to resume activity: java.lang.NullPointerException: Attempt to invoke interface method 'void com.mixpanel.android.mpmetrics.MixpanelAPI$People.append(java.lang.String, java.lang.Object)' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3430)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3470)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6121)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.mixpanel.android.mpmetrics.MixpanelAPI$People.append(java.lang.String, java.lang.Object)' on a null object reference
	at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl.trackNotificationSeen(Unknown Source)
	at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl$4.run(Unknown Source)
	at android.app.Activity.runOnUiThread(Activity.java:5869)
	at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl.showGivenOrAvailableNotification(Unknown Source)
	at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl.showNotificationIfAvailable(Unknown Source)
	at com.mixpanel.android.mpmetrics.MixpanelActivityLifecycleCallbacks.onActivityStarted(Unknown Source)
	at android.app.Application.dispatchActivityStarted(Application.java:207)
	at android.app.Activity.onStart(Activity.java:1190)
	at android.support.v4.b.r.onStart(Unknown Source)
	at android.support.v7.app.e.onStart(Unknown Source)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
	at android.app.Activity.performStart(Activity.java:6699)
	at android.app.Activity.performRestart(Activity.java:6773)
	at android.app.Activity.performResume(Activity.java:6778)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3407)
	... 8 more

**Comment by patedit** [comment]
Hi @bjaekel! This crash reminds me to this closed issue: https://github.com/mixpanel/mixpanel-android/issues/409
Can you make sure that you are identifying the people profile properly? (i.e. you call  `mYourMixpanelInstance.getPeople().identify(aUserId)`) Hope that fixes it!

**Comment by liminal** [comment]
I would like to expect that my app doesn't crash even if I hadn't made that call. Right now this is the major cause of app crashes in our app by orders of magnitude. Doesn't make me feel very good about using this sdk

**Comment by patedit** [comment]
Sorry @liminal for the confusion. I've protected the SDK from crashing with https://github.com/mixpanel/mixpanel-android/commit/dff88ca59bcffb85c490aa0d13bf2b5dd9cba845
