### ISSUE TITLE
NPE in ViewCrawler

### ISSUE THREAD

**Issue by dmitry-novikov** [mixpanel/mixpanel-android#450]
We have few crashes in prod on `mixpanel-android` version `5.0.0`:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void nx.a()' on a null object reference
       at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.applyVariantsAndEventBindings(ViewCrawler.java:887)
       at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.initializeChanges(ViewCrawler.java:447)
       at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleVariantsReceived(ViewCrawler.java:769)
       at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleMessage(ViewCrawler.java:327)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by patedit** [comment]
Can you update your library to 5.0.1 at least? This should not happen with the latest release (https://github.com/mixpanel/mixpanel-android/pull/448) Let me know if it fixes it!

**Comment by dmitry-novikov** [comment]
We have seen no such crashes anymore in prod after we upgraded to 5.0.2. So I think it could be closed.
