### ISSUE TITLE
Concurrent Modification in ViewCrawler

### ISSUE THREAD

**Issue by fabiocarballo** [mixpanel/mixpanel-android#452]
Hey! We are using 4.9.2 version of Mixpanel and we have the following problem:

```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
       at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.applyVariantsAndEventBindings(ViewCrawler.java:897)
       at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.initializeChanges(ViewCrawler.java:447)
       at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleVariantsReceived(ViewCrawler.java:778)
       at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleMessage(ViewCrawler.java:327)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

We recently launched two beta testing experiences and we are having this crash a lot.

Any idea on how to solve it?

Thanks

**Comment by patedit** [comment]
Hi @fabiocarballo! We fixed this issue with https://github.com/mixpanel/mixpanel-android/pull/448 You should update Mixpanel to 5.0.1 if possible. Let me know if you need anything else 👍
