### ISSUE TITLE
Fatal Exception: android.content.ActivityNotFoundException on 5.0.1

### ISSUE THREAD

**Issue by LupoBianco** [mixpanel/mixpanel-android#455]
Hi, I found some crashes on Fabric.io after library update, here the log:

`Fatal Exception: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.greenapes.horizontalandroid/com.mixpanel.android.takeoverinapp.TakeoverInAppActivity}; have you declared this activity in your AndroidManifest.xml?
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1815)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1531)
       at android.app.Activity.startActivityForResult(Activity.java:4389)
       at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
       at android.app.Activity.startActivityForResult(Activity.java:4348)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
       at android.app.Activity.startActivity(Activity.java:4672)
       at android.app.Activity.startActivity(Activity.java:4640)
       at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl$3.run(MixpanelAPI.java:1878)
       at android.app.Activity.runOnUiThread(Activity.java:6030)
       at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl.showGivenOrAvailableNotification(MixpanelAPI.java:1805)
       at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl.showNotificationIfAvailable(MixpanelAPI.java:1585)
       at com.greenapes.horizontalandroid.services.gaMixpanel.initMixpanel(gaMixpanel.java:40)
       at com.greenapes.horizontalandroid.services.gaMixpanel.<init>(gaMixpanel.java:24)
       at com.greenapes.horizontalandroid.activity_explore.showWindowsDetails(activity_explore.java:492)
       at com.greenapes.horizontalandroid.activity_explore.onClusterItemClick(activity_explore.java:846)
       at com.greenapes.horizontalandroid.activity_explore.onClusterItemClick(activity_explore.java:112)
       at com.google.maps.android.clustering.view.DefaultClusterRenderer$1.onMarkerClick(DefaultClusterRenderer.java:145)
       at com.google.maps.android.MarkerManager.onMarkerClick(MarkerManager.java:103)
       at com.google.maps.android.clustering.ClusterManager.onMarkerClick(ClusterManager.java:207)
       at com.google.android.gms.maps.GoogleMap$2.zza(Unknown Source)
       at com.google.android.gms.maps.internal.zzu$zza.onTransact(Unknown Source)
       at android.os.Binder.transact(Binder.java:507)
       at com.google.android.gms.maps.internal.bz.a(:com.google.android.gms.DynamiteModulesB:84)
       at com.google.maps.api.android.lib6.impl.dd.b(:com.google.android.gms.DynamiteModulesB:292)
       at com.google.maps.api.android.lib6.gmm6.api.e.a(:com.google.android.gms.DynamiteModulesB:242)
       at com.google.maps.api.android.lib6.gmm6.vector.m.a(:com.google.android.gms.DynamiteModulesB:4070)
       at com.google.maps.api.android.lib6.gmm6.vector.af.c(:com.google.android.gms.DynamiteModulesB:611)
       at com.google.maps.api.android.lib6.gmm6.vector.df.onSingleTapConfirmed(:com.google.android.gms.DynamiteModulesB:236)
       at com.google.maps.api.android.lib6.impl.gesture.g.onSingleTapConfirmed(:com.google.android.gms.DynamiteModulesB:189)
       at com.google.maps.api.android.lib6.impl.gesture.i.handleMessage(:com.google.android.gms.DynamiteModulesB:132)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6688)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)`

**Comment by patedit** [comment]
Are you sending in-app notifications and you did not include 
```
<activity android:name="com.mixpanel.android.takeoverinapp.TakeoverInAppActivity"
          android:theme="@style/com_mixpanel_android_TakeoverInAppActivityTheme"/>
```
in your AndroidManifest.xml file?

**Comment by LupoBianco** [comment]
ohhh, I forgot about it. :)
Sorry.

**Comment by patedit** [comment]
Glad we sorted it out :)
