### ISSUE TITLE
Specifying MinimumSessionDuration and SessionTimeoutDuration in xml fails

### ISSUE THREAD

**Issue by mindhacker42** [mixpanel/mixpanel-android#464]
Library: 5.1.0

If I specify session variables in AndroidManifest.xml I get this error that indicates that default value was used.

```
W/Bundle: Key com.mixpanel.android.MPConfig.MinimumSessionDuration expected Long but value was a java.lang.Integer.  The default value 10000 was returned.
W/Bundle: Attempt to cast generated internal exception:
                                           java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
                                               at android.os.Bundle.getLong(Bundle.java:973)
                                               at com.mixpanel.android.mpmetrics.MPConfig.<init>(MPConfig.java:214)
                                               at com.mixpanel.android.mpmetrics.MPConfig.readConfig(MPConfig.java:442)
                                               at com.mixpanel.android.mpmetrics.MPConfig.getInstance(MPConfig.java:116)

W/Bundle: Key com.mixpanel.android.MPConfig.SessionTimeoutDuration expected Long but value was a java.lang.Integer.  The default value 9223372036854775807 was returned.
W/Bundle: Attempt to cast generated internal exception:
                                           java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
                                               at android.os.Bundle.getLong(Bundle.java:973)
                                               at com.mixpanel.android.mpmetrics.MPConfig.<init>(MPConfig.java:215)
                                               at com.mixpanel.android.mpmetrics.MPConfig.readConfig(MPConfig.java:442)
                                               at com.mixpanel.android.mpmetrics.MPConfig.getInstance(MPConfig.java:116)
```

**Comment by patedit** [comment]
Hi @mindhacker42. Thanks for reporting this! I've fixed this issue and made a new release: 5.1.1
