### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by ofekrom** [mixpanel/mixpanel-android#470]
<img width="1047" alt="screen shot 2017-07-11 at 13 44 45" src="https://user-images.githubusercontent.com/19211886/28065087-c3d47b8a-663f-11e7-8f7f-ac13b90f2d21.png">

**Comment by patedit** [comment]
Hi @ofekrom, sorry for the delay. It sees that there are too many jsons queued up for that anonymous user. I thought about using `StringBuffer` but the `toString()` method basically creates a new string and we will run into the same issue. Do you have any thoughts regarding this issue?

**Comment by ofekrom** [comment]
How about transforming the JSONArray to Set<String> and use:
SharedPreferences.Editor#putStringSet()

**Comment by ofekrom** [comment]
Any news? Many users get the exception

**Comment by jonasborggren** [comment]
Also having this issue.

**Comment by jonasborggren** [comment]
It's been 27 days, no answer? 

Still having this issue (1377 crashes, 150 users, last 30 days)
``` 
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 29465836 byte allocation with 16777216 free bytes and 27MB until OOM
       at java.lang.String.<init>(String.java:400)
       at java.lang.AbstractStringBuilder.toString(AbstractStringBuilder.java:633)
       at java.lang.StringBuilder.toString(StringBuilder.java:663)
       at org.json.JSONStringer.toString(JSONStringer.java:430)
       at org.json.JSONArray.toString(JSONArray.java:586)
       at com.mixpanel.android.mpmetrics.PersistentIdentity.writeIdentities(PersistentIdentity.java:555)
       at com.mixpanel.android.mpmetrics.PersistentIdentity.setEventsDistinctId(PersistentIdentity.java:151)
       at com.mixpanel.android.mpmetrics.MixpanelAPI.identify(MixpanelAPI.java:439)
       at // code here for identifying
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1249)
       at android.app.Activity.performResume(Activity.java:6102)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3167)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3223)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
       at android.app.ActivityThread.access$1200(ActivityThread.java:152)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5538)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by ilsinszkibal** [comment]
We also have this crash on Android. Actually it's our main source of crash. Could you please look into this?

<img width="935" alt="screen shot 2017-11-07 at 4 25 00 pm" src="https://user-images.githubusercontent.com/2144485/32501425-3d7b6796-c3d8-11e7-8996-637aaa53b07e.png">
<img width="825" alt="screen shot 2017-11-07 at 4 21 52 pm" src="https://user-images.githubusercontent.com/2144485/32501427-3dc5c8c2-c3d8-11e7-841a-ad35781fb1ee.png">

**Comment by ilsinszkibal** [comment]
Any progress with this?

**Comment by albertopq** [comment]
Also having this issue.

**Comment by ShirlyK** [comment]
Same issue for us as well.


> Fatal Exception: java.lang.OutOfMemoryErrorFailed to allocate a 32012036 byte allocation with 8384576 free bytes and 30MB until OOM Raw Text
> --
>   | java.lang.StringFactory.newStringFromChars (StringFactory.java)
>   | org.json.JSONArray.toString (JSONArray.java:586)
>   | com.mixpanel.android.mpmetrics.PersistentIdentity.writeIdentities (SourceFile:587)
>   | com.mixpanel.android.mpmetrics.PersistentIdentity.storeWaitingPeopleRecord (SourceFile:178)
>   | com.mixpanel.android.mpmetrics.MixpanelAPI.recordPeopleMessage (SourceFile:2120)
>   | com.mixpanel.android.mpmetrics.MixpanelAPI.access$800 (SourceFile:113)
>   | com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl.set (SourceFile:1456)
