### ISSUE TITLE
Screenshot took more than 1 second

### ISSUE THREAD

**Issue by Null-Ouwenjie** [mixpanel/mixpanel-android#514]
```
ViewCrawler: Initializing snapshot with configuration
Snapshot: Screenshot took more than 1 second to be scheduled and executed. No screenshot will be sent.
     java.util.concurrent.TimeoutException
    at java.util.concurrent.FutureTask.get(FutureTask.java:176)
    at io.sugo.android.viewcrawler.ViewSnapshot.snapshots(ViewSnapshot.java:80)
    at io.sugo.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.sendSnapshot(ViewCrawler.java:749)
    at io.sugo.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleMessage(ViewCrawler.java:410)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loop(Looper.java:194)
    at android.os.HandlerThread.run(HandlerThread.java:61)
EditorCnctn: WebSocket closed. Code: 1005, reason: 
URI: 
ViewCrawler: Editor closed- freeing snapshot
```   
What causes it ?

**Comment by patedit** [comment]
It seems that you were connected to our AB visual editor and the SDK was sending a snapshot view of your current activity. This operation has a timeout of 1 second (https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/viewcrawler/ViewSnapshot.java#L75) and it's executed in the UI thread. Were you maybe using the UI thread during that time and it caused a time out?

**Comment by Null-Ouwenjie** [comment]
I was want connected to the visual editor.
there should be no time-consuming operation on my MainActivity
In RootViewFinder class has any time consuming method? is it related to complex layout?
