### ISSUE TITLE
viewcrawler NPE crash

### ISSUE THREAD

**Issue by yuanliu666** [mixpanel/mixpanel-android#515]
Hi I am running app on emulator API 16, using `com.mixpanel.android:mixpanel-android:5.2.1` And it's causing below NPE crash. It works fine on other devices with API 19, 23 and 26. Could you help me with this issue? Thanks.
***
11-16 16:34:15.540 3429-3485/? E/AndroidRuntime: FATAL EXCEPTION: com.mixpanel.android.viewcrawler.ViewCrawler
                                                 java.lang.NullPointerException
                                                     at android.util.Pair.hashCode(Pair.java:62)
                                                     at java.util.HashMap.put(HashMap.java:390)
                                                     at java.util.HashSet.add(HashSet.java:95)
                                                     at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.loadEventBindings(ViewCrawler.java:463)
                                                     at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.loadKnownChanges(ViewCrawler.java:394)
                                                     at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleMessage(ViewCrawler.java:330)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:137)
                                                     at android.os.HandlerThread.run(HandlerThread.java:60)
***

**Comment by argenisf** [comment]
Hey @yuanliu666 

Thanks for the report! This relates to [issue 507](https://github.com/mixpanel/mixpanel-android/issues/507) which has been patched and will be included in our next release.
