### ISSUE TITLE
Fatal Exception: java.lang.StackOverflowError

### ISSUE THREAD

**Issue by bayrontq** [mixpanel/mixpanel-android#523]
Exception triggered by Mixpanel Android 5.2.1 in:
at com.mixpanel.android.mpmetrics.MPDbAdapter.cleanupEvents(MPDbAdapter.java:281)
at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:281)

--------------------------------------------------------------

Fatal Exception: java.lang.StackOverflowError
       at java.lang.String.toUpperCase(String.java:1548)
       at android.database.DatabaseUtils.getSqlStatementType(DatabaseUtils.java:1415)
       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:895)
       at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:594)
       at android.database.sqlite.SQLiteConnection.setPageSize(SQLiteConnection.java:251)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:213)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
       ...
       ...
       ...
       at android.database.sqlite.SQLiteDatabase.onCorruption(SQLiteDatabase.java:338)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:892)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:795)
       at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1012)
       at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:256)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
       **at com.mixpanel.android.mpmetrics.MPDbAdapter.cleanupEvents(MPDbAdapter.java:281)
       at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:281)**
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by patedit** [comment]
Dup https://github.com/mixpanel/mixpanel-android/issues/343
