### ISSUE TITLE
Non StrictMode compliant as of Android O

### ISSUE THREAD

**Issue by Neamar** [mixpanel/mixpanel-android#524]
Hi there,

For application with StrictMode enabled (a tool to display potential problems in the application), under `.penaltyDeath()`, any app using Mixpanel will crash for using an "untagged socket" in OKHttp.

There is a workaround described in https://github.com/square/okhttp/issues/3537 but it has to be done from Mixpanel, and canno't be implemented by an app AFAIK.

Here is a stack trace, going back to mpmetrics:

```
01-02 10:55:48.680 11393-11455/fr.neamar.lolgamedata E/StrictMode: null
                                                                   java.lang.Throwable: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage
                                                                       at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2012)
                                                                       at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:78)
                                                                       at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:47)
                                                                       at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:310)
                                                                       at libcore.io.IoBridge.socket(IoBridge.java:667)
                                                                       at java.net.PlainSocketImpl.socketCreate(PlainSocketImpl.java:116)
                                                                       at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:98)
                                                                       at java.net.Socket.createImpl(Socket.java:484)
                                                                       at java.net.Socket.getImpl(Socket.java:547)
                                                                       at java.net.Socket.setSoTimeout(Socket.java:1175)
                                                                       at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:139)
                                                                       at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
                                                                       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
                                                                       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
                                                                       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
                                                                       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
                                                                       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
                                                                       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
                                                                       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
                                                                       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244)
                                                                       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                                                                       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(Unknown Source:0)
                                                                       at com.mixpanel.android.util.HttpService.performRequest(HttpService.java:126)
                                                                       at com.mixpanel.android.mpmetrics.DecideChecker.getUrls(DecideChecker.java:290)
                                                                       at com.mixpanel.android.mpmetrics.DecideChecker.getDecideResponseFromServer(DecideChecker.java:233)
                                                                       at com.mixpanel.android.mpmetrics.DecideChecker.runDecideCheck(DecideChecker.java:88)
                                                                       at com.mixpanel.android.mpmetrics.DecideChecker.runDecideChecks(DecideChecker.java:70)
                                                                       at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:274)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                       at android.os.Looper.loop(Looper.java:164)
                                                                       at android.os.HandlerThread.run(HandlerThread.java:65)
```

Since using StrictMode in development mode is considered good practice, it would be nice to fix this :) Thanks!

**Comment by swetashinde** [comment]
I agree this needs to be fixed please

**Comment by jamesonwilliams** [comment]
Me too thx

**Comment by patedit** [comment]
Hi @Neamar ! Thanks for reporting this. Mixpanel already allows you to pass your own SocketFactory. Have you tried something like:

```
SocketFactory socketFactory = new DelegatingSocketFactory(SocketFactory.getDefault()) {
      @Override protected Socket configureSocket(Socket socket) throws IOException {
        // set android
        TrafficStats.tagSocket(socket);

        System.out.println("configured");

        return socket;
      }
    };
MPConfig.getInstance(getContext()).setSSLSocketFactory(socketFactory);
```

Let me know if it works!

**Comment by shafty023** [comment]
Agreed this needs to be fixed. Looks like it went stale on Mixpanel's side but needs to be resolved.

**Comment by patedit** [comment]
We can't modify the SDK to be compatible with other SDKs. If you currently use the workaround that was pointed on the thread, you can set the custom socket factory on Mixpanel as well:

`MPConfig.getInstance(getContext()).setSSLSocketFactory(yourFactory);`
