### ISSUE TITLE
MPConfig.java and MixpanelApi.java | Fatal Exception: java.lang.RuntimeException Unable to create application: Package manager has died  Raw Text

### ISSUE THREAD

**Issue by 1jpgodara** [mixpanel/mixpanel-android#525]
`Fatal Exception: java.lang.RuntimeException: Unable to create application com.example.MyApplication: java.lang.RuntimeException: Package manager has died
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4594)
       at android.app.ActivityThread.access$1600(ActivityThread.java:154)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5292)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)`

`Caused by java.lang.RuntimeException: Package manager has died
       at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:279)
       at com.mixpanel.android.mpmetrics.f.b(MPConfig.java:437)
       at com.mixpanel.android.mpmetrics.f.a(MPConfig.java:116)
       at com.mixpanel.android.mpmetrics.g.<init>(MixpanelAPI.java:196)
       at com.mixpanel.android.mpmetrics.g.a(MixpanelAPI.java:336)
       at com.example.b.a(MixpanelManager.java:30)
       at com.example.MyApplication.onCreate(MyApplication.java:140)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4591)
       at android.app.ActivityThread.access$1600(ActivityThread.java:154)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5292)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)`

`Caused by android.os.TransactionTooLargeException
       at android.os.BinderProxy.transactNative(Binder.java)
       at android.os.BinderProxy.transact(Binder.java:496)
       at android.content.pm.IPackageManager$Stub$Proxy.getApplicationInfo(IPackageManager.java:2059)
       at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:270)
       at com.mixpanel.android.mpmetrics.f.b(MPConfig.java:437)
       at com.mixpanel.android.mpmetrics.f.a(MPConfig.java:116)
       at com.mixpanel.android.mpmetrics.g.<init>(MixpanelAPI.java:196)
       at com.mixpanel.android.mpmetrics.g.a(MixpanelAPI.java:336)
       at com.practo.pel.android.b.a(MixpanelManager.java:30)
       at com.practo.pel.android.c.a(PelTracker.java:42)
       at com.example.a.a.a(PelManager.kt:43)
       at com.example.MyApplication.onCreate(MyApplication.java:140)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4591)
       at android.app.ActivityThread.access$1600(ActivityThread.java:154)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5292)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)`

**Comment by GauthierChan** [comment]
We also have this crash in production on a Lenovo Zuk Z1 on 5.1.1

We initialized MixPanel as said in https://mixpanel.com/help/reference/android

**Comment by 1jpgodara** [comment]
@GauthierChan does this initialization, fix the issue?
or you want to say even after following the documentation it's crashing?

**Comment by GauthierChan** [comment]
@1jpgodara even after following the documentation, it's still crashing.

**Comment by 1jpgodara** [comment]
Yeah, same here 😞

**Comment by 1jpgodara** [comment]
@patedit need some help bro

**Comment by patedit** [comment]
Hey @1jpgodara @GauthierChan ! It seems that the `ApplicationInfo` object that is returned after calling `getApplicationInfo()` is too large and can't be serialized (see [this line](https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/mpmetrics/MPConfig.java#L448)).

In order to correctly set-up the SDK we need all the app meta-data info and I believe that [its bundle](http://androidxref.com/5.1.1_r6/xref/frameworks/base/core/java/android/content/pm/PackageItemInfo.java#89) is just too large to serialize. Typically, Android can handle ~1MB per transaction but really depends on the device.

Some questions:
- In what part of the app lifecycle are you guys initializing the library? What other operations are happening at the same time?
- How many `<meta-data>` tags do you have in your `AndroidManifest.xml`?
- Are you running any services / background threads?

**Comment by patedit** [comment]
Closing this due to inactivity.

**Comment by 1jpgodara** [comment]
- In total we have 6-7 `<meta-data>` tags and we have 2 `<meta-data>` tags for `MPConfig`
```
<meta-data
            android:name="com.mixpanel.android.MPConfig.FlushInterval"
            android:value="value"/>
<meta-data
            android:name="com.mixpanel.android.MPConfig.EnableDebugLogging"
            android:value="value"/>
```
- We do the initialization in `onCreate()` of the application.
- Sometimes, yeah we run 1 or 2 background threads/services parallelly.
- Besides 1 or 2 background tasks (even that's not happening always) nothing is happening parallel to initialization of Mixpanel.
