### ISSUE TITLE
Npe for timeEvent method

### ISSUE THREAD

**Issue by saikamisetti** [mixpanel/mixpanel-android#547]
Hi, I consistently get this crash. I am trying to reinstantiate in case of a null mixpanel instance. But of no use.

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.aktivlearn/com.aktivlearn.course.learn.tasks.liaison.LiaisonActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mixpanel.android.mpmetrics.j.a(java.lang.String)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3197)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3305)
       at android.app.ActivityThread.-wrap12(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1894)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7428)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mixpanel.android.mpmetrics.j.a(java.lang.String)' on a null object reference
       at com.aktivlearn.externalMobileAssignment.SimIntroActivity.onStart(SimIntroActivity.java:150)
       at android.app.Fragment.performStart(Fragment.java:2657)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1317)
       at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1554)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1617)
       at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3047)
       at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3004)
       at android.app.FragmentController.dispatchStart(FragmentController.java:189)
       at android.app.Activity.performStart(Activity.java:7398)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3160)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3305)
       at android.app.ActivityThread.-wrap12(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1894)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7428)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by patedit** [comment]
@saikamisetti feel free to open the issue if you need to. Seems it's an implementation error.
