### ISSUE TITLE
Modified React Native Text Elements Cause Crash When Clicked

### ISSUE THREAD

**Issue by mattraj** [mixpanel/mixpanel-android#550]
React Native Text elements cause an immediate crash when they are modified using Mixpanel AB testing as soon as they are clicked. This is the case whether or not they are wrapped in a TouchableHighlight and is persistent.

React Native: 0.52.0
Mixpanel: com.mixpanel.android:mixpanel-android:4.+

Logcat:
05-16 19:08:20.440  1357  1911 D InputDispatcher: notifyMotion - action=ACTION_DOWN(0), id=0, tooltype=1, deviceId=3, source=0x1002, policyFlags=0x0, flags=0x0, metaState=0x0, buttonState=0x0, edgeFlags=0x0, eventTime=9347259456000, downTime=9347259456000, 
05-16 19:08:20.456  1357  1910 D InputTransport: channel '326a891 partners.driver.mystro/partners.driver.mystro.MainActivity (server)' : action=ACTION_DOWN(0), id=0, tooltype=1, deviceId=3, source=0x1002, flags=0x0, edgeFlags=0x0, metaState=0x0, buttonState=0x0, downTime=9347259456000, eventTime=9347259456000, pointerCount=1
05-16 19:08:20.457 19120 19120 I ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
05-16 19:08:20.459 19120 19120 E InputEventReceiver: Exception dispatching input event.
05-16 19:08:20.460 19120 19120 E MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: java.lang.ClassCastException: java.lang.String cannot be cast to android.text.Spanned
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at com.facebook.react.views.text.k.a(ReactTextView.java:79)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at com.facebook.react.uimanager.ag.a(TouchTargetHelper.java:274)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at com.facebook.react.uimanager.ag.a(TouchTargetHelper.java:101)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at com.facebook.react.uimanager.f.a(JSTouchDispatcher.java:166)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at com.facebook.react.uimanager.f.b(JSTouchDispatcher.java:76)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at com.facebook.react.p.b(ReactRootView.java:214)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at com.facebook.react.p.onInterceptTouchEvent(ReactRootView.java:190)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2711)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2343)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2711)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2343)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2711)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2343)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:412)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1832)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.app.Activity.dispatchTouchEvent(Activity.java:3151)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:374)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.View.dispatchPointerEvent(View.java:10177)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4628)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4496)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3947)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4000)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3966)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3974)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3947)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4000)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3966)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4095)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3974)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4152)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3947)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4000)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3966)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3974)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3947)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6437)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6411)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6372)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6569)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.os.MessageQueue.nativePollOnce(Native Method)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.os.MessageQueue.next(MessageQueue.java:323)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.os.Looper.loop(Looper.java:136)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at android.app.ActivityThread.main(ActivityThread.java:6247)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at java.lang.reflect.Method.invoke(Native Method)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
05-16 19:08:20.462 19120 19120 E MessageQueue-JNI: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
05-16 19:08:20.462 19120 19120 D AndroidRuntime: Shutting down VM
05-16 19:08:20.496  1357  1911 D InputDispatcher: notifyMotion - action=ACTION_UP(0), id=0, tooltype=1, deviceId=3, source=0x1002, policyFlags=0x0, flags=0x0, metaState=0x0, buttonState=0x0, edgeFlags=0x0, eventTime=9347316161000, downTime=9347259456000, 
05-16 19:08:20.506  1357  1910 D InputTransport: channel '326a891 partners.driver.mystro/partners.driver.mystro.MainActivity (server)' : action=ACTION_UP(0), id=0, tooltype=1, deviceId=3, source=0x1002, flags=0x0, edgeFlags=0x0, metaState=0x0, buttonState=0x0, downTime=9347259456000, eventTime=9347316161000, pointerCount=1
05-16 19:08:20.632 19120 19120 E AndroidRuntime: FATAL EXCEPTION: main
05-16 19:08:20.632 19120 19120 E AndroidRuntime: Process: partners.driver.mystro, PID: 19120
05-16 19:08:20.632 19120 19120 E AndroidRuntime: java.lang.ClassCastException: java.lang.String cannot be cast to android.text.Spanned
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at com.facebook.react.views.text.k.a(ReactTextView.java:79)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at com.facebook.react.uimanager.ag.a(TouchTargetHelper.java:274)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at com.facebook.react.uimanager.ag.a(TouchTargetHelper.java:101)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at com.facebook.react.uimanager.f.a(JSTouchDispatcher.java:166)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at com.facebook.react.uimanager.f.b(JSTouchDispatcher.java:76)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at com.facebook.react.p.b(ReactRootView.java:214)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at com.facebook.react.p.onInterceptTouchEvent(ReactRootView.java:190)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2711)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2343)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2711)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2343)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2711)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2343)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:412)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1832)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:3151)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:374)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:10177)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4628)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4496)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3947)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4000)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3966)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3974)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3947)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4000)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3966)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4095)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3974)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4152)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3947)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4000)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3966)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3974)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3947)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6437)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6411)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6372)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6569)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:323)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:136)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6247)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
05-16 19:08:20.632 19120 19120 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

**Comment by mattraj** [comment]
Solved -- this issue is caused by an unsafe cast to Spanned in the reactTagForTouch method, which is removed in RN 0.54.0 and above.
