### ISSUE TITLE
Crash of viewcrawler when initializing the library

### ISSUE THREAD

**Issue by gregholst** [mixpanel/mixpanel-android#576]
On one of my test devices running on API 19 I observe a crash even though I have only the initialisation of mixpanel in use (other mixpanel code commented out):

`mMixpanel = MixpanelAPI.getInstance(this, MIXPANEL_TOKEN, true);`

On my other test devices (running on API 17 or much newer versions) I don't observe this crash. Just as a side note, since the sensor manager appear in the stacktrace:
The crashing device has no GPS and screen orientation is always landscape (not possible to change) (it's a payment terminal). 
 
```
FlipGesture.java:89com.mixpanel.android.viewcrawler.FlipGesture.smoothXYZ
FlipGesture.java:24com.mixpanel.android.viewcrawler.FlipGesture.onSensorChanged
SystemSensorManager.java:418android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent
MessageQueue.java:-2android.os.MessageQueue.nativePollOnce
MessageQueue.java:138android.os.MessageQueue.next
Looper.java:123android.os.Looper.loop
ActivityThread.java:5020android.app.ActivityThread.main
Method.java:-2java.lang.reflect.Method.invokeNative
Method.java:515java.lang.reflect.Method.invoke
ZygoteInit.java:785com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
ZygoteInit.java:601com.android.internal.os.ZygoteInit.main
NativeStart.java:-2dalvik.system.NativeStart.main
```
I use the following in my build.gradle file:
`implementation 'com.mixpanel.android:mixpanel-android:5.+'`

**Comment by patedit** [comment]
Hi @gregholst ! I can see the stacktrace there, I'm wondering if you happen to have the exception that is thrown. Thanks!

**Comment by TylerCarberry** [comment]
We are getting the same issue on API level 19 with AndroidX

```

    java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
        at com.mixpanel.android.viewcrawler.FlipGesture.smoothXYZ(FlipGesture.java:89)
        at com.mixpanel.android.viewcrawler.FlipGesture.onSensorChanged(FlipGesture.java:24)
        at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:418)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:138)
        at android.os.Looper.loop(Looper.java:123)
        at android.app.ActivityThread.main(ActivityThread.java:5020)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by patedit** [comment]
Are you all using Android X by any chance?

**Comment by gregholst** [comment]
@patedit No, I am not using Android X.
