### ISSUE TITLE
Exceptions thrown in sendReportTrackToEditor / errors in android log

### ISSUE THREAD

**Issue by ZOlbrys** [mixpanel/mixpanel-android#581]
Hi all,

I'm testing out Mixpanel in a sample Android app and periodically I see the following in logcat:

```
2019-02-18 21:55:00.089 27972-27996/com.example.mixpaneltrackingtestapp E/MixpanelAPI.ViewCrawler: Can't write track_message to server
    com.mixpanel.android.viewcrawler.EditorConnection$EditorConnectionException
        at com.mixpanel.android.viewcrawler.EditorConnection$WebSocketOutputStream.write(EditorConnection.java:143)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at android.util.JsonWriter.flush(JsonWriter.java:384)
        at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.sendReportTrackToEditor(ViewCrawler.java:689)
        at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleMessage(ViewCrawler.java:342)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2019-02-18 21:55:00.090 27972-27996/com.example.mixpaneltrackingtestapp E/MixpanelAPI.ViewCrawler: Can't close writer.
    com.mixpanel.android.viewcrawler.EditorConnection$EditorConnectionException
        at com.mixpanel.android.viewcrawler.EditorConnection$WebSocketOutputStream.write(EditorConnection.java:143)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
        at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:320)
        at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
        at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
        at android.util.JsonWriter.close(JsonWriter.java:393)
        at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.sendReportTrackToEditor(ViewCrawler.java:694)
        at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleMessage(ViewCrawler.java:342)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
    	Suppressed: com.mixpanel.android.viewcrawler.EditorConnection$EditorConnectionException
        at com.mixpanel.android.viewcrawler.EditorConnection$WebSocketOutputStream.close(EditorConnection.java:155)
        at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
        		... 9 more
```

It seems like the tracking I am doing works fine - so are these errors valid?

I have a sample app setup with Mixpanel `5.2.1` showing the issue: https://github.com/ZOlbrys/MixpanelTrackingTestApp 

If you navigate back/forth from the two activities (hit the FAB to show the second activity, and then press back to go back), you should see the errors reported in logcat easily.

**Comment by patedit** [comment]
Hi @ZOlbrys! Those errors are coming from our ViewCrawler which tries to connect your debug build to the visual editor on mixpanel.com. It's the visual editor you'd see if you try to create an AB Test.
Please, dismiss that log for the time being - it will be removed in the future.

**Comment by ZOlbrys** [comment]
@patedit Hello! Any updates on this? I just tested it out with Mixpanel `5.6.2` and I see the same behavior.

**Comment by zihejia** [comment]
Mixpanel is deprecating Messaging and Mobile A/B testing features([more details](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/)), please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation for any critical issues. Sorry for the inconvenience.
