### ISSUE TITLE
Unresolved reference: GCMReceiver

### ISSUE THREAD

**Issue by lpglam** [mixpanel/mixpanel-android#583]
After updated to 5.5.0 the GCMReceiver was gone and no document to introduce new replacement

**Comment by argenisf** [comment]
Hey @lpglam, the release doc for 5.5.0 contains information on how to replace the GCM implementation. [Can you take a look there](https://github.com/mixpanel/mixpanel-android/releases/tag/v5.5.0)?

**Comment by Odaym** [comment]
What on earth is `com.mixpanel.android.mpmetrics.MixpanelFCMMessagingService`, this is always flagged as read in AS, seems like a bogus class name..

**Comment by patedit** [comment]
Sorry, what's your concern about the class name?

**Comment by Odaym** [comment]
Check this screenshot please http://snpy.in/94HX2R

**Comment by Odaym** [comment]
And what if I have two package names that I want to use, `co.mycompany.app` and `co.mycompany.app.debug` and `co.mycompany.app.staging`?

In the Manifest this is not allowed of course 
`<uses-permission android:name="${myAppPackage}.permission.C2D_MESSAGE" />` so I'm guessing i'd have to save these lines somewhere and feed them to the manifest as placeholders? Or do you mean `co.mycompany` only when you say "YOUR_PACKAGE_NAME" in the docs?

thank you

**Comment by Odaym** [comment]
anything?

**Comment by Odaym** [comment]
ah, I just did clear data on the app and relaunched, now it shows why this class is flagged as an error
```
java.lang.RuntimeException: Unable to instantiate service com.mixpanel.android.mpmetrics.MixpanelFCMMessagingService: java.lang.ClassNotFoundException: Didn't find class "com.mixpanel.android.mpmetrics.MixpanelFCMMessagingService" on path: DexPathList[[zip file "/data/app/co.seez.seezr.debug-kmikayxT0R_hqNdI7uVnQA==/base.apk", zip file "/data/app/co.seez.seezr.debug-kmikayxT0R_hqNdI7uVnQA==/split_lib_resources_apk.apk", zip file "/data/app/co.seez.seezr.debug-kmikayxT0R_hqNdI7uVnQA==/split_lib_slice_0_apk.apk"],nativeLibraryDirectories=[/data/app/co.seez.seezr.debug-kmikayxT0R_hqNdI7uVnQA==/lib/arm64, /data/app/co.seez.seezr.debug-kmikayxT0R_hqNdI7uVnQA==/base.apk!/lib/arm64-v8a, /data/app/co.seez.seezr.debug-kmikayxT0R_hqNdI7uVnQA==/split_lib_resources_apk.apk!/lib/arm64-v8a, /data/app/co.seez.seezr.debug-kmikayxT0R_hqNdI7uVnQA==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /system/lib64]]
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3557)
        at android.app.ActivityThread.access$1300(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mixpanel.android.mpmetrics.MixpanelFCMMessagingService" on path: DexPathList[[zip file "/data/app/co.seez.seezr.debug-kmikayxT0R_hqNdI7uVnQA==/base.apk", zip file "/data/app/co.seez.seezr.debug-kmikayxT0R_hqNdI7uVnQA==/split_lib_resources_apk.apk", zip file "/data/app/co.seez.seezr.debug-kmikayxT0R_hqNdI7uVnQA==/split_lib_slice_0_apk.apk"],nativeLibraryDirectories=[/data/app/co.seez.seezr.debug-kmikayxT0R_hqNdI7uVnQA==/lib/arm64, /data/app/co.seez.seezr.debug-kmikayxT0R_hqNdI7uVnQA==/base.apk!/lib/arm64-v8a, /data/app/co.seez.seezr.debug-kmikayxT0R_hqNdI7uVnQA==/split_lib_resources_apk.apk!/lib/arm64-v8a, /data/app/co.seez.seezr.debug-kmikayxT0R_hqNdI7uVnQA==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:103)
        at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:66)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3552)
        at android.app.ActivityThread.access$1300(ActivityThread.java:200) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

How is this supposed to work?

**Comment by patedit** [comment]
Are you adding 5.5.0? If so and AS can't find that class, could you clean your project and or remove Gradle cache files?

You don't need any permissions for this to work. You can remove the permission that you mentioned

**Comment by Odaym** [comment]
I apologize deeply, I misunderstood

**Comment by patedit** [comment]
No worries @Odaym at all! Glad it got resolved :) Let me know if you have any other questions or problems. Thanks for using Mixpanel!

**Comment by gadaramaulik** [comment]
Caused by java.lang.ClassNotFoundException: Didn't find class "com.mixpanel.android.mpmetrics.GCMReceiver" on path: DexPathList[[zip file "/data/app/com.contractorforeman-2/base.apk"],nativeLibraryDirectories=[/data/app/com.contractorforeman-2/lib/arm, /data/app/com.contractorforeman-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3285)
       at android.app.ActivityThread.-wrap20(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1715)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1534)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1424)

how to solve this error?

**Comment by Odaym** [comment]
Run these steps @gadaramaulik https://github.com/mixpanel/mixpanel-android/releases/tag/v5.5.0

For me I'm still unable to receive from the Mixpanel console @patedit but the code is not producing any errors anymore so that's good, I am actually mixed up with how to send the properties to MIxpanel People, is this what's required?

```
val jsonProperties = JSON()
jsonProperties.addString("$token", MY_MIXPANEL_TOKEN)
jsonPRoerpties.addString("$distinct_id", mixpanelApi.distinct_id)
jsonProperties.addString("$android_devices", USER_PUSH_TOKEN)

mixPanelApi.people.set(jsonProperties)
```

is this how they mean by this section of Importing Device Tokens? https://developer.mixpanel.com/docs/android-push-notifications

**Comment by patedit** [comment]
You don't need to do anything besides initializing your Mixpanel instance and creating a people profile:

```
MixpanelAPI mixpanelAPI = MixpanelAPI.getInstance(mContext);
mixpanelAPI.getPeople().identify("Odaym");
```

On mixpanel.com, do you see that profile created with a property `Android devices`?

**Comment by Odaym** [comment]
of course I do this, Mixpanel requires identify to work, how will I see the Android Devices property there if I don't send it as `$android_devices` field as the docs suggest? I do see that property after I send it myself and I am able to get the UI to send the Push but it's not received, how will it know this user's device token if I don't send it (like the docs suggest)? Thanks

**Comment by patedit** [comment]
That's done automatically for you if you add

```
<service
            android:name="com.mixpanel.android.mpmetrics.MixpanelFCMMessagingService"
            android:enabled="true"
            android:exported="false">
            <intent-filter>
                 <action android:name="com.google.firebase.MESSAGING_EVENT"/>
            </intent-filter>
</service>
```

To your `AndroidManifest.xml` file. The class `MixpanelFCMMessagingService` will take care of the registration and push handling for you.

The doc explains that if you don't add this Mixpanel handler, you will need to manually set those properties, as you said.

Do you see any logs on your logcat coming from `FirebaseApp` ?

**Comment by Odaym** [comment]
I removed my user from Mixpanel and logged in again, here is the info that I got, it's all accurate but there's no device token/android devices field of course , see here http://snpy.in/tc7miU please :)

**Comment by Odaym** [comment]
yea, $android_devices is definitely not being sent if I remove those lines

**Comment by patedit** [comment]
If that's the case, there's definitely something missing. Let's try and debug this and figure out what is going on 👍 

1. On your `AndroidManifest.xml` file add the following lines:
```
<meta-data android:name="com.mixpanel.android.MPConfig.EnableDebugLogging"
            android:value="true" />
```

2. Make sure you have the following inside your `application` tag:
```
<service
            android:name="com.mixpanel.android.mpmetrics.MixpanelFCMMessagingService"
            android:enabled="true"
            android:exported="false">
            <intent-filter>
                 <action android:name="com.google.firebase.MESSAGING_EVENT"/>
            </intent-filter>
</service>
```
3. Open your `build.gradle` file and make sure you have firebase messaging dependency added.
4. Start up the app and look for logs.

You will see something like 
```
FirebaseInitProvider: FirebaseApp initialization successful
```
Could you copy and paste your logs and paste them here?

**Comment by Odaym** [comment]
Yes I do see that line, but no other log appears under that tag

`2019-02-25 18:03:41.860 26874-26874/? I/FirebaseInitProvider: FirebaseApp initialization successful`

**Comment by patedit** [comment]
That means that Google Play Services is correctly installed. The rest of the logs won't appear under that tag, could you paste what comes next? Uninstall the app and install it again when you copy your logs. Thanks!

**Comment by Odaym** [comment]
well this is what happened when i launched the app after having uninstalled:

```
2019-02-25 20:22:04.857 7864-7864/co.seez.seezr.debug I/FirebaseInitProvider: FirebaseApp initialization successful
2019-02-25 20:22:04.863 7864-7864/co.seez.seezr.debug I/CrashlyticsInitProvider: CrashlyticsInitProvider skipping initialization
2019-02-25 20:22:04.874 7864-7864/co.seez.seezr.debug I/InstantRun: starting instant run server: is main process
2019-02-25 20:22:04.892 7864-7895/co.seez.seezr.debug W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
2019-02-25 20:22:04.900 7864-7895/co.seez.seezr.debug I/FirebaseAuth: [FirebaseAuth:] Loading module via FirebaseOptions.
2019-02-25 20:22:04.900 7864-7895/co.seez.seezr.debug I/FirebaseAuth: [FirebaseAuth:] Preparing to create service connection to gms implementation
```

Some more logs of mine happened related to network requests, and then this happened:

```
V/MixpanelAPI.Conf: Mixpanel (5.5.0) configured with:
        AutoShowMixpanelUpdates true
        BulkUploadLimit 40
        FlushInterval 60000
        DataExpiration 432000000
        MinimumDatabaseLimit 20971520
        DisableAppOpenEvent true
        DisableViewCrawler false
        DisableGestureBindingUI false
        DisableEmulatorBindingUI false
        EnableDebugLogging true
        TestMode false
        EventsEndpoint https://api.mixpanel.com/track?ip=1
        PeopleEndpoint https://api.mixpanel.com/engage
        DecideEndpoint https://decide.mixpanel.com/decide
        EditorUrl wss://switchboard.mixpanel.com/connect/
        ImageCacheMaxMemoryFactor 10
        DisableDecideChecker false
        IgnoreInvisibleViewsEditor false
        NotificationDefaults 0
        MinimumSessionDuration: 10000
        SessionTimeoutDuration: 2147483647
        DisableExceptionHandler: false
        NotificationChannelId: mp
        NotificationChannelName: Seez Dev
        NotificationChannelImportance: 3

V/MixpanelAPI.Messages: Queuing event for sending later (Thread 18319)
2019-02-25 20:22:05.125 7864-7927/co.seez.seezr.debug V/MixpanelAPI.Messages:     {"event":"$ae_first_open","properties":{"mp_lib":"android","$lib_version":"5.5.0","$os":"Android","$os_version":"9","$manufacturer":"Google","$brand":"google","$model":"Pixel 2 XL","$google_play_services":"available","$screen_dpi":560,"$screen_height":2712,"$screen_width":1440,"$app_version":"2.2.4-dev","$app_version_string":"2.2.4-dev","$app_release":58,"$app_build_number":58,"$has_nfc":true,"$has_telephone":true,"$carrier":"touch","$wifi":true,"$bluetooth_version":"ble","token":"507af41a73c7c6296b0ba145f3124efa","time":1551118925,"distinct_id":"0824e0fa-9e3e-4f65-9f31-c10c20230080","$had_persisted_distinct_id":false,"$device_id":"0824e0fa-9e3e-4f65-9f31-c10c20230080"},"$mp_metadata":{"$mp_event_id":"a49a17a2534e2485","$mp_session_id":"7c01d394f92fc18","$mp_session_seq_id":0,"$mp_session_start_sec":1551118925}} (Thread 18319)
2019-02-25 20:22:05.146 7864-7927/co.seez.seezr.debug V/MixpanelAPI.Messages: Queue depth 1 - Adding flush in 60000 (Thread 18319)
2019-02-25 20:22:05.146 7864-7927/co.seez.seezr.debug V/MixpanelAPI.Messages: Installing a check for in-app notifications (Thread 18319)
2019-02-25 20:22:05.147 7864-7927/co.seez.seezr.debug V/MixpanelAPI.DChecker: Querying decide server, url: https://decide.mixpanel.com/decide?version=1&lib=android&token=507af41a73c7c6296b0ba145f3124efa&distinct_id=0824e0fa-9e3e-4f65-9f31-c10c20230080&properties=%7B%22%24android_lib_version%22%3A%225.5.0%22%2C%22%24android_app_version%22%3A%222.2.4-dev%22%2C%22%24android_version%22%3A%229%22%2C%22%24android_app_release%22%3A58%2C%22%24android_device_model%22%3A%22Pixel+2+XL%22%7D
2019-02-25 20:22:05.148 7864-7927/co.seez.seezr.debug V/MixpanelAPI.Message: ConnectivityManager says we are online
2019-02-25 20:22:05.148 7864-7927/co.seez.seezr.debug V/MixpanelAPI.Message: Attempting request to https://decide.mixpanel.com/decide?version=1&lib=android&token=507af41a73c7c6296b0ba145f3124efa&distinct_id=0824e0fa-9e3e-4f65-9f31-c10c20230080&properties=%7B%22%24android_lib_version%22%3A%225.5.0%22%2C%22%24android_app_version%22%3A%222.2.4-dev%22%2C%22%24android_version%22%3A%229%22%2C%22%24android_app_release%22%3A58%2C%22%24android_device_model%22%3A%22Pixel+2+XL%22%7D
2019-02-25 20:22:05.163 7864-7864/co.seez.seezr.debug D/FirebasePerformance: Creating a new Non Verbose Session: b8c1e9cf24f8446eb2fee9d0c945578b
```

**Comment by patedit** [comment]
I have the feeling it has something to do with the implementation of the SDK. Shoot me an e-mail to sergio.alonso [at] mixpanel [dot] com when you get a chance
