### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException in MixpanelFCMMessagingService.makeNotificationSDK26OrHigher()

### ISSUE THREAD

**Issue by wman1980** [mixpanel/mixpanel-android#599]
Hi Mixpanel-Team,

we released a new version of our app and there are now new crashes which did not exists before:

`Fatal Exception: java.lang.IllegalArgumentException
       at android.os.Parcel.readException(Parcel.java:1971)
       at android.os.Parcel.readException(Parcel.java:1913)
       at android.app.INotificationManager$Stub$Proxy.createNotificationChannels(INotificationManager.java:1488)
       at android.app.NotificationManager.createNotificationChannels(NotificationManager.java:492)
       at android.app.NotificationManager.createNotificationChannel(NotificationManager.java:480)
       at com.mixpanel.android.mpmetrics.MixpanelFCMMessagingService.makeNotificationSDK26OrHigher(MixpanelFCMMessagingService.java:251)
       at com.mixpanel.android.mpmetrics.MixpanelFCMMessagingService.buildNotification(MixpanelFCMMessagingService.java:217)
       at com.mixpanel.android.mpmetrics.MixpanelFCMMessagingService.showPushNotification(MixpanelFCMMessagingService.java:173)
       at com.mixpanel.android.mpmetrics.MixpanelFCMMessagingService.onMessageReceived(MixpanelFCMMessagingService.java:151)
       at myPackage.pushNotifications.MyMessagingService.onMessageReceived(XXX.kt:25)
       at com.mixpanel.android.mpmetrics.MixpanelFCMMessagingService.onMessageReceived(MixpanelFCMMessagingService.java:133)
       at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:60)
       at com.google.firebase.iid.zzg.run(Unknown Source:4)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
       at java.lang.Thread.run(Thread.java:764)`

We are using mixpanel 5.+. The crash occurs on Android 8/9.

Any ideas?

**Comment by wman1980** [comment]
On line 25 in MyMessageService we only call super.onMessageReceived(context, intent).
MyMessageService extends MixpanelFCMMessagingService.

**Comment by wman1980** [comment]
please close that issue. It was my fault.

**Comment by patedit** [comment]
thanks for following up!
