### ISSUE TITLE
ANR in 5.4.5

### ISSUE THREAD

**Issue by ColtonIdle** [mixpanel/mixpanel-android#604]
### Version
*4.13.0*

### Additional information
**Stacktrace**:

Getting an ANR, and while I can't really pinpoint that Mixpanel is the issue, it does show up in the stacktrace in my bugsnag logs. Feel free to close if it's not an issue with Mixpanel.

```
ANR: Application did not respond for at least 5000 ms
        at android.os.BinderProxy.transactNative(Binder.java:-2)
        at android.os.BinderProxy.transact(Binder.java:1140)
        at android.app.IActivityManager$Stub$Proxy.handleApplicationCrash(IActivityManager.java:3560)
        at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:143)
        at com.bugsnag.android.ExceptionHandler.uncaughtException(ExceptionHandler.java:91)
        at com.mixpanel.android.mpmetrics.ExceptionHandler.uncaughtException(ExceptionHandler.java:53)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
        at io.reactivex.plugins.RxJavaPlugins.uncaught(RxJavaPlugins.java:429)
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:383)
        at com.uber.rxdogtag.RxDogTag.reportError(RxDogTag.java:309)
        at com.uber.rxdogtag.DogTagObserver.onError(DogTagObserver.java:61)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:281)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

**Comment by patedit** [comment]
From the stacktrace I can't see how Mixpanel would be causing the ANR. If you have a different report please feel free to re-open the issue
