### ISSUE TITLE
In-App Mini Messages Not Always Showing

### ISSUE THREAD

**Issue by jkopi11** [mixpanel/mixpanel-android#648]
This appears to be an intermittent issue, but in-app messages do not always show for Android.

I updated to version 5.6.5. With debugging enabled, we see this exception:

019-11-13 11:16:36.698 21489-21569/com.amientertainment.AMISmartBar V/MixpanelAPI.DChecker: Mixpanel decide server response was:
    {"notifications":[{"body":"Joe","title_color":4284245368,"close_color":4292534248,"title":"Hello","display_triggers":[{"event":"Check In","selector":{"operator":"==","children":[{"operator":"string","children":[{"property":"event","value":"$os"}]},{"property":"literal","value":"Android"}]}}],"message_id":343568,"buttons":[{"text":"Tap Here","border_color":4292534248,"cta_url":null,"bg_color":4294967295,"text_color":4286288547}],"bg_color":4294967295,"extras":{"image_fade":true},"image_url":"https://cdn4.mxpnl.com/site_media/images/engage/inapp_messages/mini/icon_megaphone.png","type":"takeover","id":4484208,"body_color":4286288547}],"automatic_events":true,"integrations":[]}
2019-11-13 11:16:36.787 21489-21569/com.amientertainment.AMISmartBar V/MixpanelAPI.Message: Attempting request to https://cdn4.mxpnl.com/site_media/images/engage/inapp_messages/mini/icon_megaphone@4x.png
2019-11-13 11:16:37.118 21489-21569/com.amientertainment.AMISmartBar V/MixpanelAPI.DChecker: Can't load image https://cdn4.mxpnl.com/site_media/images/engage/inapp_messages/mini/icon_megaphone@4x.png for a notification
    com.mixpanel.android.util.ImageStore$CantGetImageException: Can't download bitmap
        at com.mixpanel.android.util.ImageStore.getImageFile(ImageStore.java:80)
        at com.mixpanel.android.util.ImageStore.getImage(ImageStore.java:115)
        at com.mixpanel.android.mpmetrics.DecideChecker.getNotificationImage(DecideChecker.java:308)
        at com.mixpanel.android.mpmetrics.DecideChecker.setImages(DecideChecker.java:108)
        at com.mixpanel.android.mpmetrics.DecideChecker.runDecideCheck(DecideChecker.java:129)
        at com.mixpanel.android.mpmetrics.DecideChecker.runDecideCheck(DecideChecker.java:87)
        at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:419)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.io.FileNotFoundException: https://cdn4.mxpnl.com/site_media/images/engage/inapp_messages/mini/icon_megaphone@4x.png
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:26)
        at com.mixpanel.android.util.HttpService.performRequest(HttpService.java:139)
        at com.mixpanel.android.util.ImageStore.getImageFile(ImageStore.java:78)
        at com.mixpanel.android.util.ImageStore.getImage(ImageStore.java:115) 
        at com.mixpanel.android.mpmetrics.DecideChecker.getNotificationImage(DecideChecker.java:308) 
        at com.mixpanel.android.mpmetrics.DecideChecker.setImages(DecideChecker.java:108) 
        at com.mixpanel.android.mpmetrics.DecideChecker.runDecideCheck(DecideChecker.java:129) 
        at com.mixpanel.android.mpmetrics.DecideChecker.runDecideCheck(DecideChecker.java:87) 
        at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:419) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 

It looks like it is appending @4x to the megaphone image file and that image is not available. Not sure if that would be a reason why the in-app message would not show?

**Comment by patedit** [comment]
@jkopi11 do you see later on the logs that it tries to download @2x and then the regular size image?

**Comment by jkopi11** [comment]
I don't see anything that would suggest that.

the next line is:
`2019-11-13 14:34:12.541 5408-5502/com.amientertainment.AMISmartBar V/MixpanelAPI.DecideUpdts: New Decide content has become available. 0 notifications and 0 experiments have been added.
`
And then we don't see it try to download until we restart the app and it's the same error. Not sure if it may have cached already. We're just trying to troubleshoot why we can't get them reliably.

**Comment by patedit** [comment]
It's expected that it tries to fetch the @4x version first and it will fail (we should change the implementation so for mini in-apps it doesn't try to fetch the @4x or @2x since the regular version is big enough. If there is a problem fetching the in-app you should see an error like `Could not retrieve image for notification` which I suspect is not the case.

The message you just pasted here tells you if there is anything new that hasn't been seen yet by the SDK. It's likely that the in-app has been returned before.

Notice that in-apps are shown automatically on every new activity. If you don't want to wait to show the in-app after a new activity is on screen, then you need to manually trigger the in-app display. You can read more about it here: https://developer.mixpanel.com/docs/android-inapp-messages

**Comment by zihejia** [comment]
Mixpanel is deprecating Messaging and Mobile A/B testing features([more details](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/)), please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation for any critical issues. Sorry for the inconvenience.
