### ISSUE TITLE
Wrong URL in EU-API documentation

### ISSUE THREAD

**Issue by d4rken** [mixpanel/mixpanel-android#659]
The[ EU-API docs for Android](https://developer.mixpanel.com/docs/implement-mixpanel#section-android-sdk) have a typo in their URL:

```
<meta-data android:name="com.mixpanel.android.MPConfig.PeopleEndpoint"
           android:value="https://api-eu.mixpanel.com/engage=" />
```

compared to the defaults, the `=` sign is wrong.

https://github.com/mixpanel/mixpanel-android/blob/62786cb25ded116c3655ae52a75c849cf2266247/src/main/java/com/mixpanel/android/util/MPConstants.java#L11

```Kotlin
    java.io.FileNotFoundException: https://api-eu.mixpanel.com/engage=
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
        at com.mixpanel.android.util.HttpService.performRequest(HttpService.java:139)
        at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.sendData(AnalyticsMessages.java:548)
        at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.sendAllData(AnalyticsMessages.java:516)
        at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:425)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by patedit** [comment]
Thanks a lot for reporting this @d4rken. Documentation has been updated :)
