### ISSUE TITLE
Crash in MixpanelAPI.getInstance

### ISSUE THREAD

**Issue by tallior** [mixpanel/mixpanel-android#678]
We started seeing this crash with out latest release (that uses Mixpanel SDK v5.8.0).
Seems to be related to the deprecation of the InstallReferrer intent.

`Caused by java.lang.IllegalArgumentException: Service not registered: com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection@1276263
       at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1680)
       at android.app.ContextImpl.unbindService(ContextImpl.java:1781)
       at android.content.ContextWrapper.unbindService(ContextWrapper.java:730)
       at com.android.installreferrer.api.InstallReferrerClientImpl.endConnection(InstallReferrerClientImpl.java:170)
       at com.mixpanel.android.mpmetrics.InstallReferrerPlay.disconnect(InstallReferrerPlay.java:155)
       at com.mixpanel.android.mpmetrics.InstallReferrerPlay.onInstallReferrerSetupFinished(InstallReferrerPlay.java:120)
       at com.android.installreferrer.api.InstallReferrerClientImpl.startConnection(InstallReferrerClientImpl.java:154)
       at com.mixpanel.android.mpmetrics.InstallReferrerPlay.connect(InstallReferrerPlay.java:132)
       at com.mixpanel.android.mpmetrics.MixpanelAPI.<init>(MixpanelAPI.java:388)
       at com.mixpanel.android.mpmetrics.MixpanelAPI.<init>(MixpanelAPI.java:320)
       at com.mixpanel.android.mpmetrics.MixpanelAPI.getInstance(MixpanelAPI.java:582)
       at com.mixpanel.android.mpmetrics.MixpanelAPI.getInstance(MixpanelAPI.java:468)
       at com.moon.coinmaster.android.GameActivity.onCreate(GameActivity.java:94)
       at android.app.Activity.performCreate(Activity.java:7327)
       at android.app.Activity.performCreate(Activity.java:7318)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3101)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3264)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7078)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)`

Happens on different device models and OS versions.

**Comment by patedit** [comment]
Hi @tallior ! what's the exception that is thrown? Is it an `IllegalArgumentException`? Would be great to see the entire stack trace.
What installreferrer version are you using?

**Comment by tallior** [comment]
@patedit updated with the full stack trace.

**Comment by patedit** [comment]
And what installreferrer version are you using?

**Comment by tallior** [comment]
@patedit our Unity project includes this file: installreferrer-1.0
I believe it is not the "updated" install referrer library (after the recent deprecation).

Could that be the reason for crash ?

**Comment by patedit** [comment]
It seems to be the case, could you upgrade it to 1.1 and see if it works? Thanks!

**Comment by Huulivoide** [comment]
installreferrer v1.1 is not really a option because of the associated permission problems [https://stackoverflow.com/questions/59263642/install-referrer-library-v1-1-adds-permissions](https://stackoverflow.com/questions/59263642/install-referrer-library-v1-1-adds-permissions).

**Comment by pawelqus** [comment]
Any update on this issue? I'm experiencing same crashes. When do you plan to release the fix?

**Comment by patedit** [comment]
Fix has been merged to master. I will cut a release later today :)

**Comment by pawelqus** [comment]
@patedit Could you please make a release? This is #1 crash we get in the app.

**Comment by patedit** [comment]
Release is out! Thanks for your patience 🙏

**Comment by sprakash593** [comment]
how to reproduce this issue
