### ISSUE TITLE
InstallReferrer crash - lib version 1.1.2

### ISSUE THREAD

**Issue by arongeorgel** [mixpanel/mixpanel-android#679]
I have started to see an increased number of crashes due to `com.mixpanel.android.mpmetrics.InstallReferrerPlay` - check stack trace bellow. I'm not sure how to reproduce it yet, it's just something that I'm currently seeing in crashlytics.

Mixpanel library version: 5.8.0
Install Referrer version: 1.1.2

`Fatal Exception: java.lang.RuntimeException: Unable to instantiate receiver com.mixpanel.android.mpmetrics.InstallReferrerPlay: java.lang.IllegalAccessException: java.lang.Class<com.mixpanel.android.mpmetrics.InstallReferrerPlay> is not accessible from java.lang.Class<android.app.AppComponentFactory>
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3808)
       at android.app.ActivityThread.access$1500(ActivityThread.java:220)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1894)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7520)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
`

`Caused by java.lang.IllegalAccessException: java.lang.Class<com.mixpanel.android.mpmetrics.InstallReferrerPlay> is not accessible from java.lang.Class<android.app.AppComponentFactory>
       at java.lang.Class.newInstance(Class.java)
       at android.app.AppComponentFactory.instantiateReceiver(AppComponentFactory.java:110)
       at androidx.core.app.CoreComponentFactory.instantiateReceiver(CoreComponentFactory.java:60)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3801)
       at android.app.ActivityThread.access$1500(ActivityThread.java:220)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1894)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7520)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
`

**Comment by patedit** [comment]
Hi @arongeorgel ! The error makes me think that you are adding `com.mixpanel.android.mpmetrics.InstallReferrerPlay` as a receiver on your `AndroidManifest.xml` file? If that is the case, notice that this class is not a receiver and you don't need to declare it on your manifest. You just need to add a dependency on your `build.gradle`. Check out the release notes to know more: https://github.com/mixpanel/mixpanel-android/releases/tag/v5.8.0

Let me know if that was the case. Thank you!

**Comment by arongeorgel** [comment]
That was indeed the case. I've miss read the release notes
