### ISSUE TITLE
FATAL EXCEPTION: com.mixpanel.android.viewcrawler.ViewCrawler -- java.lang.AssertionError

### ISSUE THREAD

**Issue by Ezike** [mixpanel/mixpanel-android#698]
@patedit Please all my crash events recorded on mixpanel are coming from the SDK
Guess it's somewhere in this [file](https://github.com/mixpanel/mixpanel-android/blob/a89ba15568809add9f42e7253c7f9a6a349a522e/src/main/java/com/mixpanel/android/java_websocket/WebSocketImpl.java)
```@Override
	public boolean isOpen() {
		assert ( readystate == READYSTATE.OPEN ? !flushandclosestate : true );
		return readystate == READYSTATE.OPEN;
	}
```
Full stacktrace
```
FATAL EXCEPTION: com.mixpanel.android.viewcrawler.ViewCrawler
    java.lang.AssertionError
        at com.mixpanel.android.java_websocket.WebSocketImpl.isOpen(WebSocketImpl.java:675)
        at com.mixpanel.android.java_websocket.client.WebSocketClient.connectBlocking(WebSocketClient.java:123)
        at com.mixpanel.android.viewcrawler.EditorConnection.<init>(EditorConnection.java:51)
        at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.connectToEditor(ViewCrawler.java:494)
        at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleMessage(ViewCrawler.java:333)
```

**Comment by Ezike** [comment]
@patedit i still get the crash after setting the manifest flag..

**Comment by patedit** [comment]
Ah, sorry. I assumed it was a crash in production. The emulator uses another flag:

```
<meta-data android:name="com.mixpanel.android.MPConfig.DisableEmulatorBindingUI"
                      android:value="true" /
```

**Comment by Ezike** [comment]
> Ah, sorry. I assumed it was a crash in production. The emulator uses another flag:
> 
> ```
> <meta-data android:name="com.mixpanel.android.MPConfig.DisableEmulatorBindingUI"
>                       android:value="true" /
> ```

Can I set both flags in the manifest @patedit ?

**Comment by patedit** [comment]
Yup, you perfectly can!

**Comment by Ezike** [comment]
> Yup, you perfectly can!

Thanks.
