### ISSUE TITLE
[android] crash in MixpanelNotificationRouteActivity.handleRouteIntent

### ISSUE THREAD

**Issue by valeriyo** [mixpanel/mixpanel-android#699]
version 5.8.3, crashed a couple times in production ()

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.CharSequence android.os.Bundle.getCharSequence(java.lang.String)' on a null object reference
       at com.mixpanel.android.mpmetrics.MixpanelNotificationRouteActivity.handleRouteIntent(MixpanelNotificationRouteActivity.java:46)
       at com.mixpanel.android.mpmetrics.MixpanelNotificationRouteActivity.onCreate(MixpanelNotificationRouteActivity.java:34)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by valeriyo** [comment]
hello there?

**Comment by zihejia** [comment]
hi @valeriyo, the fix is included in the new version https://github.com/mixpanel/mixpanel-android/releases/tag/v5.8.5 we just released. I'm closing this one now, please feel free to reopen it if the problem still exists.
