### ISSUE TITLE
AssertionError from ViewCrawler

### ISSUE THREAD

**Issue by lhoracek** [mixpanel/mixpanel-android#713]
App randomly crashed when running in debug mode. No events sent to it.
Android API 29
Mixpanel SDK 5.8.4

`
AndroidRuntime: FATAL EXCEPTION: com.mixpanel.android.viewcrawler.ViewCrawler
    Process: com.app.package, PID: 14917
    java.lang.AssertionError
        at com.mixpanel.android.java_websocket.WebSocketImpl.isOpen(WebSocketImpl.java:675)
        at com.mixpanel.android.java_websocket.client.WebSocketClient.connectBlocking(WebSocketClient.java:123)
        at com.mixpanel.android.viewcrawler.EditorConnection.<init>(EditorConnection.java:51)
        at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.connectToEditor(ViewCrawler.java:494)
        at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleMessage(ViewCrawler.java:333)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
`

**Comment by zihejia** [comment]
hi @lhoracek , sorry for the late response, are you still seeing this problem?

**Comment by lhoracek** [comment]
Sorry, I'm not with the project anymore

**Comment by rjsuzuki** [comment]
```
com.mixpanel.android.java_websocket.WebSocketImpl.isOpen (WebSocketImpl.java:675)
com.mixpanel.android.java_websocket.client.WebSocketClient.connectBlocking (WebSocketClient.java:123)
com.mixpanel.android.viewcrawler.EditorConnection.<init> (EditorConnection.java:51)
com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.connectToEditor (ViewCrawler.java:494)
com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleMessage (ViewCrawler.java:333)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:135)
android.os.HandlerThread.run (HandlerThread.java:61) 
```

**Comment by rjsuzuki** [comment]
I'm still seeing this error - especially frequent on Android 5 devices

**Comment by zihejia** [comment]
Hi @rjsuzuki , please try our latest version https://github.com/mixpanel/mixpanel-android/releases/tag/v5.8.8, it has a fix for it. I'm closing this one for now, please feel free to reopen if the problem still exists.

**Comment by rjsuzuki** [comment]
yes I think it has been resolved with the update  - cheers.
