### ISSUE TITLE
App crashing with ConcurrentModificationException in Mixpanel SDK code

### ISSUE THREAD

**Issue by ori-6over6** [mixpanel/mixpanel-android#720]
Hey,

We are seeing crashes in firebase crashlytics that originate in Mixpanel SDK code.
We use version 5.8.4.

This is the relevant part of the stacktrace:
```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757)
       at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:780)
       at com.mixpanel.android.mpmetrics.MixpanelAPI.track(MixpanelAPI.java:2885)
       at com.mixpanel.android.mpmetrics.MixpanelAPI.track(MixpanelAPI.java:868)
```

Could you please take a look?

Thanks in advance!

**Comment by zihejia** [comment]
Hi @ori-6over6 , did you track any properties on the track call? Is there any possibility you modify the properties on another thread during the track call?

**Comment by zihejia** [comment]
I’m closing this issue because it has been inactive for a few months. Please reopen if you still encounter this issue
