### ISSUE TITLE
In-app messages cause: IllegalArgumentException: Software rendering doesn't support hardware bitmaps

### ISSUE THREAD

**Issue by gosr** [mixpanel/mixpanel-android#753]
Same as #711, which was apparently fixed in v5.8.7, but this is still occurring in v5.9.1:

> Fatal Exception: java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
at android.graphics.BaseCanvas.onHwBitmapInSwMode(BaseCanvas.java:673)
at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:680)
at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:84)
at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:142)
at android.graphics.Canvas.drawBitmap(Canvas.java:1648)
at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
at android.widget.ImageView.onDraw(ImageView.java:1453)
at android.view.View.draw(View.java:23901)
at android.view.View.draw(View.java:23773)
at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1975)
at android.view.View.draw(View.java:23771)
at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
at android.view.View.draw(View.java:23771)
at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
at android.view.View.draw(View.java:23904)
at android.view.View.draw(View.java:23773)
at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5030)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
at android.view.View.draw(View.java:23904)
at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429)
at android.view.View.draw(View.java:23773)
at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1975)
at android.view.View.draw(View.java:23771)
at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
at android.view.View.draw(View.java:23771)
at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.java:261)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.java:249)
at android.view.View.draw(View.java:23771)
at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1975)
at android.view.View.draw(View.java:23771)
at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
at android.view.View.draw(View.java:23771)
at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
at android.view.View.draw(View.java:23771)
at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
at android.view.View.draw(View.java:23771)
at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
at android.view.View.draw(View.java:23771)
at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
at android.view.View.draw(View.java:23771)
at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
at android.view.View.draw(View.java:23904)
at com.android.internal.policy.DecorView.draw(DecorView.java:1282)
at com.mixpanel.android.util.ActivityImageUtils.getScaledScreenshot(ActivityImageUtils.java:31)
at com.mixpanel.android.util.ActivityImageUtils.getHighlightColorFromBackground(ActivityImageUtils.java:52)
at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl$2.run(MixpanelAPI.java:2541)
at android.app.Activity.runOnUiThread(Activity.java:7154)
at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl.showGivenOrAvailableNotification(MixpanelAPI.java:2514)
at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl.showGivenNotification(MixpanelAPI.java:2333)
at com.mixpanel.android.mpmetrics.MixpanelAPI.track(MixpanelAPI.java:2928)
at com.mixpanel.android.mpmetrics.MixpanelAPI.track(MixpanelAPI.java:900)
at com.mixpanel.android.mpmetrics.MixpanelAPI.trackMap(MixpanelAPI.java:842)

**Comment by zihejia** [comment]
hi @ gosr , the error is from the Messaging. Are you using it right now?  We are deprecating Messaging and Mobile A/B testing features([more details](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/)). It will be removed on Jan 1, 2022. 
- If you are not using Messaging and Mobile A/B testing , we'd highly suggest you opt into our beta version `implementation "com.mixpanel.android:mixpanel-android:6.0.0-beta+"` It has the current release minus A/B Testing and Messaging and it has our full support. 
- If you are using Messaging and Mobile A/B testing  and do need this fix, please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation. Sorry for the inconvenience.
