### ISSUE TITLE
Crash: HttpService.java line 178 (com.mixpanel.android.util.HttpService.slurp)

### ISSUE THREAD

**Issue by anjalsaneen** [mixpanel/mixpanel-android#774]
**Stacktrace:**
```
Fatal Exception: java.lang.NoClassDefFoundError: com.google.protobuf.y0
       at com.google.protobuf.Protobuf.getInstance(Protobuf.java:55)
       at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:175)
       at com.google.protobuf.GeneratedMessageLite$Builder.buildPartial(GeneratedMessageLite.java:395)
       at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:403)
       at com.google.firebase.perf.session.PerfSession.build(PerfSession.java:126)
       at com.google.firebase.perf.session.PerfSession.buildAndSort(PerfSession.java:145)
       at com.google.firebase.perf.metrics.NetworkRequestMetricBuilder.build(NetworkRequestMetricBuilder.java:316)
       at com.google.firebase.perf.network.InstrHttpInputStream.close(InstrHttpInputStream.java:76)
       at com.mixpanel.android.util.HttpService.performRequest(HttpService.java:160)
       at com.mixpanel.android.mpmetrics.DecideChecker.checkDecide(DecideChecker.java:340)
       at com.mixpanel.android.mpmetrics.DecideChecker.getDecideResponseFromServer(DecideChecker.java:283)
       at com.mixpanel.android.mpmetrics.DecideChecker.runDecideCheck(DecideChecker.java:121)
       at com.mixpanel.android.mpmetrics.DecideChecker.runDecideCheck(DecideChecker.java:87)
       at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:465)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:187)
       at android.os.HandlerThread.run(HandlerThread.java:65)
       
       
       
Caused by java.lang.VerifyError: Verifier rejected class com.google.protobuf.j$b: boolean com.google.protobuf.j$b.B(int) failed to verify: boolean com.google.protobuf.j$b.B(int): [0x41] instance field access on object that has non-reference type Undefined
 long com.google.protobuf.j$b.E() failed to verify: long com.google.protobuf.j$b.E(): [0x2D] register v4 has type Byte but expected Long (Low Half)
 long com.google.protobuf.j$b.G(): [0xFFFFFFFF] invalid branch target -49 (-> 0x16) at 0x47
 long com.google.protobuf.j$b.H() failed to verify: long com.google.protobuf.j$b.H(): [0xD] register v0 has type Precise Low-half Constant: 0 but expected Integer
 void com.google.protobuf.j$b.J(int) failed to verify: void com.google.protobuf.j$b.J(int): [0xA] cannot access instance field com.google.android.gms.internal.ads.n4 com.google.android.gms.internal.ads.vl.a from object of type Precise Reference: com.google.protobuf.j$b
 com.google.protobuf.i com.google.protobuf.j$b.k() failed to verify: com.google.protobuf.i com.google.protobuf.j$b.k(): [0xD] instance field access on object that has non-reference type Integer
 java.lang.String com.google.protobuf.j$b.w() failed to verify: java.lang.String com.google.protobuf.j$b.w(): [0x13] register v0 has type Reference: java.nio.charset.Charset but expected Integer (declaration of 'com.google.protobuf.j$b' appears in base.apk!classes2.dex)
       at com.google.protobuf.CodedInputStream.newInstance(CodedInputStream.java:146)
       at com.google.protobuf.CodedInputStream.newInstance(CodedInputStream.java:140)
       at com.google.protobuf.CodedInputStream.newInstance(CodedInputStream.java:135)
       at com.google.protobuf.Internal.<clinit>(Internal.java:381)
       at com.google.protobuf.ManifestSchemaFactory.<init>(ManifestSchemaFactory.java:48)
       at com.google.protobuf.ManifestSchemaFactory.<init>(ManifestSchemaFactory.java:44)
       at com.google.protobuf.Protobuf.<init>(Protobuf.java:137)
       at com.google.protobuf.Protobuf.<clinit>(Protobuf.java:45)
       at com.google.protobuf.Protobuf.getInstance(Protobuf.java:55)
       at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:175)
       at com.google.protobuf.GeneratedMessageLite$Builder.buildPartial(GeneratedMessageLite.java:395)
       at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:403)
       at com.google.firebase.perf.session.PerfSession.build(PerfSession.java:126)
       at com.google.firebase.perf.session.PerfSession.buildAndSort(PerfSession.java:145)
       at com.google.firebase.perf.metrics.NetworkRequestMetricBuilder.build(NetworkRequestMetricBuilder.java:316)
       at com.google.firebase.perf.network.InstrHttpInputStream.read(InstrHttpInputStream.java:130)
       at com.mixpanel.android.util.HttpService.slurp(HttpService.java:178)
       at com.mixpanel.android.util.HttpService.performRequest(HttpService.java:140)
       at com.mixpanel.android.mpmetrics.DecideChecker.checkDecide(DecideChecker.java:340)
       at com.mixpanel.android.mpmetrics.DecideChecker.getDecideResponseFromServer(DecideChecker.java:283)
       at com.mixpanel.android.mpmetrics.DecideChecker.runDecideCheck(DecideChecker.java:121)
       at com.mixpanel.android.mpmetrics.DecideChecker.runDecideCheck(DecideChecker.java:87)
       at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:465)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:187)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Other infos:**

- 100% on background
- Repetitive crashes 
- SDK Version: 5.9.5

<img width="517" alt="Screenshot 2021-12-24 at 6 30 15 AM" src="https://user-images.githubusercontent.com/43947967/147303345-1232cb3e-60b1-4cbc-8fbc-50a1f915c45d.png">

<img width="459" alt="Screenshot 2021-12-24 at 6 27 11 AM" src="https://user-images.githubusercontent.com/43947967/147303196-e0e43995-d3df-4258-ba6c-305026beede7.png">

**Comment by zihejia** [comment]
hi @anjalsaneen. Please try v6.0.0. It should not have this issue anymore. I'm closing this one now, please feel free to reopen if the problem still exists.
