### ISSUE TITLE
[ANR] Getting number of new ANR from module - com.mixpanel.android.*

### ISSUE THREAD

**Issue by raghav2945** [mixpanel/mixpanel-android#778]
We'd begun to receive several ANR from your component. Looking at the recored stack, it appears that we are spending a lot of time on the main thread. Which is producing such a rise in the condition and resulting in ANR. If we can outsource the task to another assistance thread, we will most likely be able to resolve this issue.

We are using Mixpanel SDK version as : =  **'6.0.0'**

For a better understanding, I'm sharing a stack trace recorded on Firebase.

- com.mixpanel.android.mpmetrics.MixpanelActivityLifecycleCallbacks$1.run (MixpanelActivityLifecycleCallbacks.java:71)
```
main (runnable): tid=1 systid=2719
       at org.json.JSONObject.<init>(JSONObject.java:122)
       at com.mixpanel.android.mpmetrics.MixpanelActivityLifecycleCallbacks$1.run(MixpanelActivityLifecycleCallbacks.java:71)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7701)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

- com.mixpanel.android.mpmetrics.MixpanelActivityLifecycleCallbacks.onActivityPaused(MixpanelActivityLifecycleCallbacks.java)
```
main (runnable): tid=1 systid=28058
       at com.mixpanel.android.mpmetrics.MixpanelActivityLifecycleCallbacks.onActivityPaused(MixpanelActivityLifecycleCallbacks.java)
       at android.app.Application.dispatchActivityPaused(Application.java:485)
       at android.app.Activity.dispatchActivityPaused(Activity.java:1449)
       at android.app.Activity.onPause(Activity.java:2387)
       at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:388)
       at com.audiomack.activities.BaseActivity.onPause(BaseActivity.kt:39)
       at com.audiomack.ui.home.HomeActivity.onPause(HomeActivity.kt:284)
       at android.app.Activity.performPause(Activity.java:8383)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1510)
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5202)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5163)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5114)
       at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8512)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

- com.mixpanel.android.mpmetrics.MixpanelActivityLifecycleCallbacks.onActivityStarted (MixpanelActivityLifecycleCallbacks.java)
```
main (runnable): tid=1 systid=22220
       at com.mixpanel.android.mpmetrics.MixpanelActivityLifecycleCallbacks.onActivityStarted(MixpanelActivityLifecycleCallbacks.java)
       at android.app.Application.dispatchActivityStarted(Application.java:425)
       at android.app.Activity.dispatchActivityStarted(Activity.java:1382)
       at android.app.Activity.onStart(Activity.java:1873)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:496)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
       at com.audiomack.ui.home.HomeActivity.onStart(HomeActivity.java:295)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
       at android.app.Activity.performStart(Activity.java:8231)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3861)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

Please let us know if you require any other information. We will gladly provide it.

**Comment by raghav2945** [comment]
Hello there,
Any update on this issue? we are still observing this issue.

**Comment by zihejia** [comment]
hi @raghav2945 , sorry for the late response. Is it possible to attach a sample app or code snippet for how to replicate the issue? We have some trouble replicating it.

**Comment by raghav2945** [comment]
Hello @zihejia 

Don't be concerned. 
We've recently seen a drop in the number of reporting on this issue over Firebase. These may have been handled across a number of SDK and application releases. We're keeping a watch on it, and if the count rises again, we'll contact you and provide the desired information.
