### ISSUE TITLE
Crash: HttpService.java line 113 (com.mixpanel.android.util.HttpService.performRequest)

### ISSUE THREAD

**Issue by HarisHoulis** [mixpanel/mixpanel-android#783]
Hi guys,
Today we noticed a weird crash in our _Crashlytics_ dashboard:
```
Fatal Exception: java.lang.NoSuchMethodError: No static method newBuilder()Lcom/google/firebase/perf/v1/NetworkRequestMetric$Builder; in class Lcom/google/firebase/perf/v1/NetworkRequestMetric; or its super classes (declaration of 'com.google.firebase.perf.v1.NetworkRequestMetric' appears in /data/app/gr.androiddev.taxibeat-w4fVWIzh1AjrX8exoOlubw==/base.apk!classes2.dex)
       at com.google.firebase.perf.metrics.NetworkRequestMetricBuilder.<init>(NetworkRequestMetricBuilder.java:61)
       at com.google.firebase.perf.metrics.NetworkRequestMetricBuilder.<init>(NetworkRequestMetricBuilder.java:92)
       at com.google.firebase.perf.metrics.NetworkRequestMetricBuilder.builder(NetworkRequestMetricBuilder.java:84)
       at com.google.firebase.perf.network.FirebasePerfUrlConnection.instrument(FirebasePerfUrlConnection.java:186)
       at com.mixpanel.android.util.HttpService.performRequest(HttpService.java:113)
       at com.mixpanel.android.mpmetrics.DecideChecker.checkDecide(DecideChecker.java:180)
       at com.mixpanel.android.mpmetrics.DecideChecker.getDecideResponseFromServer(DecideChecker.java:158)
       at com.mixpanel.android.mpmetrics.DecideChecker.runDecideCheck(DecideChecker.java:81)
       at com.mixpanel.android.mpmetrics.DecideChecker.runDecideCheck(DecideChecker.java:60)
       at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:462)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

🔥  Our current `Firebase BoM` is `29.1.0` which corresponds to version `20.0.5` of our `com.google.firebase:firebase-perf-ktx` dependency. 

❓ Could it be a class between our different versions of the [Firebase Performance Monitoring](https://firebase.google.com/docs/perf-mon/) lib?

🙇 Thanks in advance!

**Comment by zihejia** [comment]
hi @HarisHoulis , sorry about the late response. Which version are you using? We will be soon deprecating the code `checkDecide` from Mixpanel entirely so you won't be able to see this crash anymore.

**Comment by india2sarthak** [comment]
Hey we got the same crash from one of our usrers. Here is the crash log
```
Fatal Exception: java.lang.InternalError: Thread starting during runtime shutdown
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:733)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:975)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1391)
       at com.google.firebase.perf.transport.TransportManager.log(TransportManager.java:324)
       at com.google.firebase.perf.metrics.NetworkRequestMetricBuilder.build(NetworkRequestMetricBuilder.java:329)
       at com.google.firebase.perf.network.InstrHttpInputStream.close(InstrHttpInputStream.java:76)
       at com.mixpanel.android.util.HttpService.performRequest(HttpService.java:160)
       at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.sendData(AnalyticsMessages.java:571)
       at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.sendAllData(AnalyticsMessages.java:538)
       at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:448)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.os.HandlerThread.run(HandlerThread.java:65)
``` 
Android OS: 9
Device: Galaxy S8
Mixpanel Version: 6.2.2

Any resolution for this?
