### ISSUE TITLE
ANR on MixpanelAPI.getInstance

### ISSUE THREAD

**Issue by SubhrajyotiSen** [mixpanel/mixpanel-android#818]
Hi, Firebase detected an ANR on the SDK init. 

```kotlin
MixpanelAPI.getInstance(
    application,
    BuildConfig.MIXPANEL_ID,
    true,
    false
)
```

Mixpanel Android version: 7.2.1. I don't see anything related to performance post this and hence creating the issue without updating the library.

Attaching the logs below.

```
main (runnable):tid=1 systid=26666 
       at java.lang.Double.valueOf(Double.java:524)
       at com.mixpanel.android.mpmetrics.MixpanelActivityLifecycleCallbacks.<init>(MixpanelActivityLifecycleCallbacks.java:29)
       at com.mixpanel.android.mpmetrics.MixpanelAPI.registerMixpanelActivityLifecycleCallbacks(MixpanelAPI.java:1676)
       at com.mixpanel.android.mpmetrics.MixpanelAPI.<init>(MixpanelAPI.java:168)
       at com.mixpanel.android.mpmetrics.MixpanelAPI.<init>(MixpanelAPI.java:121)
       at com.mixpanel.android.mpmetrics.MixpanelAPI.getInstance(MixpanelAPI.java:503)
       at com.mixpanel.android.mpmetrics.MixpanelAPI.getInstance(MixpanelAPI.java:344)
       at com.keeptruckin.android.fleet.di.module.AppModule$Companion.provideMixpanelAPI(AppModule.kt:102)
       at com.keeptruckin.android.fleet.di.module.AppModule_Companion_ProvideMixpanelAPIFactory.provideMixpanelAPI(AppModule_Companion_ProvideMixpanelAPIFactory.java:39)
       at com.keeptruckin.android.fleet.ui.DaggerMainApplication_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerMainApplication_HiltComponents_SingletonC.java:2607)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.keeptruckin.android.fleet.ui.DaggerMainApplication_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerMainApplication_HiltComponents_SingletonC.java:2604)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.keeptruckin.android.fleet.ui.DaggerMainApplication_HiltComponents_SingletonC$SingletonCImpl.analyticsAppConfigurator(DaggerMainApplication_HiltComponents_SingletonC.java:2382)
       at com.keeptruckin.android.fleet.ui.DaggerMainApplication_HiltComponents_SingletonC$SingletonCImpl.listOfAppConfigurable(DaggerMainApplication_HiltComponents_SingletonC.java:2422)
       at com.keeptruckin.android.fleet.ui.DaggerMainApplication_HiltComponents_SingletonC$SingletonCImpl.compositeAppConfigurator(DaggerMainApplication_HiltComponents_SingletonC.java:2426)
       at com.keeptruckin.android.fleet.ui.DaggerMainApplication_HiltComponents_SingletonC$SingletonCImpl.injectMainApplication2(DaggerMainApplication_HiltComponents_SingletonC.java:2539)
       at com.keeptruckin.android.fleet.ui.DaggerMainApplication_HiltComponents_SingletonC$SingletonCImpl.injectMainApplication(DaggerMainApplication_HiltComponents_SingletonC.java:2514)
       at com.keeptruckin.android.fleet.ui.Hilt_MainApplication.hiltInternalInject(Hilt_MainApplication.java:50)
       at com.keeptruckin.android.fleet.ui.Hilt_MainApplication.onCreate(Hilt_MainApplication.java:41)
       at com.keeptruckin.android.fleet.ui.MainApplication.onCreate(MainApplication.kt:31)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1277)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6759)
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication(unavailable)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7872)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by Tangxiaochuanle** [comment]
I also encountered it at flutter(mixpanel_flutter: ^2.2.0)
