### ISSUE TITLE
Crash happened in ViewCrawler$ViewCrawlerHandler.applyVariantsAndEventBindings on version 5.9.1

### ISSUE THREAD

**Issue by fadhlancl** [mixpanel/mixpanel-android#823]
device detail:
- Vivo Y02
- Android 12

stacktrace: 
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Set java.util.HashMap.keySet()' on a null object reference
       at java.util.HashSet.iterator(HashSet.java:172)
       at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
       at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.applyVariantsAndEventBindings(ViewCrawler.java:1013)
       at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.loadKnownChanges(ViewCrawler.java:396)
       at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleMessage(ViewCrawler.java:330)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:334)
       at android.os.HandlerThread.run(HandlerThread.java:67)
       ```

**Comment by argenisf** [comment]
hey @fadhlancl this looks like a crash on an old version of the library that leverages the view crawler class for A/B testing which has been deprecated for a couple of years now. Have you tried updating to a recent version of our library? This should not happen on versions 7+ of the Android SDK as the A/B testing functionality has been removed.
