### ISSUE TITLE
UnsupportedOperationException

### ISSUE THREAD

**Issue by moksh-tehlan** [mixpanel/mixpanel-android#837]
```
Fatal Exception: java.lang.UnsupportedOperationException:
       at java.util.Collections$UnmodifiableMap.put(Collections.java:1552)
       at org.json.JSONObject.put(JSONObject.java:1056)
       at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl.set(MixpanelAPI.java:1778)
       at com.grappus.battlebucks.domain.analytics.MixpanelService.identifyUser(MixpanelService.java:21)
```
```
       
class MixpanelService(private val mixpanelAPI: MixpanelAPI) : AnalyticsService {
    override fun identifyUser(userId: String, properties: Map<String, Any>?) {
        mixpanelAPI.identify(userId)
        properties?.let { mixpanelAPI.people.set(JsonUtils.toJsonObject(it)) }
    }
}

```

It only happens only with release build
```
buildTypes {
        release {
            isMinifyEnabled = true
            isDebuggable = false
            isShrinkResources = true

            proguardFiles(

                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
```

**Comment by jaredmixpanel** [comment]
@moksh-tehlan seems like this might be due to how ProGuard is obfuscating or optimizing your code in the release build. You might want to try adding rules to your ProGuard configuration file, things like...

```
# Preserve the Mixpanel API and related classes
-keep class com.mixpanel.** { *; }
-dontwarn com.mixpanel.**

# Preserve the JSONObject methods used by Mixpanel
-keep class org.json.JSONObject { *; }

# your JsonUtils class
-keep class com.your.package.JsonUtils { *; }

# Preserve your MixpanelService and its methods
-keep class com.grappus.battlebucks.domain.analytics.MixpanelService { *; }
```

**Comment by moksh-tehlan** [comment]
Hey, thanks @jaredmixpanel! 🙌

It was problem with JSONObject after adding below rule it worked like a charm.
`-keep class org.json.JSONObject { *; }`

Really appreciate your help!
