### ISSUE TITLE
DiskRead Violation when calling  in Application class

### ISSUE THREAD

**Issue by akhil-handa** [mixpanel/mixpanel-android#849]
Mixpanel Version : 7.5.2

Violation details 

```
StrictMode policy violation; ~duration=2528 ms: android.os.strictmode.DiskReadViolation (Ask Gemini)
                                                                                                    	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1596)
                                                                                                    	at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:275)
                                                                                                    	at android.app.SharedPreferencesImpl.getAll(SharedPreferencesImpl.java:291)
                                                                                                    	at com.mixpanel.android.mpmetrics.PersistentIdentity.getTimeEvents(PersistentIdentity.java:294)
                                                                                                    	at com.mixpanel.android.mpmetrics.MixpanelAPI.<init>(MixpanelAPI.java:158)
                                                                                                    	at com.mixpanel.android.mpmetrics.MixpanelAPI.<init>(MixpanelAPI.java:122)
                                                                                                    	at com.mixpanel.android.mpmetrics.MixpanelAPI.getInstance(MixpanelAPI.java:454)
                                                                                                    	at com.mixpanel.android.mpmetrics.MixpanelAPI.getInstance(MixpanelAPI.java:227)
                                                                                                    	at zophop.app.etim.DependencyFactory$Companion.initAnalytics(DependencyFactory.kt:145)
                                                                                                    	at zophop.app.etim.DependencyFactory$Companion.init(DependencyFactory.kt:347)
                                                                                                    	at zophop.app.etim.DependencyFactory.init(Unknown Source:2)
                                                                                                    	at zophop.app.etim.application.EtimApplication.onCreate(EtimApplication.java:132)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6776)
                                                                                                    	at android.app.ActivityThread.access$1500(ActivityThread.java:244)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1963)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7723)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1005)
```

**Comment by jaredmixpanel** [comment]
Fixed in `v8.0.3`
