### ISSUE TITLE
java.security.NoSuchAlgorithmException: MessageDigest MD5 implementation not found

### ISSUE THREAD

**Issue by shimitapiro** [mixpanel/mixpanel-android#95]
Hey guys, 
I'm seeing this exception in my bug report system, mostly on 4.1.X systems.
Any idea when will this be fixed ? 

0	java.lang.AssertionError: java.security.NoSuchAlgorithmException: MessageDigest MD5 implementation not found
1		at org.apache.harmony.xnet.provider.jsse.NativeCrypto.X509_NAME_hash(NativeCrypto.java:188)
2		at org.apache.harmony.xnet.provider.jsse.NativeCrypto.X509_NAME_hash_old(NativeCrypto.java:181)
3		at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.hash(TrustedCertificateStore.java:417)
4		at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.findCert(TrustedCertificateStore.java:377)
5		at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.isTrustAnchor(TrustedCertificateStore.java:326)
6		at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.findTrustAnchorBySubjectAndPublicKey(TrustManagerImpl.java:307)
7		at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.cleanupCertChainAndFindTrustAnchors(TrustManagerImpl.java:237)
8		at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:184)
9		at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:163)
10		at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:597)
11		at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
12		at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:395)
13		at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:210)
14		at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478)
15		at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:433)
16		at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:289)
17		at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:239)
18		at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:273)
19		at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:168)
20		at libcore.net.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:271)
21		at com.mixpanel.android.mpmetrics.ServerMessage.performRequest(ServerMessage.java:152)
22		at com.mixpanel.android.mpmetrics.ServerMessage.get(ServerMessage.java:106)
23		at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.getSurveyFromServer(AnalyticsMessages.java:422)
24		at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.runSurveyCheck(AnalyticsMessages.java:367)
25		at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:301)
26		at android.os.Handler.dispatchMessage(Handler.java:99)
27		at android.os.Looper.loop(Looper.java:137)
28		at android.os.HandlerThread.run(HandlerThread.java:60)
29	Caused by: java.security.NoSuchAlgorithmException: MessageDigest MD5 implementation not found
30		at org.apache.harmony.security.fortress.Engine.notFound(Engine.java:177)
31		at org.apache.harmony.security.fortress.Engine.getInstance(Engine.java:151)
32		at java.security.MessageDigest.getInstance(MessageDigest.java:91)
33		at org.apache.harmony.xnet.provider.jsse.NativeCrypto.X509_NAME_hash(NativeCrypto.java:185)
34		... 27 more
35	java.security.NoSuchAlgorithmException: MessageDigest MD5 implementation not found
36		at org.apache.harmony.security.fortress.Engine.notFound(Engine.java:177)
37		at org.apache.harmony.security.fortress.Engine.getInstance(Engine.java:151)
38		at java.security.MessageDigest.getInstance(MessageDigest.java:91)
39		at org.apache.harmony.xnet.provider.jsse.NativeCrypto.X509_NAME_hash(NativeCrypto.java:185)
40		at org.apache.harmony.xnet.provider.jsse.NativeCrypto.X509_NAME_hash_old(NativeCrypto.java:181)
41		at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.hash(TrustedCertificateStore.java:417)
42		at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.findCert(TrustedCertificateStore.java:377)
43		at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.isTrustAnchor(TrustedCertificateStore.java:326)
44		at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.findTrustAnchorBySubjectAndPublicKey(TrustManagerImpl.java:307)
45		at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.cleanupCertChainAndFindTrustAnchors(TrustManagerImpl.java:237)
46		at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:184)
47		at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:163)
48		at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:597)
49		at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
50		at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:395)
51		at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:210)
52		at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478)
53		at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:433)
54		at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:289)
55		at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:239)
56		at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:273)
57		at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:168)
58		at libcore.net.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:271)
59		at com.mixpanel.android.mpmetrics.ServerMessage.performRequest(ServerMessage.java:152)
60		at com.mixpanel.android.mpmetrics.ServerMessage.get(ServerMessage.java:106)
61		at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.getSurveyFromServer(AnalyticsMessages.java:422)
62		at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.runSurveyCheck(AnalyticsMessages.java:367)
63		at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:301)
64		at android.os.Handler.dispatchMessage(Handler.java:99)
65		at android.os.Looper.loop(Looper.java:137)
66		at android.os.HandlerThread.run(HandlerThread.java:60)

Thanks ,
Shimi

**Comment by arittr** [comment]
I've seen this in the wild:

ava.lang.AssertionError: java.security.NoSuchAlgorithmException: MessageDigest MD5 implementation not found
       at org.apache.harmony.xnet.provider.jsse.NativeCrypto.X509_NAME_hash(NativeCrypto.java:188)
       at org.apache.harmony.xnet.provider.jsse.NativeCrypto.X509_NAME_hash_old(NativeCrypto.java:181)
       at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.hash(TrustedCertificateStore.java:417)
       at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.findCert(TrustedCertificateStore.java:377)
       at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.isTrustAnchor(TrustedCertificateStore.java:326)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.findTrustAnchorBySubjectAndPublicKey(TrustManagerImpl.java:307)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.cleanupCertChainAndFindTrustAnchors(TrustManagerImpl.java:237)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:184)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:163)
       at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:573)
       at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(NativeCrypto.java)
       at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:371)
       at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:209)
       at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478)
       at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:433)
       at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:289)
       at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:239)
       at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:273)
       at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:168)
       at libcore.net.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:271)
       at com.mixpanel.android.mpmetrics.ServerMessage.performRequest(ServerMessage.java:104)
       at com.mixpanel.android.mpmetrics.ServerMessage.getUrls(ServerMessage.java:51)
       at com.mixpanel.android.mpmetrics.DecideChecker.getDecideResponseFromServer(DecideChecker.java:206)
       at com.mixpanel.android.mpmetrics.DecideChecker.runDecideCheck(DecideChecker.java:72)
       at com.mixpanel.android.mpmetrics.DecideChecker.runDecideChecks(DecideChecker.java:54)
       at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:259)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by jaredmixpanel** [comment]
Another example stack trace for this issue:

**Comment by louis-schiff** [comment]
We are also getting crashes from this. mostly 4.1.2, but some on 4.0.4. here's a stack trace:
```
java.lang.AssertionError: java.security.NoSuchAlgorithmException: MessageDigest MD5 implementation not found
       at org.apache.harmony.xnet.provider.jsse.NativeCrypto.X509_NAME_hash(NativeCrypto.java:113)
       at org.apache.harmony.xnet.provider.jsse.NativeCrypto.X509_NAME_hash_old(NativeCrypto.java:106)
       at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.hash(TrustedCertificateStore.java:417)
       at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.findCert(TrustedCertificateStore.java:377)
       at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.isTrustAnchor(TrustedCertificateStore.java:326)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.findTrustAnchorBySubjectAndPublicKey(TrustManagerImpl.java:299)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.cleanupCertChainAndFindTrustAnchors(TrustManagerImpl.java:229)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:176)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:163)
       at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:593)
       at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(NativeCrypto.java)
       at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:410)
       at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:257)
       at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:210)
       at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:477)
       at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:432)
       at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:282)
       at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:232)
       at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:273)
       at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:168)
       at libcore.net.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:270)
       at com.mixpanel.android.mpmetrics.ServerMessage.performRequest(ServerMessage.java:104)
       at com.mixpanel.android.mpmetrics.ServerMessage.getUrls(ServerMessage.java:51)
       at com.mixpanel.android.mpmetrics.DecideChecker.getDecideResponseFromServer$60fbfe44(DecideChecker.java:206)
       at com.mixpanel.android.mpmetrics.DecideChecker.runDecideChecks$63ac6e48(DecideChecker.java:54)
       at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:259)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)
Caused by: java.security.NoSuchAlgorithmException: MessageDigest MD5 implementation not found
       at org.apache.harmony.security.fortress.Engine.notFound(Engine.java:177)
       at org.apache.harmony.security.fortress.Engine.getInstance(Engine.java:151)
       at java.security.MessageDigest.getInstance(MessageDigest.java:91)
       at org.apache.harmony.xnet.provider.jsse.NativeCrypto.X509_NAME_hash(NativeCrypto.java:110)
       at org.apache.harmony.xnet.provider.jsse.NativeCrypto.X509_NAME_hash_old(NativeCrypto.java:106)
       at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.hash(TrustedCertificateStore.java:417)
       at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.findCert(TrustedCertificateStore.java:377)
       at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.isTrustAnchor(TrustedCertificateStore.java:326)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.findTrustAnchorBySubjectAndPublicKey(TrustManagerImpl.java:299)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.cleanupCertChainAndFindTrustAnchors(TrustManagerImpl.java:229)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:176)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:163)
       at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:593)
       at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(NativeCrypto.java)
       at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:410)
       at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:257)
       at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:210)
       at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:477)
       at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:432)
       at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:282)
       at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:232)
       at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:273)
       at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:168)
       at libcore.net.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:270)
       at com.mixpanel.android.mpmetrics.ServerMessage.performRequest(ServerMessage.java:104)
       at com.mixpanel.android.mpmetrics.ServerMessage.getUrls(ServerMessage.java:51)
       at com.mixpanel.android.mpmetrics.DecideChecker.getDecideResponseFromServer$60fbfe44(DecideChecker.java:206)
       at com.mixpanel.android.mpmetrics.DecideChecker.runDecideChecks$63ac6e48(DecideChecker.java:54)
       at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:259)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)
```

**Comment by underscoretang** [comment]
Can we reopen this issue? We're getting quite a bit of these and it's a cause for concern. If it's been addressed, could you point us to commit so we can verify it's in the version of mixpanel were on? Thanks

**Comment by jeffwatts** [comment]
Are others who are seeing this issue using Crittercism for crash reporting? We switched from Crittercism to Crashlytics a few months ago, and **if Crashlytics' reports are accurate**, then the issue seems to have disappeared. If this is truly the case and not a reporting anomaly, then I wonder if Crittercism's initialization might have something to do with this crash.

**Comment by joeatwork** [comment]
@underscoretang I'm reopening it - @jeffwatts , thanks for your feedback! Please post here if you see the issue again.

We have a strong suspicion that these errors are caused by settings changed in the global SSL context. Maintainers, consider giving users the ability to provide their own SSLSocketFactory, or otherwise allow optional isolation from the global SSL context.

**Comment by joeatwork** [comment]
Thanks to the folks reporting this, I've got what I believe may be a lead! I've posted an EXPERIMENTAL fix to Maven central, you can give it a go by putting

    compile 'com.mixpanel.android:mixpanel-android-experimental:4.6.1-EXPERIMENTAL'

in your build.gradle dependencies. The body of the fix is here:

   https://github.com/mixpanel/mixpanel-android/compare/EXPERIMENTAL-isolate-ssl

If anyone can reproduce the issue reliably, I'd love to hear if the fix applies!

**Comment by joeatwork** [comment]
I've got a release-reasonable PRQ that may address this issue in https://github.com/mixpanel/mixpanel-android/pull/231 - we'll likely release this in any case, even if it doesn't fix this particular issue, since it seems like an overall improvement to how the library deals with SSL in the presence of other third party libraries and allows devs more freedom of action in configuring SSL connections that they control themselves.

**Comment by joeatwork** [comment]
I've made a new minor release of the library, version 4.6.1, that may fix this problem. I'm not going to close this issue until I get confirmation - the new release changes how Mixpanel configures it's SSL context in a way that should eliminate problems coming from other libraries. I'd really appreciate feedback if adopting version v4.6.1 solves the problem!

**Comment by yinfeiru** [comment]
Closing. Please re-open if anyone sees this issue again.

**Comment by marwanad** [comment]
We're still getting this issue. These logs were pulled from an LG-LG730 running Android 4.1.2
```
Fatal Exception: java.lang.AssertionError: java.security.NoSuchAlgorithmException: MessageDigest MD5 implementation not found
       at org.apache.harmony.xnet.provider.jsse.NativeCrypto.X509_NAME_hash(NativeCrypto.java:188)
       at org.apache.harmony.xnet.provider.jsse.NativeCrypto.X509_NAME_hash_old(NativeCrypto.java:181)
       at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.hash(TrustedCertificateStore.java:417)
       at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.findCert(TrustedCertificateStore.java:377)
       at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.isTrustAnchor(TrustedCertificateStore.java:326)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.findTrustAnchorBySubjectAndPublicKey(TrustManagerImpl.java:307)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.cleanupCertChainAndFindTrustAnchors(TrustManagerImpl.java:237)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:184)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:163)
       at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:573)
       at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(NativeCrypto.java)
       at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:371)
       at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:209)
       at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478)
       at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:433)
       at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:289)
       at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:239)
       at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:273)
       at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:168)
       at libcore.net.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:271)
       at com.mixpanel.android.util.HttpService.performRequest(SourceFile:101)
       at com.mixpanel.android.mpmetrics.DecideChecker.getUrls(SourceFile:288)
       at com.mixpanel.android.mpmetrics.DecideChecker.getDecideResponseFromServer(SourceFile:231)
       at com.mixpanel.android.mpmetrics.DecideChecker.runDecideCheck(SourceFile:1086)
       at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(SourceFile:277)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)
Caused by java.security.NoSuchAlgorithmException: MessageDigest MD5 implementation not found
       at org.apache.harmony.security.fortress.Engine.notFound(Engine.java:177)
       at org.apache.harmony.security.fortress.Engine.getInstance(Engine.java:146)
       at java.security.MessageDigest.getInstance(MessageDigest.java:91)
       at org.apache.harmony.xnet.provider.jsse.NativeCrypto.X509_NAME_hash(NativeCrypto.java:185)
       at org.apache.harmony.xnet.provider.jsse.NativeCrypto.X509_NAME_hash_old(NativeCrypto.java:181)
       at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.hash(TrustedCertificateStore.java:417)
       at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.findCert(TrustedCertificateStore.java:377)
       at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.isTrustAnchor(TrustedCertificateStore.java:326)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.findTrustAnchorBySubjectAndPublicKey(TrustManagerImpl.java:307)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.cleanupCertChainAndFindTrustAnchors(TrustManagerImpl.java:237)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:184)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:163)
       at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:573)
       at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(NativeCrypto.java)
       at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:371)
       at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:209)
       at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478)
       at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:433)
       at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:289)
       at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:239)
       at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:273)
       at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:168)
       at libcore.net.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:271)
       at com.mixpanel.android.util.HttpService.performRequest(SourceFile:101)
       at com.mixpanel.android.mpmetrics.DecideChecker.getUrls(SourceFile:288)
       at com.mixpanel.android.mpmetrics.DecideChecker.getDecideResponseFromServer(SourceFile:231)
       at com.mixpanel.android.mpmetrics.DecideChecker.runDecideCheck(SourceFile:1086)
       at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(SourceFile:277)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)
```

**Comment by marwanad** [comment]
This seems to be a problem on some devices where MD5 (and others) aren't available. One fix would be to use Spongy Castle as a security provider. 
I still believe you should at least be catching an `AssertionError` here since the number of crashes is somewhat significant.

**Comment by jeffwatts** [comment]
We already install Spongy Castle as a provider, and we still see the issue.

**Comment by marwanad** [comment]
Are you inserting it at 1 ?
Using ```Security.insertAt(new BouncyCastleProvider(), 1);``` seemed to have reduced those crashes.

**Comment by jeffwatts** [comment]
Yes, I have always inserted it at 1.
